### ISSUE TITLE
internal server error teslamate:4000

### ISSUE THREAD

**Issue by ronajon** [adriankumpf/teslamate#1145]
**opening the teslamate deault page give error "internal server error"**

the car was totally down to 0% range when i noticed the error. 
now it's on the charger, but still the error remains

in grafana i can see data is still being received

**Relevant entries from the logs**

```
teslamate_1  | Server: 192.168.0.70:4000 (http)
teslamate_1  | Request: GET /
teslamate_1  | ** (exit) an exception was raised:
teslamate_1  |     ** (ArithmeticError) bad argument in arithmetic expression
teslamate_1  |         (teslamate 1.20.1) lib/teslamate_web/live/car_live/summary.html.leex:203: anonymous fn/1 in TeslaMateWeb.CarLive.Summary.render/1
teslamate_1  |         (teslamate 1.20.1) lib/teslamate_web/live/car_live/summary.html.leex:216: anonymous fn/2 in TeslaMateWeb.CarLive.Summary.render/1
teslamate_1  |         (phoenix_live_view 0.14.7) lib/phoenix_live_view/diff.ex:303: Phoenix.LiveView.Diff.traverse/6
teslamate_1  |         (phoenix_live_view 0.14.7) lib/phoenix_live_view/diff.ex:377: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
teslamate_1  |         (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |         (phoenix_live_view 0.14.7) lib/phoenix_live_view/diff.ex:303: Phoenix.LiveView.Diff.traverse/6
teslamate_1  |         (phoenix_live_view 0.14.7) lib/phoenix_live_view/diff.ex:111: Phoenix.LiveView.Diff.render/3
teslamate_1  |         (phoenix_live_view 0.14.7) lib/phoenix_live_view/static.ex:284: Phoenix.LiveView.Static.to_rendered_content_tag/4
```

some minutes later these logs 

```
teslamate_1  | 21:10:56.330 [error] TeslaApi.Error / 408 – %{
teslamate_1  |   "error" => "vehicle unavailable: {:error=>\"{\\\"error\\\": \\\"timeout\\\"}\"}",
teslamate_1  |   "error_description" => "",
teslamate_1  |   "response" => nil
teslamate_1  | }
teslamate_1  | 21:10:57.140 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 21:11:17.299 [error] TeslaApi.Error / 408 – %{
teslamate_1  |   "error" => "vehicle unavailable: {:error=>\"{\\\"error\\\": \\\"timeout\\\"}\"}",
teslamate_1  |   "error_description" => "",
teslamate_1  |   "response" => nil
teslamate_1  | }
```

**Environment**

- TeslaMate version: 1.20.1
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian GNU/Linux 10 (buster)
- User OS & Browser: Linux Mint, Firefox
- Others:

**Comment by ronajon** [comment]
update:
it's charging now an d the homepage of Teslamate is working again. 
Must have something to do with to 0% charge earlier
