### ISSUE TITLE
Database error after upgrading from 1.4.3 to latest

### ISSUE THREAD

**Issue by IXEguy** [adriankumpf/teslamate#116]
Noticed I was a few versions behind, so decided to update to latest and now I get the following:
`db_1         | 2019-08-26 05:18:16.975 UTC [64] STATEMENT:  SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1)
teslamate_1  | ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name does not exist
teslamate_1  |
teslamate_1  |     query: SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1)
`

I initially updated the images via portainer UI, but that game the the error with c0.name missing as well, so I did a docker-compose up and that is what gave me the output from above.

**Comment by adriankumpf** [comment]
When you restart the `teslamate` container do you see something like `... [info]  Already up` in the logs?

**Comment by IXEguy** [comment]
Started up the containers one-by-one with teslamate staying up & also
restarted teslamate when everything else was running.

Here's a more detailed log, you see something about IncompleteMigrations
when the database comes up:
`
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1),
    (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
    (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5,
    (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4,
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
    (elixir) lib/code.ex:240: Code.eval_string/3,
05:18:24.948 [error] Postgrex.Protocol (#PID<0.3328.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:24.948 [error] Postgrex.Protocol (#PID<0.3333.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:24.948 [error] Postgrex.Protocol (#PID<0.3334.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:24.948 [error] Postgrex.Protocol (#PID<0.3332.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:24.948 [error] Postgrex.Protocol (#PID<0.3331.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:26.608 [error] Postgrex.Protocol (#PID<0.3333.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:26.836 [error] Postgrex.Protocol (#PID<0.3331.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing
domain - :nxdomain,
05:18:26.934 [info] Application teslamate exited:
TeslaMate.Application.start(:normal, []) returned an error: shutdown:
failed to start child: TeslaMate.Api,
    ** (EXIT) an exception was raised:,
        ** (DBConnection.ConnectionError) connection not available and
request was dropped from queue after 2000ms. You can configure how long
requests wait in the queue using :queue_target and :queue_interval. See
DBConnection.start_link/2 for more information,
            (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
            (ecto_sql) lib/ecto/adapters/sql.ex:554:
Ecto.Adapters.SQL.execute/5,
            (ecto) lib/ecto/repo/queryable.ex:153:
Ecto.Repo.Queryable.execute/4,
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
            (teslamate) lib/teslamate/auth.ex:33:
TeslaMate.Auth.get_tokens/0,
            (teslamate) lib/teslamate/api.ex:58: TeslaMate.Api.init/1,
            (stdlib) gen_server.erl:374: :gen_server.init_it/2,
            (stdlib) gen_server.erl:342: :gen_server.init_it/6,
waiting for postgres at db:5432 (2sec),
waiting for postgres at db:5432 (4sec),
waiting for postgres at db:5432 (8sec),
waiting for postgres at db:5432 (16sec),
waiting for postgres at db:5432 (32sec),
14:02:25.270 [info] == Running 20190813184320
TeslaMate.Repo.Migrations.FixIncompleteChargingProcessesV2.up/0 forward,
** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name does not
exist,
,
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1),
    (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
    (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5,
    (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4,
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
    (elixir) lib/code.ex:240: Code.eval_string/3,
14:02:33.475 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at
:::4000 (http),
14:02:33.476 [info] Access TeslaMateWeb.Endpoint at http://muaddib,
14:02:33.521 [info] Found Model 3: 'Electric Barbarella',
14:02:33.534 [info] Application teslamate exited:
TeslaMate.Application.start(:normal, []) returned an error: shutdown:
failed to start child: TeslaMate.Vehicles,
    ** (EXIT) an exception was raised:,
        ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name
does not exist,
,
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1),
            (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
            (ecto_sql) lib/ecto/adapters/sql.ex:554:
Ecto.Adapters.SQL.execute/5,
            (ecto) lib/ecto/repo/queryable.ex:153:
Ecto.Repo.Queryable.execute/4,
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
            (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3,
            (teslamate) lib/teslamate/vehicles.ex:74:
TeslaMate.Vehicles.create_or_update!/1,
            (teslamate) lib/teslamate/vehicles.ex:26: anonymous fn/2 in
TeslaMate.Vehicles.init/1,
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
{"Kernel pid
terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__'
=> true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 38,message
=> nil,postgres => #{code => undefined_column,file =>
<<\"parse_relation.c\">>,line => <<\"3294\">>,message => <<\"column c0.name
does not exist\">>,pg_code => <<\"42703\">>,position => <<\"17\">>,routine
=> <<\"errorMissingColumn\">>,severity => <<\"ERROR\">>,unknown =>
<<\"ERROR\">>},query => <<\"SELECT c0.\\"id\\", c0.\\"name\\",
c0.\\"efficiency\\", c0.\\"eid\\", c0.\\"model\\", c0.\\"version\\",
c0.\\"vid\\", c0.\\"vin\\", c0.\\"inserted_at\\", c0.\\"updated_at\\" FROM
\\"cars\\" AS c0 WHERE (c0.\\"eid\\" =
$1)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,621}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,554}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,18}]},{'Elixir.Ecto.Repo.Queryable',one,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,67}]},{'Elixir.TeslaMate.Vehicles','create_or_update!',1,[{file,\"lib/teslamate/vehicles.ex\"},{line,74}]},{'Elixir.TeslaMate.Vehicles','-init/1-fun-0-',2,[{file,\"lib/teslamate/vehicles.ex\"},{line,26}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1336}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
,
Kernel pid terminated (application_controller)
({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__'
=> true,'__struct__' => 'Elixir.Po
,

,
Crash dump is being written to: erl_crash.dump...done
,
14:02:40.813 [info] == Running 20190813184320
TeslaMate.Repo.Migrations.FixIncompleteChargingProcessesV2.up/0 forward,
** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name does not
exist,
,
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1),
    (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
    (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5,
    (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4,
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
    (elixir) lib/code.ex:240: Code.eval_string/3,
14:02:48.655 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at
:::4000 (http),
14:02:48.655 [info] Access TeslaMateWeb.Endpoint at http://muaddib,
14:02:48.727 [info] Found Model 3: 'Electric Barbarella',
14:02:48.740 [info] Application teslamate exited:
TeslaMate.Application.start(:normal, []) returned an error: shutdown:
failed to start child: TeslaMate.Vehicles,
    ** (EXIT) an exception was raised:,
        ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name
does not exist,
,
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1),
            (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
            (ecto_sql) lib/ecto/adapters/sql.ex:554:
Ecto.Adapters.SQL.execute/5,
            (ecto) lib/ecto/repo/queryable.ex:153:
Ecto.Repo.Queryable.execute/4,
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
            (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3,
            (teslamate) lib/teslamate/vehicles.ex:74:
TeslaMate.Vehicles.create_or_update!/1,
            (teslamate) lib/teslamate/vehicles.ex:26: anonymous fn/2 in
TeslaMate.Vehicles.init/1,
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
{"Kernel pid
terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__'
=> true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 44,message
=> nil,postgres => #{code => undefined_column,file =>
<<\"parse_relation.c\">>,line => <<\"3294\">>,message => <<\"column c0.name
does not exist\">>,pg_code => <<\"42703\">>,position => <<\"17\">>,routine
=> <<\"errorMissingColumn\">>,severity => <<\"ERROR\">>,unknown =>
<<\"ERROR\">>},query => <<\"SELECT c0.\\"id\\", c0.\\"name\\",
c0.\\"efficiency\\", c0.\\"eid\\", c0.\\"model\\", c0.\\"version\\",
c0.\\"vid\\", c0.\\"vin\\", c0.\\"inserted_at\\", c0.\\"updated_at\\" FROM
\\"cars\\" AS c0 WHERE (c0.\\"eid\\" =
$1)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,621}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,554}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,18}]},{'Elixir.Ecto.Repo.Queryable',one,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,67}]},{'Elixir.TeslaMate.Vehicles','create_or_update!',1,[{file,\"lib/teslamate/vehicles.ex\"},{line,74}]},{'Elixir.TeslaMate.Vehicles','-init/1-fun-0-',2,[{file,\"lib/teslamate/vehicles.ex\"},{line,26}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1336}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
,
Kernel pid terminated (application_controller)
({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__'
=> true,'__struct__' => 'Elixir.Po
,

,
Crash dump is being written to: erl_crash.dump...done
,
14:02:56.049 [info] == Running 20190813184320
TeslaMate.Repo.Migrations.FixIncompleteChargingProcessesV2.up/0 forward,
** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.name does not
exist,
,
    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid",
c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at",
c0."updated_at", c0."id" FROM "cars" AS c0 WHERE (c0."id" = $1),
    (ecto_sql) lib/ecto/adapters/sql.ex:621:
Ecto.Adapters.SQL.raise_sql_call_error/1,
    (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5,
    (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4,
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3,
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2,
    (elixir) lib/code.ex:240: Code.eval_string/3,
`

**Comment by adriankumpf** [comment]
Thanks! Can you try again with the latest image (v.16.2)?
