### ISSUE TITLE
Crash after updating to v1.21.0

### ISSUE THREAD

**Issue by IMcD23** [adriankumpf/teslamate#1179]
**Describe the bug**

After updating teslamate to version v1.21.0, the docker container fails to start.

**Relevant entries from the logs**

```
Crash dump is being written to: erl_crash.dump...done
2021-01-04 21:02:19.751 [info] Migrations already up
2021-01-04 21:02:23.492 [info] Version: 1.21.0

2021-01-04 21:02:31.624 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Api

** (EXIT) an exception was raised:
** (CaseClauseError) no case clause matching: {:error, "non-existing domain"}

(teslamate 1.21.0) lib/tesla_api/auth.ex:44: TeslaApi.Auth.handle_response/1
(teslamate 1.21.0) lib/teslamate/api.ex:171: TeslaMate.Api.refresh_tokens/1
(teslamate 1.21.0) lib/teslamate/api.ex:99: TeslaMate.Api.init/1
(stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
(stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
(stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{case_clause,{error,<<\"non-existing domain\">>}},[{'Elixir.TeslaApi.Auth',handle_response,1,[{file,\"lib/tesla_api/auth.ex\"},{line,44}]},{'Elixir.TeslaMate.Api',refresh_tokens,1,[{file,\"lib/teslamate/api.ex\"},{line,171}]},{'Elixir.TeslaMate.Api',init,1,[{file,\"lib/teslamate/api.ex\"},{line,99}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
```

**Environment**

- TeslaMate version: 1.21.0
- Type of installation: Docker

**Comment by trulow** [comment]
Did you double check your docker-compose or your .env file?

Looks like you might have an invalid Fqdn in your settings

**Comment by frietbakker** [comment]
I have this same error with a fresh install on a Synology

**Comment by IMcD23** [comment]
Here's my docker command:
```
docker run -d --name='TeslaMate' --net='private' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'DATABASE_USER'='teslamate' -e 'DATABASE_PASS'='<redacted>' -e 'DATABASE_NAME'='teslamate' -e 'DATABASE_HOST'='TeslaMate-postgres' -e 'MQTT_HOST'='TeslaMate-mosquitto' -v '/mnt/user/appdata/teslamate/import':'/opt/app/import':'rw' 'teslamate/teslamate:latest'
```

The FQDN has not changed since I initially configured it. It _may_ not be resolvable from the container, since it's in a private network. This has not been a problem in the past, however.

**Comment by teslaballa** [comment]
I had the same problem upgrading (on a QNAP)) and I solved it only by deleting the docker, restarting the server and creating it again.
Fortunately I didn't lost any data :-)
