### ISSUE TITLE
App container crashes after few days

### ISSUE THREAD

**Issue by absynthe** [adriankumpf/teslamate#1209]
**Describe the bug**

I am running TeslaMate on AWS on an EC2 instance. After spinning up the stack it works correctly for a few days after which the app container fails. It automatically tries to recover but cannot connect to the postrgres database anymore for some reason. Application start working again if I shut it down and start the whole stack up again, but it crashes again in a few days. 

**Expected behavior**
The app container shouldn't crash. 

**How to reproduce it (as minimally and precisely as possible)**: 

I am using the docker-compose yaml from the fast start tutorial, and I have installed docker on a t3a.nano instance on AWS (default VPC). 

**Relevant entries from the logs**

Here is the docker log:

```
2021-01-09 03:00:31.944 [info] Connection was closed (a:1|t:15|d:10). Reconnecting …
2021-01-09 03:00:43.934 [warn] Too many disconnects …
2021-01-09 03:00:43.934 car_id=1 [info] Creating new connection … 
2021-01-09 03:00:43.934 car_id=1 [info] Disconnecting ...
2021-01-09 03:00:43.937 car_id=1 [info] Connecting ...
2021-01-09 03:00:54.335 [info] Connection was closed (a:1|t:1|d:0). Reconnecting …
2021-01-09 03:01:04.750 [info] Connection was closed (a:1|t:2|d:0). Reconnecting …
2021-01-09 03:01:15.167 [info] Connection was closed (a:1|t:3|d:0). Reconnecting …
2021-01-09 03:01:25.645 [info] Connection was closed (a:1|t:4|d:0). Reconnecting …
2021-01-09 03:01:42.043 [info] Connection was closed (a:1|t:5|d:0). Reconnecting …
2021-01-09 03:01:42.367 [info] control:hello – 0
2021-01-09 03:02:28.549 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
2021-01-09 03:02:38.974 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
2021-01-09 03:02:39.296 [info] control:hello – 0
2021-01-09 03:02:49.374 [info] Connection was closed (a:1|t:3|d:1). Reconnecting …
2021-01-09 03:02:59.776 [info] Connection was closed (a:1|t:4|d:1). Reconnecting …
2021-01-09 03:05:44.904 car_id=1 [info] Received stream data: :inactive
2021-01-09 03:05:44.983 [info] Connection was closed (a:1|t:5|d:6). Reconnecting …
2021-01-09 03:06:15.304 [info] Stream.Timeout / 5
2021-01-09 03:06:15.381 [info] Connection was closed (a:1|t:6|d:6). Reconnecting …
2021-01-09 03:06:53.595 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
2021-01-09 03:07:03.987 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
2021-01-09 03:07:14.404 [info] Connection was closed (a:1|t:3|d:1). Reconnecting …
2021-01-09 03:07:24.798 [info] Connection was closed (a:1|t:4|d:1). Reconnecting …
erl_child_setup closed

**Crash dump is being written to: erl_crash.dump...waiting for postgres at database:5432 (2sec)
waiting for postgres at database:5432 (4sec)
waiting for postgres at database:5432 (8sec)
waiting for postgres at database:5432 (16sec)
waiting for postgres at database:5432 (32sec)
waiting for postgres at database:5432 (64sec)
waiting for postgres at database:5432 (128sec)
waiting for postgres at database:5432 (256sec)
waiting for postgres at database:5432 (512sec)
waiting for postgres at database:5432 (1024sec)
waiting for postgres at database:5432 (2048sec)
waiting for postgres at database:5432 (4096sec)
waiting for postgres at database:5432 (8192sec)
waiting for postgres at database:5432 (16384sec)
waiting for postgres at database:5432 (32768sec)
waiting for postgres at database:5432 (65536sec)
waiting for postgres at database:5432 (131072sec)
waiting for postgres at database:5432 (262144sec)**
```

If I ssh into the container and try to inspect erl_crash.dump it shows up as empty. 

**Environment**

- TeslaMate version: 1.21.0
- Type of installation: Docker
- OS TeslaMate is installed on: Amazon Linux
- User OS & Browser: N/A
- Others: Hosted on AWS EC2 instance

**Comment by adriankumpf** [comment]
Is this still an issue with v1.21.2?

**Comment by absynthe** [comment]
Yes it is. It failed even faster (6h after restart) but the error logs seem to be a bit more verbose now:
```
Attaching to ec2-user_teslamate_1
teslamate_1  | 2021-02-06 21:24:41.469 [info] == Running 20210130174838 TeslaMate.Repo.Migrations.UseVariableLengthTypeForTokens.change/0 forward
teslamate_1  | 2021-02-06 21:24:41.473 [info] alter table tokens
teslamate_1  | 2021-02-06 21:24:41.488 [info] == Migrated 20210130174838 in 0.0s
teslamate_1  | 2021-02-06 21:24:43.677 [info] Version: 1.21.3
teslamate_1  | 2021-02-06 21:24:43.955 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (188.125 ms)
teslamate_1  | 2021-02-06 21:24:43.956 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/4b09f3fb-c0eb-492d-958e-a3e5c6a1ec74-1612646683902"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "4b09f3fb-c0eb-492d-958e-a3e5c6a1ec74"},
teslamate_1  |       {"x-correlation-id", "4b09f3fb-c0eb-492d-958e-a3e5c6a1ec74"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "1.685ms"},
teslamate_1  |       {"date", "Sat, 06 Feb 2021 21:24:43 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-06 21:24:43.956 [info] Scheduling token refresh in 1?h
teslamate_1  | 2021-02-06 21:24:43.962 [info] Running TeslaMateWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
teslamate_1  | 2021-02-06 21:24:43.965 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2021-02-06 21:24:44.901 [info] Starting logger for 'TeslAna'
teslamate_1  | 2021-02-06 21:24:44.926 [info] MQTT connection has been established
teslamate_1  | 2021-02-06 21:24:45.619 car_id=1 [info] Start / :online
teslamate_1  | 2021-02-06 21:24:45.626 car_id=1 [info] Logged missing software udpate: 2020.48.35.5 842a95863251
teslamate_1  | 2021-02-06 21:24:45.682 car_id=1 [info] Connecting ...
teslamate_1  | 2021-02-06 21:24:46.067 car_id=1 [info] Charging / SOC: 74% / Home
teslamate_1  | 2021-02-06 21:24:46.067 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-02-06 21:24:46.711 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Sun, 24 Jan 2021 19:35:23 GMT.
teslamate_1  | 2021-02-06 21:24:48.175 [info] Tzdata has updated the release from 2020e to 2021a
teslamate_1  | 2021-02-06 21:24:52.485 [info] GET /
teslamate_1  | 2021-02-06 21:24:52.504 [info] Sent 200 in 18ms
teslamate_1  | 2021-02-06 22:25:12.957 [info] Refreshing access token ...
teslamate_1  | 2021-02-06 22:25:13.122 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (159.036 ms)
teslamate_1  | 2021-02-06 22:25:13.122 [error] GenServer TeslaMate.Api terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, %TeslaApi.Error{env: %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}, __module__: TeslaApi.Auth, body: %{"error" => "server_error", "error_description" => "Internal server error", "error_uri" => "https://auth.tesla.com/error/reference/db1f1dd3-1003-4f2a-9cf0-8b0add5af50c-1612650313064"}, headers: [{"server", "nginx"}, {"content-type", "application/json"}, {"x-dns-prefetch-control", "off"}, {"x-frame-options", "DENY"}, {"strict-transport-security", "max-age=15552000; includeSubDomains"}, {"x-download-options", "noopen"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-request-id", "db1f1dd3-1003-4f2a-9cf0-8b0add5af50c"}, {"x-correlation-id", "db1f1dd3-1003-4f2a-9cf0-8b0add5af50c"}, {"access-control-allow-origin", "*"}, {"x-response-time", "2.249ms"}, {"date", "Sat, 06 Feb 2021 22:25:13 GMT"}, {"connection", "close"}], method: :post, opts: [], query: [], status: 400, url: "https://auth.tesla.com/oauth2/v3/token"}, message: nil, reason: :token_refresh}}
teslamate_1  |     (teslamate 1.21.3) lib/teslamate/api.ex:151: TeslaMate.Api.handle_info/2
teslamate_1  |     (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :refresh_auth
teslamate_1  | 2021-02-06 22:25:13.213 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (88.653 ms)
teslamate_1  | 2021-02-06 22:25:13.214 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/d043573e-8c12-47ff-9729-67f488255044-1612650313175"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"content-length", "172"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "d043573e-8c12-47ff-9729-67f488255044"},
teslamate_1  |       {"x-correlation-id", "d043573e-8c12-47ff-9729-67f488255044"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "1.608ms"},
teslamate_1  |       {"date", "Sat, 06 Feb 2021 22:25:13 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-06 22:25:13.214 [info] Scheduling token refresh in 1?h
teslamate_1  | 2021-02-06 22:30:42.638 car_id=1 [info] Phase correction: 2 -> 3
teslamate_1  | 2021-02-06 22:30:42.646 car_id=1 [info] Derived efficiency factor: 140.0 Wh/km (2x confirmed)
teslamate_1  | 2021-02-06 22:30:42.647 car_id=1 [info] Charging / Complete / 11.73 kWh ? 66 min
teslamate_1  | 2021-02-06 22:30:42.648 car_id=1 [info] Start / :online
teslamate_1  | 2021-02-06 22:30:42.683 car_id=1 [info] Connecting ...
teslamate_1  | 2021-02-06 22:35:54.162 [info] GET /api/1/vehicles/181100447284/vehicle_data -> 408 (9139.981 ms)
teslamate_1  | 2021-02-06 22:35:54.269 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-02-06 23:02:34.266 [info] GET /api/1/vehicles/181100447284/vehicle_data -> 408 (9191.706 ms)
teslamate_1  | 2021-02-06 23:02:34.588 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-02-06 23:02:53.747 [info] GET /api/1/vehicles/181100447284/vehicle_data -> 408 (9158.530 ms)
teslamate_1  | 2021-02-06 23:02:53.893 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-02-06 23:08:29.450 [info] GET /api/1/vehicles/181100447284/vehicle_data -> 408 (9145.092 ms)
teslamate_1  | 2021-02-06 23:08:29.566 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-02-06 23:12:26.227 car_id=1 [info] Driving / Start
teslamate_1  | 2021-02-06 23:14:49.070 car_id=1 [info] Driving / Ended / 0 km ? 2 min
teslamate_1  | 2021-02-06 23:14:49.071 car_id=1 [info] Start / :online
teslamate_1  | 2021-02-06 23:15:04.580 car_id=1 [info] Driving / Start
teslamate_1  | 2021-02-06 23:15:38.823 car_id=1 [info] Driving / Ended / 0 km ? 0 min
teslamate_1  | 2021-02-06 23:15:38.823 car_id=1 [info] Start / :online
teslamate_1  | 2021-02-06 23:16:52.243 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-02-06 23:16:52.243 car_id=1 [info] Creating new connection ? 
teslamate_1  | 2021-02-06 23:16:52.243 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-02-06 23:16:52.247 car_id=1 [info] Connecting ...
teslamate_1  | 2021-02-06 23:22:05.453 car_id=1 [info] Suspending logging
teslamate_1  | 2021-02-06 23:23:27.901 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-02-06 23:23:27.901 car_id=1 [info] Creating new connection ? 
teslamate_1  | 2021-02-06 23:23:27.901 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-02-06 23:23:27.904 car_id=1 [info] Connecting ...
teslamate_1  | 2021-02-06 23:25:42.215 [info] Refreshing access token ...
teslamate_1  | 2021-02-06 23:25:42.438 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (223.047 ms)
teslamate_1  | 2021-02-06 23:25:42.438 [error] GenServer TeslaMate.Api terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, %TeslaApi.Error{env: %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}, __module__: TeslaApi.Auth, body: %{"error" => "server_error", "error_description" => "Internal server error", "error_uri" => "https://auth.tesla.com/error/reference/546e2d39-4a2a-4c9d-b3f3-52c71c4740ce-1612653942399"}, headers: [{"content-type", "application/json"}, {"content-length", "172"}, {"x-dns-prefetch-control", "off"}, {"x-frame-options", "DENY"}, {"strict-transport-security", "max-age=15552000; includeSubDomains"}, {"x-download-options", "noopen"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-request-id", "546e2d39-4a2a-4c9d-b3f3-52c71c4740ce"}, {"x-correlation-id", "546e2d39-4a2a-4c9d-b3f3-52c71c4740ce"}, {"access-control-allow-origin", "*"}, {"x-response-time", "1.599ms"}, {"date", "Sat, 06 Feb 2021 23:25:42 GMT"}, {"connection", "close"}], method: :post, opts: [], query: [], status: 400, url: "https://auth.tesla.com/oauth2/v3/token"}, message: nil, reason: :token_refresh}}
teslamate_1  |     (teslamate 1.21.3) lib/teslamate/api.ex:151: TeslaMate.Api.handle_info/2
teslamate_1  |     (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :refresh_auth
teslamate_1  | 2021-02-06 23:25:42.549 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (108.341 ms)
teslamate_1  | 2021-02-06 23:25:42.550 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/8d69ed1a-2af1-4533-a55d-874a3d2c6a56-1612653942510"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "8d69ed1a-2af1-4533-a55d-874a3d2c6a56"},
teslamate_1  |       {"x-correlation-id", "8d69ed1a-2af1-4533-a55d-874a3d2c6a56"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.042ms"},
teslamate_1  |       {"date", "Sat, 06 Feb 2021 23:25:42 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-06 23:25:42.550 [info] Scheduling token refresh in 1?h
teslamate_1  | 2021-02-06 23:30:06.724 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-02-06 23:30:06.725 car_id=1 [info] Creating new connection ? 
teslamate_1  | 2021-02-06 23:30:06.725 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-02-06 23:30:06.728 car_id=1 [info] Connecting ...
teslamate_1  | 2021-02-06 23:52:05.841 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-02-06 23:52:05.846 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-02-07 00:26:11.551 [info] Refreshing access token ...
teslamate_1  | 2021-02-07 00:26:11.818 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (266.601 ms)
teslamate_1  | 2021-02-07 00:26:11.818 [error] GenServer TeslaMate.Api terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, %TeslaApi.Error{env: %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}, __module__: TeslaApi.Auth, body: %{"error" => "server_error", "error_description" => "Internal server error", "error_uri" => "https://auth.tesla.com/error/reference/bf247c11-efbf-4b5a-a8db-b166beb85238-1612657571778"}, headers: [{"content-type", "application/json"}, {"content-length", "172"}, {"x-dns-prefetch-control", "off"}, {"x-frame-options", "DENY"}, {"strict-transport-security", "max-age=15552000; includeSubDomains"}, {"x-download-options", "noopen"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-request-id", "bf247c11-efbf-4b5a-a8db-b166beb85238"}, {"x-correlation-id", "bf247c11-efbf-4b5a-a8db-b166beb85238"}, {"access-control-allow-origin", "*"}, {"x-response-time", "0.982ms"}, {"date", "Sun, 07 Feb 2021 00:26:11 GMT"}, {"connection", "close"}], method: :post, opts: [], query: [], status: 400, url: "https://auth.tesla.com/oauth2/v3/token"}, message: nil, reason: :token_refresh}}
teslamate_1  |     (teslamate 1.21.3) lib/teslamate/api.ex:151: TeslaMate.Api.handle_info/2
teslamate_1  |     (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :refresh_auth
teslamate_1  | 2021-02-07 00:26:11.918 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (97.579 ms)
teslamate_1  | 2021-02-07 00:26:11.919 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/fe3abd49-ae08-4a48-82c3-ecefbeb75e1a-1612657571879"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"content-length", "172"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "fe3abd49-ae08-4a48-82c3-ecefbeb75e1a"},
teslamate_1  |       {"x-correlation-id", "fe3abd49-ae08-4a48-82c3-ecefbeb75e1a"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "4.664ms"},
teslamate_1  |       {"date", "Sun, 07 Feb 2021 00:26:11 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-07 00:26:11.919 [info] Scheduling token refresh in 1?h
teslamate_1  | 2021-02-07 01:26:40.920 [info] Refreshing access token ...
teslamate_1  | 2021-02-07 01:26:41.044 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (123.803 ms)
teslamate_1  | 2021-02-07 01:26:41.044 [error] GenServer TeslaMate.Api terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, %TeslaApi.Error{env: %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}, __module__: TeslaApi.Auth, body: %{"error" => "server_error", "error_description" => "Internal server error", "error_uri" => "https://auth.tesla.com/error/reference/0c7a1b6e-3679-4327-aecd-92b37989e1fd-1612661201008"}, headers: [{"server", "nginx"}, {"content-type", "application/json"}, {"x-dns-prefetch-control", "off"}, {"x-frame-options", "DENY"}, {"strict-transport-security", "max-age=15552000; includeSubDomains"}, {"x-download-options", "noopen"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-request-id", "0c7a1b6e-3679-4327-aecd-92b37989e1fd"}, {"x-correlation-id", "0c7a1b6e-3679-4327-aecd-92b37989e1fd"}, {"access-control-allow-origin", "*"}, {"x-response-time", "2.438ms"}, {"date", "Sun, 07 Feb 2021 01:26:41 GMT"}, {"connection", "close"}], method: :post, opts: [], query: [], status: 400, url: "https://auth.tesla.com/oauth2/v3/token"}, message: nil, reason: :token_refresh}}
teslamate_1  |     (teslamate 1.21.3) lib/teslamate/api.ex:151: TeslaMate.Api.handle_info/2
teslamate_1  |     (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :refresh_auth
teslamate_1  | 2021-02-07 01:26:41.140 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (93.775 ms)
teslamate_1  | 2021-02-07 01:26:41.141 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/0cd5409e-a4b6-4eb5-8ea2-a2700ff33965-1612661201104"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"content-length", "172"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "0cd5409e-a4b6-4eb5-8ea2-a2700ff33965"},
teslamate_1  |       {"x-correlation-id", "0cd5409e-a4b6-4eb5-8ea2-a2700ff33965"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "1.361ms"},
teslamate_1  |       {"date", "Sun, 07 Feb 2021 01:26:41 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-07 01:26:41.141 [info] Scheduling token refresh in 1?h
teslamate_1  | 2021-02-07 02:27:10.142 [info] Refreshing access token ...
teslamate_1  | 2021-02-07 02:27:10.254 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (111.794 ms)
teslamate_1  | 2021-02-07 02:27:10.254 [error] GenServer TeslaMate.Api terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, %TeslaApi.Error{env: %Tesla.Env{__client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}, __module__: TeslaApi.Auth, body: %{"error" => "server_error", "error_description" => "Internal server error", "error_uri" => "https://auth.tesla.com/error/reference/cf19f636-ea1b-4087-9712-f789c9ada55a-1612664830213"}, headers: [{"server", "nginx"}, {"content-type", "application/json"}, {"x-dns-prefetch-control", "off"}, {"x-frame-options", "DENY"}, {"strict-transport-security", "max-age=15552000; includeSubDomains"}, {"x-download-options", "noopen"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-request-id", "cf19f636-ea1b-4087-9712-f789c9ada55a"}, {"x-correlation-id", "cf19f636-ea1b-4087-9712-f789c9ada55a"}, {"access-control-allow-origin", "*"}, {"x-response-time", "4.372ms"}, {"date", "Sun, 07 Feb 2021 02:27:10 GMT"}, {"connection", "close"}], method: :post, opts: [], query: [], status: 400, url: "https://auth.tesla.com/oauth2/v3/token"}, message: nil, reason: :token_refresh}}
teslamate_1  |     (teslamate 1.21.3) lib/teslamate/api.ex:151: TeslaMate.Api.handle_info/2
teslamate_1  |     (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :refresh_auth
teslamate_1  | 2021-02-07 02:27:10.355 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (97.954 ms)
teslamate_1  | 2021-02-07 02:27:10.356 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/9e6c613a-bfaa-444d-8edb-9faa55307c08-1612664830315"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "9e6c613a-bfaa-444d-8edb-9faa55307c08"},
teslamate_1  |       {"x-correlation-id", "9e6c613a-bfaa-444d-8edb-9faa55307c08"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.783ms"},
teslamate_1  |       {"date", "Sun, 07 Feb 2021 02:27:10 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-02-07 02:27:10.356 [info] Scheduling token refresh in 1?h
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
```

**Comment by adriankumpf** [comment]
You can make the error messages related to the token refresh go away logging in again once according to the [changelog](https://github.com/adriankumpf/teslamate/releases/tag/v1.21.2). 

I have no idea why it cannot connect to the Postrgres database anymore. Could this be an issue with Docker? Are you on the latest version?

**Comment by adriankumpf** [comment]
Closed due to inactivity. As soon as there is new information, I will open it again.
