### ISSUE TITLE
Teslamate docker shutdown

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#135]
I'm getting this when trying to start up the teslamate container:

21:05:55.132 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
21:05:55.446 [info] Access TeslaMateWeb.Endpoint at http://10.10.10.10
21:05:56.158 [info] Found '422165'
21:05:56.529 [info] Adding elevation to 1000 positions ...
21:05:56.570 car_id=1 [info] Start / :offline
21:05:56.656 [info] Querying location for elevation takes longer than 50ms ...
21:05:57.069 [info] Initializing handler
21:05:57.070 [info] Connection has been established
21:05:58.377 [error] Task #PID<0.3524.0> started from TeslaMate.Mapping terminating
** (CaseClauseError) no case clause matching: 25921570
    (srtm) lib/data_cell.ex:13: SRTM.DataCell.from_file!/1
    (srtm) lib/client.ex:103: anonymous fn/4 in SRTM.Client.load_cell/2
    (srtm) lib/client.ex:90: SRTM.Client.get_data_cell/3
    (srtm) lib/client.ex:81: SRTM.Client.get_elevation/3
    (teslamate) lib/teslamate/mapping.ex:160: TeslaMate.Mapping.do_get_elevation/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.93367123/0 in TeslaMate.Mapping.handle_event/4>
    Args: []
21:05:58.812 [info] Adding elevation to 1000 positions ...
21:05:58.863 [info] Querying location for elevation takes longer than 50ms ...
21:05:59.127 [error] Task #PID<0.3535.0> started from TeslaMate.Mapping terminating
** (CaseClauseError) no case clause matching: 25921570
    (srtm) lib/data_cell.ex:13: SRTM.DataCell.from_file!/1
    (srtm) lib/client.ex:103: anonymous fn/4 in SRTM.Client.load_cell/2
    (srtm) lib/client.ex:90: SRTM.Client.get_data_cell/3
    (srtm) lib/client.ex:81: SRTM.Client.get_elevation/3
    (teslamate) lib/teslamate/mapping.ex:160: TeslaMate.Mapping.do_get_elevation/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.93367123/0 in TeslaMate.Mapping.handle_event/4>
    Args: []
21:05:59.326 [info] Adding elevation to 1000 positions ...
21:05:59.378 [info] Querying location for elevation takes longer than 50ms ...
21:05:59.680 [error] Task #PID<0.3537.0> started from TeslaMate.Mapping terminating
** (CaseClauseError) no case clause matching: 25921570
    (srtm) lib/data_cell.ex:13: SRTM.DataCell.from_file!/1
    (srtm) lib/client.ex:103: anonymous fn/4 in SRTM.Client.load_cell/2
    (srtm) lib/client.ex:90: SRTM.Client.get_data_cell/3
    (srtm) lib/client.ex:81: SRTM.Client.get_elevation/3
    (teslamate) lib/teslamate/mapping.ex:160: TeslaMate.Mapping.do_get_elevation/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.93367123/0 in TeslaMate.Mapping.handle_event/4>
    Args: []
21:05:59.844 [info] Adding elevation to 1000 positions ...
21:05:59.896 [info] Querying location for elevation takes longer than 50ms ...
21:05:59.946 [error] Task #PID<0.3539.0> started from TeslaMate.Mapping terminating
** (CaseClauseError) no case clause matching: 25921570
    (srtm) lib/data_cell.ex:13: SRTM.DataCell.from_file!/1
    (srtm) lib/client.ex:103: anonymous fn/4 in SRTM.Client.load_cell/2
    (srtm) lib/client.ex:90: SRTM.Client.get_data_cell/3
    (srtm) lib/client.ex:81: SRTM.Client.get_elevation/3
    (teslamate) lib/teslamate/mapping.ex:160: TeslaMate.Mapping.do_get_elevation/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.93367123/0 in TeslaMate.Mapping.handle_event/4>
    Args: []
21:06:00.907 [info] Application teslamate exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})

Crash dump is being written to: erl_crash.dump...done

I am coming from a synology setup and this is after downgrading my broken version of Docker to a working one. 

EDIT:

My posgres log:

2019-09-03 03:55:54.074 UTC [89] LOG:  incomplete startup packet
2019-09-03 03:58:25.165 UTC [1] LOG:  received smart shutdown request
2019-09-03 03:58:26.081 UTC [1] LOG:  background worker "logical replication launcher" (PID 30) exited with exit code 1
2019-09-03 03:58:26.723 UTC [25] LOG:  shutting down
2019-09-03 03:58:27.682 UTC [1] LOG:  database system is shut down
2019-09-03 03:59:19.795 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-09-03 03:59:19.795 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-09-03 03:59:20.046 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-09-03 03:59:20.737 UTC [24] LOG:  database system was shut down at 2019-09-03 03:58:27 UTC
2019-09-03 03:59:20.981 UTC [25] LOG:  incomplete startup packet
2019-09-03 03:59:21.856 UTC [1] LOG:  database system is ready to accept connections
2019-09-03 04:01:14.140 UTC [40] LOG:  incomplete startup packet
2019-09-03 04:03:32.022 UTC [51] LOG:  incomplete startup packet
2019-09-03 04:06:34.841 UTC [62] LOG:  incomplete startup packet
2019-09-03 04:09:14.686 UTC [1] LOG:  received smart shutdown request
2019-09-03 04:09:16.202 UTC [1] LOG:  background worker "logical replication launcher" (PID 31) exited with exit code 1
2019-09-03 04:09:16.268 UTC [26] LOG:  shutting down
2019-09-03 04:09:18.064 UTC [1] LOG:  database system is shut down
2019-09-03 04:10:16.616 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-09-03 04:10:16.616 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-09-03 04:10:16.627 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-09-03 04:10:16.761 UTC [23] LOG:  database system was shut down at 2019-09-03 04:09:17 UTC
2019-09-03 04:10:16.912 UTC [1] LOG:  database system is ready to accept connections
2019-09-03 04:10:17.620 UTC [30] LOG:  incomplete startup packet

**Comment by adriankumpf** [comment]
Does a restart of the Docker container fix the problem? It seems like  the HGT file containing elevation data was not completely downloaded.

**Comment by natrlhy** [comment]
I've restarted all the containers multiple times only to have the teslamate container always get shutdown. I also had to fix my EID as mentioned in other threads

**Comment by adriankumpf** [comment]
Okay, if you continue to see the error `** (CaseClauseError) no case clause matching: 25921570` you can either downgrade to version 1.6.2 by explicitly specifying that version in your docker-compose.yml or wait for a fix.

**Comment by natrlhy** [comment]
Downgraded:

DB log:

2019-09-03 14:23:26.358 UTC [1] LOG:  received smart shutdown request
2019-09-03 14:23:26.765 UTC [1] LOG:  background worker "logical replication launcher" (PID 29) exited with exit code 1
2019-09-03 14:23:26.877 UTC [24] LOG:  shutting down
2019-09-03 14:23:27.022 UTC [1] LOG:  database system is shut down
2019-09-03 14:23:40.661 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-09-03 14:23:40.661 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-09-03 14:23:40.765 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-09-03 14:23:40.892 UTC [23] LOG:  database system was shut down at 2019-09-03 14:23:26 UTC
2019-09-03 14:23:41.074 UTC [1] LOG:  database system is ready to accept connections
2019-09-03 14:23:42.816 UTC [30] LOG:  incomplete startup packet
2019-09-03 14:24:22.358 UTC [37] ERROR:  column c0.version does not exist at character 67
2019-09-03 14:24:22.358 UTC [37] STATEMENT:  SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1)
2019-09-03 14:24:27.493 UTC [38] LOG:  incomplete startup packet
2019-09-03 14:25:01.533 UTC [45] ERROR:  column c0.version does not exist at character 67
2019-09-03 14:25:01.533 UTC [45] STATEMENT:  SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1)
2019-09-03 14:25:06.261 UTC [47] LOG:  incomplete startup packet
2019-09-03 14:25:40.317 UTC [51] ERROR:  column c0.version does not exist at character 67
2019-09-03 14:25:40.317 UTC [51] STATEMENT:  SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1)

teslamate logs:

07:25:50.499 [info] Already up
07:26:19.621 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
07:26:19.625 [info] Access TeslaMateWeb.Endpoint at http://10.10.10.10
07:26:19.678 [info] Found Model 3: 'SHUYE 3G'
07:26:19.709 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Vehicles
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.version does not exist

    query: SELECT c0."id", c0."name", c0."efficiency", c0."eid", c0."model", c0."version", c0."vid", c0."vin", c0."inserted_at", c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1)
            (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
            (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
            (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3
            (teslamate) lib/teslamate/vehicles.ex:74: TeslaMate.Vehicles.create_or_update!/1
            (teslamate) lib/teslamate/vehicles.ex:26: anonymous fn/2 in TeslaMate.Vehicles.init/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 62,message => nil,postgres => #{code => undefined_column,file => <<\"parse_relation.c\">>,line => <<\"3294\">>,message => <<\"column c0.version does not exist\">>,pg_code => <<\"42703\">>,position => <<\"67\">>,routine => <<\"errorMissingColumn\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"SELECT c0.\\"id\\", c0.\\"name\\", c0.\\"efficiency\\", c0.\\"eid\\", c0.\\"model\\", c0.\\"version\\", c0.\\"vid\\", c0.\\"vin\\", c0.\\"inserted_at\\", c0.\\"updated_at\\" FROM \\"cars\\" AS c0 WHERE (c0.\\"eid\\" = $1)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,621}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,554}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,18}]},{'Elixir.Ecto.Repo.Queryable',one,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,67}]},{'Elixir.TeslaMate.Vehicles','create_or_update!',1,[{file,\"lib/teslamate/vehicles.ex\"},{line,74}]},{'Elixir.TeslaMate.Vehicles','-init/1-fun-0-',2,[{file,\"lib/teslamate/vehicles.ex\"},{line,26}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1336}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'__exception__' => true,'__struct__' => 'Elixir.Po

Crash dump is being written to: erl_crash.dump...done

**Comment by adriankumpf** [comment]
Run this:

```bash
docker-compose run teslamate bin/teslamate eval "TeslaMate.Release.rollback(TeslaMate.Repo, 20190828150058)"
```

**Comment by natrlhy** [comment]
I decided to try to go to the latest again and.... drumroll:

07:35:25.330 [info] Sent 200 in 197ms
07:35:26.147 [info] Adding elevation to 1000 positions ...
07:35:29.729 [info] Adding elevation to 1000 positions ...
07:35:32.778 [info] Adding elevation to 1000 positions ...
07:35:35.715 [info] Adding elevation to 1000 positions ...
07:35:38.916 [info] Adding elevation to 1000 positions ...
07:35:41.819 [info] Adding elevation to 1000 positions ...
07:35:44.520 [info] Adding elevation to 1000 positions ...
07:35:47.688 [info] Adding elevation to 1000 positions ...
07:35:50.758 [info] Adding elevation to 1000 positions ...
07:35:54.029 [info] Adding elevation to 1000 positions ...
07:35:57.035 [info] Adding elevation to 1000 positions ...
07:36:00.025 [info] Adding elevation to 1000 positions ...
07:36:01.807 [info] GET /
07:36:01.819 [info] Sent 200 in 12ms
07:36:03.210 [info] Adding elevation to 1000 positions ...
07:36:03.861 [info] GET /settings
07:36:03.905 [info] Sent 200 in 43ms
07:36:06.252 [info] Adding elevation to 1000 positions ...
07:36:06.548 [info] GET /geo-fences
07:36:06.602 [info] Sent 200 in 53ms
07:36:08.436 [info] GET /geo-fences/11/edit
07:36:08.449 [info] Sent 200 in 13ms
07:36:09.345 [info] Adding elevation to 1000 positions ...
07:36:12.145 [info] Adding elevation to 1000 positions ...
07:36:12.345 [info] GET /geo-fences
07:36:12.355 [info] Sent 200 in 10ms
07:36:14.890 [info] Adding elevation to 1000 positions ...
07:36:15.583 [info] GET /settings
07:36:15.595 [info] Sent 200 in 12ms
07:36:17.623 [info] Adding elevation to 1000 positions ...
07:36:18.431 [info] GET /
07:36:18.447 [info] Sent 200 in 15ms
07:36:20.334 [info] Adding elevation to 1000 positions ...
07:36:23.038 [info] Adding elevation to 1000 positions ...
07:36:26.560 [info] Adding elevation to 1000 positions ...
07:36:29.646 [info] Adding elevation to 1000 positions ...
07:36:32.427 [info] Adding elevation to 1000 positions ...
07:36:35.835 [info] Adding elevation to 1000 positions ...
07:36:39.069 [info] Adding elevation to 1000 positions ...
07:36:43.278 [info] Adding elevation to 1000 positions ...
07:36:46.306 [info] Adding elevation to 1000 positions ...
07:36:49.082 [info] Adding elevation to 1000 positions ...
07:36:51.830 [info] Adding elevation to 1000 positions ...
07:36:54.598 [info] Adding elevation to 1000 positions ...
07:36:57.387 [info] Adding elevation to 521 positions ...

Seems it figured things out! I'm able to hit my port :4000 again (running on 1.7.0)

**Comment by adriankumpf** [comment]
Nice!
