### ISSUE TITLE
Regenerated vehicle IDs | TeslaMate crashing

### ISSUE THREAD

**Issue by drklain** [adriankumpf/teslamate#142]
Teslamate appears to be constantly crashing (running v 1.7.0).  Crashes every minute.

Here's the log entry:

9/3/19 18:39 | stdout | 14:39:43.395   [info] Already up |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stderr | Crash dump is being written to:   erl_crash.dump...done |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stderr |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stderr | Kernel pid terminated   (application_controller)   ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{{badmatch,{error,#{'__struct__'   => 'Elixir.Ecto.Chan |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stdout | {\Kernel pid terminated\" | application_controller | \"{application_start_failure | teslamate | {{shutdown | {failed_to_start_child | 'Elixir.TeslaMate.Vehicles' | {{badmatch | {error | #{'__struct__' => 'Elixir.Ecto.Changeset' | action => insert | changes => #{eid => 5893706682181155 | name => <<\\"Aluminum Falcon\\">> | vid => 1246387540 | vin => <<\\"xxxx\\">>} | constraints => [#{constraint =>   <<\\"cars_vid_index\\">> | error_message => <<\\"has already been   taken\\">> | error_type => unique | field => vid | match => exact | type => unique} | #{constraint => <<\\"cars_eid_index\\">> | error_message => <<\\"has already been   taken\\">> | error_type => unique | field => eid | match => exact | type => unique}] | data => #{'__meta__' => #{'__struct__' =>   'Elixir.Ecto.Schema.Metadata' | context => nil | prefix => nil | schema => 'Elixir.TeslaMate.Log.Car' | source => <<\\"cars\\">> | state => built} | '__struct__' => 'Elixir.TeslaMate.Log.Car' | charging_processes => #{'__cardinality__' => many | '__field__' => charging_processes | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | drives => #{'__cardinality__' => many | '__field__' => drives | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | efficiency => nil | eid => 5893706682181155 | id => nil | inserted_at => nil | model => nil | name => nil | positions => #{'__cardinality__' => many | '__field__' => positions | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | trim_badging => nil | updated_at => nil | vid => 1246387540 | vin => nil} | empty_values => [<<>>] | errors => [{vid | {<<\\"has already been taken\\">> | [{constraint | unique} | {constraint_name | <<\\"cars_vid_index\\">>}]}}] | filters => #{} | params => #{<<\\"name\\">> =>   <<\\"Aluminum Falcon\\">> | <<\\"vin\\">> =>   <<\\"xxxxx\\">>} | prepare => [] | repo => 'Elixir.TeslaMate.Repo' | repo_opts => [] | required => [eid | vid] | types => #{charging_processes => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => charging_processes | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.ChargingProcess' | related => 'Elixir.TeslaMate.Log.ChargingProcess' | related_key => car_id | relationship => child | unique => true | where => []}} | drives => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => drives | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.Drive' | related => 'Elixir.TeslaMate.Log.Drive' | related_key => car_id | relationship => child | unique => true | where => []}} | efficiency => float | eid => integer | id => id | inserted_at => naive_datetime | model => string | name => string | positions => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => positions | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.Position' | related => 'Elixir.TeslaMate.Log.Position' | related_key => car_id | relationship => child | unique => true | where => []}} | trim_badging => string | updated_at => naive_datetime | vid => integer | vin => string} | 'valid?' => false | validations => []}}} | [{'Elixir.TeslaMate.Vehicles' | 'create_or_update!' | 1 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 71}]} | {'Elixir.TeslaMate.Vehicles' | '-init/1-fun-0-' | 2 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 26}]} | {'Elixir.Enum' | '-map/2-lists^map/1-0-' | 2 | [{file | \\"lib/enum.ex\\"} | {line | 1336}]} | {'Elixir.TeslaMate.Vehicles' | init | 1 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 26}]} | {supervisor | init | 1 | [{file | \\"supervisor.erl\\"} | {line | 295}]} | {gen_server | init_it | 2 | [{file | \\"gen_server.erl\\"} | {line | 374}]} | {gen_server | init_it | 6 | [{file | \\"gen_server.erl\\"} | {line | 342}]} | {proc_lib | init_p_do_apply | 3 | [{file | \\"proc_lib.erl\\"} | {line | 249}]}]}}} | {'Elixir.TeslaMate.Application' | start | [normal | []]}}}\"}
2019-09-03 18:39:34,stdout,              (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3               2019-09-03 18:39:34,stdout,              (stdlib) gen_server.erl:342: :gen_server.init_it/6               2019-09-03 18:39:34,stdout,              (stdlib) gen_server.erl:374: :gen_server.init_it/2               2019-09-03 18:39:34,stdout,              (stdlib) supervisor.erl:295: :supervisor.init/1               2019-09-03 18:39:34,stdout,              (teslamate) lib/teslamate/vehicles.ex:26: TeslaMate.Vehicles.init/1               2019-09-03 18:39:34,stdout,              (elixir) lib/enum.ex:1336: Enum.-map/2-lists^map/1-0-"/2 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stdout | (teslamate)   lib/teslamate/vehicles.ex:26: anonymous fn/2 in TeslaMate.Vehicles.init/1 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stdout | (teslamate)   lib/teslamate/vehicles.ex:71: TeslaMate.Vehicles.create_or_update!/1 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
9/3/19 18:39 | stdout | ** (MatchError) no match of   right hand side value: {:error, #Ecto.Changeset<action: :insert, changes:   %{eid: 5893706682181155, name: \Aluminum Falcon\" | vid: 1246387540 | vin:   \"xxxx\"} | errors: [vid: {\"has already   been taken\" | [constraint: :unique | constraint_name:   \"cars_vid_index\"]}] | data: #TeslaMate.Log.Car<> | valid?: false>} |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
2019-09-03 18:39:34,stdout,    **   (EXIT) an exception was raised:               2019-09-03 18:39:34,stdout,14:39:33.951 [info] Application teslamate   exited: TeslaMate.Application.start(:normal | []) returned an error: shutdown: failed to   start child: TeslaMate.Vehicles |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
2019-09-03 18:39:33,stdout,14:39:33.932 [info] Found 'Aluminum   Falcon'               2019-09-03 18:39:33,stdout,14:39:33.809 [info] Access TeslaMateWeb.Endpoint   at http://192.168.1.169               2019-09-03 18:39:33,stdout,14:39:33.808 [info] Running   TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)               2019-09-03 18:39:18,stdout,14:39:18.599 [info] Already up               2019-09-03 18:39:10,stderr,Crash dump is being written to:   erl_crash.dump...done                    2019-09-03 18:39:10,stderr,                    2019-09-03 18:39:10,stderr,Kernel pid terminated (application_controller)   ({application_start_failure | teslamate | {{shutdown | {failed_to_start_child | 'Elixir.TeslaMate.Vehicles' | {{badmatch | {error | #{'__struct__' =>   'Elixir.Ecto.Chan |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
2019-09-03 18:39:10,stdout,{\"Kernel pid terminated\" | application_controller | \"{application_start_failure | teslamate | {{shutdown | {failed_to_start_child | 'Elixir.TeslaMate.Vehicles' | {{badmatch | {error | #{'__struct__' => 'Elixir.Ecto.Changeset' | action => insert | changes => #{eid => 5893706682181155 | name => <<\\"Aluminum Falcon\\">> | vid => 1246387540 | vin => <<\\"xxxxxx\\">>} | constraints => [#{constraint =>   <<\\"cars_vid_index\\">> | error_message => <<\\"has already been   taken\\">> | error_type => unique | field => vid | match => exact | type => unique} | #{constraint => <<\\"cars_eid_index\\">> | error_message => <<\\"has already been   taken\\">> | error_type => unique | field => eid | match => exact | type => unique}] | data => #{'__meta__' => #{'__struct__' =>   'Elixir.Ecto.Schema.Metadata' | context => nil | prefix => nil | schema => 'Elixir.TeslaMate.Log.Car' | source => <<\\"cars\\">> | state => built} | '__struct__' => 'Elixir.TeslaMate.Log.Car' | charging_processes => #{'__cardinality__' => many | '__field__' => charging_processes | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | drives => #{'__cardinality__' => many | '__field__' => drives | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | efficiency => nil | eid => 5893706682181155 | id => nil | inserted_at => nil | model => nil | name => nil | positions => #{'__cardinality__' => many | '__field__' => positions | '__owner__' => 'Elixir.TeslaMate.Log.Car' | '__struct__' => 'Elixir.Ecto.Association.NotLoaded'} | trim_badging => nil | updated_at => nil | vid => 1246387540 | vin => nil} | empty_values => [<<>>] | errors => [{vid | {<<\\"has already been taken\\">> | [{constraint | unique} | {constraint_name | <<\\"cars_vid_index\\">>}]}}] | filters => #{} | params => #{<<\\"name\\">> =>   <<\\"Aluminum Falcon\\">> | <<\\"vin\\">> =>   <<\\"xxxxx\\">>} | prepare => [] | repo => 'Elixir.TeslaMate.Repo' | repo_opts => [] | required => [eid | vid] | types => #{charging_processes => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => charging_processes | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.ChargingProcess' | related => 'Elixir.TeslaMate.Log.ChargingProcess' | related_key => car_id | relationship => child | unique => true | where => []}} | drives => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => drives | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.Drive' | related => 'Elixir.TeslaMate.Log.Drive' | related_key => car_id | relationship => child | unique => true | where => []}} | efficiency => float | eid => integer | id => id | inserted_at => naive_datetime | model => string | name => string | positions => {assoc | #{'__struct__' => 'Elixir.Ecto.Association.Has' | cardinality => many | defaults => [] | field => positions | on_cast => nil | on_delete => nothing | on_replace => raise | owner => 'Elixir.TeslaMate.Log.Car' | owner_key => id | queryable => 'Elixir.TeslaMate.Log.Position' | related => 'Elixir.TeslaMate.Log.Position' | related_key => car_id | relationship => child | unique => true | where => []}} | trim_badging => string | updated_at => naive_datetime | vid => integer | vin => string} | 'valid?' => false | validations => []}}} | [{'Elixir.TeslaMate.Vehicles' | 'create_or_update!' | 1 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 71}]} | {'Elixir.TeslaMate.Vehicles' | '-init/1-fun-0-' | 2 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 26}]} | {'Elixir.Enum' | '-map/2-lists^map/1-0-' | 2 | [{file | \\"lib/enum.ex\\"} | {line | 1336}]} | {'Elixir.TeslaMate.Vehicles' | init | 1 | [{file | \\"lib/teslamate/vehicles.ex\\"} | {line | 26}]} | {supervisor | init | 1 | [{file | \\"supervisor.erl\\"} | {line | 295}]} | {gen_server | init_it | 2 | [{file | \\"gen_server.erl\\"} | {line | 374}]} | {gen_server | init_it | 6 | [{file | \\"gen_server.erl\\"} | {line | 342}]} | {proc_lib | init_p_do_apply | 3 | [{file | \\"proc_lib.erl\\"} | {line | 249}]}]}}} | {'Elixir.TeslaMate.Application' | start | [normal | []]}}}\"} |   |

**Comment by adriankumpf** [comment]
Please try again with the latest version (v1.8)

**Comment by drklain** [comment]
It fixed the problem.  Thanks again!
