### ISSUE TITLE
Error accessing settings page after deleting old car from database

### ISSUE THREAD

**Issue by ctraber** [adriankumpf/teslamate#1427]
I have now the same issue as described in #1199 .
Deleted car with id = 1 and only my new car with id = 2 is now in the database.
@lytesout2376 @KingKongKent have you found a solution for the problem?

```
2021-03-11 06:15:50.668 [error] #PID<0.2475.0> running TeslaMateWeb.Endpoint (connection #PID<0.2449.0>, stream id 5) terminated

Server: 192.168.1.63:4000 (http)

Request: GET /settings

** (exit) an exception was raised:

    ** (UndefinedFunctionError) function nil.id/0 is undefined

        nil.id()

        (teslamate 1.21.6) lib/teslamate_web/live/settings_live/index.ex:184: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1

        (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3

        (teslamate 1.21.6) lib/teslamate_web/live/settings_live/index.ex:16: TeslaMateWeb.SettingsLive.Index.mount/3

        (phoenix_live_view 0.15.4) lib/phoenix_live_view/utils.ex:320: anonymous fn/4 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4

        (telemetry 0.4.2) /opt/app/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3

        (phoenix_live_view 0.15.4) lib/phoenix_live_view/static.ex:306: Phoenix.LiveView.Static.call_mount_and_handle_params!/5

        (phoenix_live_view 0.15.4) lib/phoenix_live_view/static.ex:131: Phoenix.LiveView.Static.render/3
```

**Comment by KingKongKent** [comment]
@ctraber, no solution. Since my my car was new, I had no history to remain on the new car. 
My solution was to deploy a new Teslamate on another RasPi.

**Comment by ctraber** [comment]
Found a solution. In table car_settings was still an entry with the id of my old and deleted car.
After I deleted the record, settings work again.

**Comment by KingKongKent** [comment]
Thanks, that worked for me as well...
