### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by LostSoulfly** [adriankumpf/teslamate#164]
I'm running a fresh install of Alpine with only docker and docker-compose installed.

This is my first docker container.. and also first attempt with docker-compose. I've setup using the defaults. When I attempt to login, it looks like it gets my token successfully at the end but never proceeds and returns to a blank login screen. I've verified the login credentials are correct through Tesla's website as well. No issues logging in there.

I'm also unable to access port 3000 at all. I'm not sure if that's relevant.

What am I doing wrong? What am I missing? Thanks for your hard work, I'm excited to try this out!

```
mosquitto_1  | 1568441180: mosquitto version 1.6.5 starting
mosquitto_1  | 1568441180: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto_1  | 1568441180: Opening ipv4 listen socket on port 1883.
mosquitto_1  | 1568441180: Opening ipv6 listen socket on port 1883.
db_1         | 2019-09-14 06:06:20.828 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432db_1         | 2019-09-14 06:06:20.828 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2019-09-14 06:06:20.833 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2019-09-14 06:06:20.847 UTC [21] LOG:  database system was shut down at 2019-09-14 06:06:10 UTC
db_1         | 2019-09-14 06:06:20.853 UTC [1] LOG:  database system is ready to accept connectionsdb_1         | 2019-09-14 06:06:21.676 UTC [28] LOG:  incomplete startup packet
teslamate_1  | 02:06:24.161 [info] Already up
grafana_1    | Failed to send request: Get https://grafana.com/api/plugins/repo/pr0ps-trackmap-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
grafana_1    | Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/pr0ps-trackmap-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
grafana_1    |
grafana_1    | NAME:
grafana_1    |    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
grafana_1    |
grafana_1    | USAGE:
grafana_1    |    Grafana cli plugins install [arguments...]
dcompose_grafana_1 exited with code 1
teslamate_1  | 02:06:31.579 [info] Please sign in.
teslamate_1  | 02:06:31.588 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
teslamate_1  | 02:06:31.592 [info] Access TeslaMateWeb.Endpoint at http://tesla.trollparty.org
mosquitto_1  | 1568441191: New connection from 172.19.0.3 on port 1883.
mosquitto_1  | 1568441191: New client connected from 172.19.0.3 as TESLAMATE_302E3036363 (p2, c1, k60).
teslamate_1  | 02:06:31.606 [info] Initializing handler
teslamate_1  | 02:06:31.609 [info] Connection has been established
teslamate_1  | 02:06:54.623 [info] GET /sign_in
teslamate_1  | 02:06:54.626 [info] Sent 200 in 3ms
teslamate_1  | 02:07:00.864 [error] GenServer #PID<0.3592.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Api, {:sign_in, %TeslaMate.Auth.Credentials{__meta__: #Ecto.Schema.Metadata<:built, "">, email: "xx@xx.com", id: nil, password: "xxxxxxxxxx"}}, 5000)
teslamate_1  |     ** (EXIT) time out
teslamate_1  |     (elixir) lib/gen_server.ex:1009: GenServer.call/3
teslamate_1  |     (teslamate) lib/teslamate_web/live/signin_live/index.ex:40: TeslaMateWeb.SignInLive.Index.handle_event/3
teslamate_1  |     (phoenix_live_view) lib/phoenix_live_view/channel.ex:81: Phoenix.LiveView.Channel.handle_info/2
teslamate_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "1", payload: %{"event" => "save", "type" => "form", "value" => "_csrf_token=xx"}, ref: "4", topic: "lv:xxx-xxxxxxxx"}
```

**Comment by virtualm2000** [comment]
Check if the docker container has internet access. Both Grafana and Tesla API failed in connecting to internet.

**Comment by LostSoulfly** [comment]
I worked out my issue finally. I did everything correctly for the VM and docker containers. Turned out to be an odd DHCP problem where the VM didn't wasn't receiving the correct gateway and/or DNS from my pfSense box. I deleted and re-created the static entry and that fixed it. Thanks for the insight guys.
