### ISSUE TITLE
Existing API tokens: Unable to fill form

### ISSUE THREAD

**Issue by cybe** [adriankumpf/teslamate#1666]
**Describe the bug**

When filling in the form for authentication by existing API tokens, the authentication process seems to start immediately after entering one single character. That fails? and the form resets.

**Expected behavior**

The authentication process starts only after clicking the "Sign in" button.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to `https://teslamate.example.org/sign_in?use_api_tokens=true`
2. Click on "Access Token" field
3. Type character "a"
4. See error: Form gets submitted immediately 

**Relevant entries from the logs**

```
2021-06-02 19:24:30.751 [error] GenServer #PID<0.2670.0> terminating
** (FunctionClauseError) no function clause matching in TeslaMateWeb.SignInLive.Index.handle_event/3
    (teslamate 1.23.1) lib/teslamate_web/live/signin_live/index.ex:41: TeslaMateWeb.SignInLive.Index.handle_event("validate", %{"_csrf_token" => "BDpJNBB_IhIWNBQ8CGM5ISRSdQIDC0IJBP3cWODBfUUqo4nybfECgH3f", "_target" => ["credentials", "access"], "credentials" => %{"access" => "a", "refresh" => ""}}, #Phoenix.LiveView.Socket<assigns: %{api: TeslaMate.Api, callback: #Function<3.38282672/2 in TeslaMate.Api.handle_call/3>, captcha: nil, error: nil, flash: %{}, live_action: nil, page_title: "Sign in", state: {:tokens, #Ecto.Changeset<action: nil, changes: %{}, errors: [access: {"can't be blank", [validation: :required]}, refresh: {"can't be blank", [validation: :required]}], data: #TeslaMate.Auth.Tokens<>, valid?: false>}, task: nil}, changed: %{}, endpoint: TeslaMateWeb.Endpoint, id: "phx-FoTT0aon29mjswCD", parent_pid: nil, root_pid: #PID<0.2670.0>, router: TeslaMateWeb.Router, view: TeslaMateWeb.SignInLive.Index, ...>)
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:342: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:204: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"event" => "validate", "type" => "form", "uploads" => %{}, "value" => "_csrf_token=BDpJNBB_IhIWNBQ8CGM5ISRSdQIDC0IJBP3cWODBfUUqo4nybfECgH3f&credentials%5Baccess%5D=a&credentials%5Brefresh%5D=&_target=credentials%5Baccess%5D"}, ref: "5", topic: "lv:phx-FoTT0aon29mjswCD"}
2021-06-02 19:24:31.988 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (202.915 ms)
2021-06-02 19:24:31.993 [error] GenServer #PID<0.2671.0> terminating
** (FunctionClauseError) no function clause matching in TeslaMateWeb.SignInLive.Index.handle_event/3
    (teslamate 1.23.1) lib/teslamate_web/live/signin_live/index.ex:41: TeslaMateWeb.SignInLive.Index.handle_event("validate", %{"_csrf_token" => "BDpJNBB_IhIWNBQ8CGM5ISRSdQIDC0IJBP3cWODBfUUqo4nybfECgH3f", "_target" => ["_csrf_token"], "credentials" => %{"access" => "a", "refresh" => ""}}, #Phoenix.LiveView.Socket<assigns: %{api: TeslaMate.Api, callback: #Function<3.38282672/2 in TeslaMate.Api.handle_call/3>, captcha: nil, error: nil, flash: %{}, live_action: nil, page_title: "Sign in", state: {:tokens, #Ecto.Changeset<action: nil, changes: %{}, errors: [access: {"can't be blank", [validation: :required]}, refresh: {"can't be blank", [validation: :required]}], data: #TeslaMate.Auth.Tokens<>, valid?: false>}, task: nil}, changed: %{}, endpoint: TeslaMateWeb.Endpoint, id: "phx-FoTT0aon29mjswCD", parent_pid: nil, root_pid: #PID<0.2671.0>, router: TeslaMateWeb.Router, view: TeslaMateWeb.SignInLive.Index, ...>)
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:342: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:204: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "6", payload: %{"event" => "validate", "type" => "form", "uploads" => %{}, "value" => "_csrf_token=BDpJNBB_IhIWNBQ8CGM5ISRSdQIDC0IJBP3cWODBfUUqo4nybfECgH3f&credentials%5Baccess%5D=a&credentials%5Brefresh%5D=&_target=_csrf_token"}, ref: "7", topic: "lv:phx-FoTT0aon29mjswCD"}
2021-06-02 19:24:34.037 [info] GET /sign_in
2021-06-02 19:24:34.040 [info] Sent 200 in 3ms
2021-06-02 19:24:34.524 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (228.923 ms)
```

**Environment**

- TeslaMate version: 1.23.1
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: Windows 10, Firefox / Chrome
- Others: Never logged in on this installation, database should be clear. Installation was done on 1.23.0. and upgraded moments ago.

**Comment by adriankumpf** [comment]
Fixed in v1.23.3
