### ISSUE TITLE
Drive does not continue when offline for a few minutes

### ISSUE THREAD

**Issue by pkuehnel** [adriankumpf/teslamate#1848]
**Describe the bug**
When driving and the car does not have a network connection for a few minutes (or has very low signal with switching between online and offline all the time) a new drive is started without ending the previous one, so the old drive does not show up in Grafana because everything except the `start_date` in the database is `null`. Then you have to manually end the drive like described in the [TeslaMate documentation](https://docs.teslamate.org/docs/maintenance/manually_fixing_data#terminate-a-drive-or-charge)

**Expected behavior**
In my opinion there are three options to resove this issue:

1. Do not start a new drive if there is no point where the car is definetly not driving (is online and not driving or asleep). I see an issue here, when drivers park frequently in garages without internet connection, there would be an endless drive.
2. End the previous drive when a new drive is started
3. Let the user dynamically set a timeout x seconds. After that timeout the drive is automatically ended properly.

**How to reproduce it**:
Drive for a few minutes without internet connection and still drive when connection is regained. Mostly happens when crossing national borders, because the car needs some time to connect to the cell phone network of the next country. Probably error occurs only, when car is often switching between online and offline. I was driving along a border in Germany, while car was still in Austrian network with very low signal.

**Relevant entries from the logs**
```

2021-07-18 14:31:55.949 car_id=1 [warn] Discarded incomplete fetch result


2021-07-18 14:32:03.215 [error] Vehicle Error: Vehicle is offline


2021-07-18 14:32:06.288 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (337.458 ms)


2021-07-18 14:32:06.610 car_id=1 [warn] Vehicle went offline while driving


2021-07-18 14:32:12.213 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (601.450 ms)


2021-07-18 14:32:17.996 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (446.375 ms)


2021-07-18 14:32:23.795 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (495.721 ms)


2021-07-18 14:32:29.529 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (404.606 ms)


2021-07-18 14:32:33.215 car_id=1 [info] Received stream data: :inactive


2021-07-18 14:32:34.498 [error] Vehicle Error: Vehicle is offline


2021-07-18 14:32:35.186 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (425.332 ms)


2021-07-18 14:32:41.134 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (265.105 ms)


2021-07-18 14:32:46.852 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/173805042760/vehicle_data -> 408 (353.286 ms)


2021-07-18 14:32:52.730 car_id=1 [info] Vehicle is back online


2021-07-18 14:35:32.206 [error] ** (RuntimeError) Client Error: %{"error_type" => "client_error", "msg_type" => "data:error", "tag" => "1119824679", "value" => "owner_api error: `Post \"https://ownerapi-internal.vn.teslamotors.com:443/authenticate/vehicles/1119824679?operation=streaming_authenticate\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`"}


    (teslamate 1.23.6) lib/tesla_api/stream.ex:150: TeslaApi.Stream.handle_frame/2


    (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3


    (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4


    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3



2021-07-18 14:35:38.946 car_id=1 [info] Start / :online


2021-07-18 14:35:38.953 car_id=1 [info] Connecting ...


2021-07-18 14:35:38.953 car_id=1 [info] Driving / Start
```

**Environment**

- TeslaMate version: 1.23.6
- Type of installation: Docker
- OS TeslaMate is installed on: Debian 10
- User OS & Browser: not relevant
- Others: not relevant

**Comment by adriankumpf** [comment]
TeslaMate already handles the case where the car was offline for a moment. The issue here is that the Tesla Streaming API returned an unexpected error which caused the recording to be abruptly interrupted. 

```elixir
** (RuntimeError) Client Error: %{
  "error_type" => "client_error",
  "msg_type" => "data:error",
  "tag" => "1119824679",
  "value" =>
    "owner_api error: `Post \"https://ownerapi-internal.vn.teslamotors.com:443/authenticate/vehicles/1119824679?operation=streaming_authenticate\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`"
}
```

Has this happened to you more than once? If so, did you see the same error each time in the logs?

**Comment by adriankumpf** [comment]
The above error does now get handled properly on the latest master.

**Comment by pkuehnel** [comment]
> Has this happened to you more than once? If so, did you see the same error each time in the logs?

It has occured two times that I don't have an end date of the drive, but last time it occured (2021-06-15), so I don't have the logs anymore. On this day there are 25 drives within 15 minutes, maybe it was another issue there. I'll try to manually fix this by merging it into a single drive in the database and end the drive. Thank you for the quick fix, I close this for now because I can't tell you if I ever had this issue before.

Of topic: I am really amazed by this software, I have never seen so few bugs in a software. There are so many logging tools for Tesla out there but not a single one is in terms of bugs better than yours. Automated tests FTW!

**Comment by aaronjwood** [comment]
Just ran into this myself today due to a timeout from the Tesla API. My drive to work only got recorded at the last 7 minutes so I lost most of the data for it. Glad to hear this was fixed in master recently! Is there any ETA for when a new version will roll out with the fix?
