### ISSUE TITLE
503 error will send geofence=""

### ISSUE THREAD

**Issue by brianmay** [adriankumpf/teslamate#1885]
**Describe the bug**

Teslamate will randomly on rare occasions send geofence="" mqqtt messages and then immediately correct one minute later.

**Expected behavior**

Teslamate should not send geofence messages if it is not sure of the value.

**How to reproduce it (as minimally and precisely as possible)**:

1. Monitor geofence messages.
2. Wait.

**Relevant entries from the logs**

1st occurrence:

```
2021-08-05 20:51:58.830 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/46735652188006662/vehicle_data -> 503 (425.895 ms)
2021-08-05 20:51:58.831 [warn] TeslaApi.Error / "upstream connect error or disconnect/reset before headers. reset reason: connection failure"
2021-08-05 20:51:58.832 car_id=1 [error] Error / :unknown
2021-08-05 20:52:10.876 [error] ** (RuntimeError) Client Error: %{"error_type" => "client_error", "msg_type" => "data:error", "tag" => "1318482982", "value" => "owner_api error: `Got HTTP status: 503 Service Unavailable for . Response: upstream connect error or disconnect/reset before headers. reset reason: connection failure`"}
    (teslamate 1.23.7) lib/tesla_api/stream.ex:150: TeslaApi.Stream.handle_frame/2
    (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3
    (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

2021-08-05 20:52:21.130 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/46735652188006662 -> 408 (10250.011 ms)
2021-08-05 20:52:21.132 [warn] TeslaApi.Error / %{"error" => "https://mothership-api.vn.teslamotors.com:443/vehicles/1318482982 => operation_timedout with 10s timeout", "error_description" => "", "response" => nil}
2021-08-05 20:52:21.133 car_id=1 [error] Error / :unknown
2021-08-05 20:52:53.945 car_id=1 [info] Start / :online
2021-08-05 20:52:53.966 car_id=1 [info] Connecting ...
```

2nd occurrence:

```
2021-08-05 21:04:20.635 [error] ** (RuntimeError) Client Error: %{"error_type" => "client_error", "msg_type" => "data:error", "tag" => "1318482982", "value" => "owner_api error: `Got HTTP status: 503 Service Unavailable for . Response: upstream connect error or disconnect/reset before headers. reset reason: connection failure`"}
    (teslamate 1.23.7) lib/tesla_api/stream.ex:150: TeslaApi.Stream.handle_frame/2
    (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3
    (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

2021-08-05 21:04:37.407 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/46735652188006662 -> 408 (16765.618 ms)
2021-08-05 21:04:37.408 [warn] TeslaApi.Error / %{"error" => "https://mothership-api.vn.teslamotors.com:443/vehicles/1318482982 => operation_timedout with 10s timeout", "error_description" => "", "response" => nil}
2021-08-05 21:04:37.409 car_id=1 [error] Error / :unknown
2021-08-05 21:05:11.590 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/46735652188006662/vehicle_data -> 503 (425.181 ms)
2021-08-05 21:05:11.591 [warn] TeslaApi.Error / "upstream connect error or disconnect/reset before headers. reset reason: connection failure"
2021-08-05 21:05:11.591 car_id=1 [error] Error / :unknown
2021-08-05 21:05:58.802 car_id=1 [info] Start / :online
2021-08-05 21:05:58.826 car_id=1 [info] Connecting ...
```

If I am reading this correct, the first time we get a 503, then we retry and get a timeout error. Not sure exactly what point the geofence="" message gets sent. Then we try again and it works.

I suspect this is because the Tesla API is doing "weird stuff"(tm). But ideally TeslaMate should be able to cope.

**Environment**

- TeslaMate version: 1.23.7
- Type of installation: Docker

**Comment by LelandSindt** [comment]
interesting..... I have seen, and had to [work around](https://github.com/gaussmeter/retractor/blob/main/main.go#L162-L165) this behaviour as well. 

Indeed it would be nice if instead of sending an empty geofence TeslaMate would leave geofence unchanged.

**Comment by brianmay** [comment]
I suspect the actual issue is that that code uses `geofence=nil` to for (a) geofence is unknown we haven't received it yet, and (b) geofence is known but there is no geofence. But these two cases probably need to be stored as two distinct atoms.

I also have an untested theory that this may not happen with the latitude/longitude. But for latitude/longitude these really should be sent in one message. I mean how often do you really want just the latitude without the longitude or vice versa? Otherwise it is difficult to interpret the values when receiving them correctly, without trying for example to interpret {new latitude,old longitude} which is nonsense.

I think these issues are easily fixable. The challenge is understanding the code structure enough to create a a fix and not break anything. I wish there was an overall design document that described the various processes and the interactions.

**Comment by brianmay** [comment]
My theory is that what is happening is:

1. TeslaApi.Stream sees the 503.
2. TeslaApi.Stream commits suicide:
```
{:ok, %{"msg_type" => "data:error", "tag" => ^tag, "error_type" => "client_error"} = msg} ->
raise "Client Error: #{inspect(msg)}"
```
3. This results in the `TeslaMate.Vehicles.Vehicle` process dieing. Possibly because the processes are linked, not 100% sure here.
4. When the `TeslaMate.Vehicles.Vehicle`  process dies it is restarted. With the default value of geofence of null.
5. This value of geofence gets broadcast to mqtt.
6. Eventually we get the correct value of geofence, and this gets updated.

One unknown here is step 3. I don't think the process dieing was intended to kill the `TeslaMate.Vehicles.Vehicle` process. But not really sure I understand how this happens. Having processes linked is an easy mistake to make with Elixir. I am currently constrained though, because I don't know where this call ends up:

```
defp connect_stream(%Data{car: car} = data) do
    Logger.info("Connecting ...", car_id: car.id)

    me = self()

    call(data.deps.api, :stream, [
      data.car.vid,
      fn stream_data -> send(me, {:stream, stream_data}) end
    ])
  end
```

What is `data.deps.api` set to?

I am experimenting with the following patch:

```
diff --git a/lib/teslamate/vehicles/vehicle.ex b/lib/teslamate/vehicles/vehicle.ex
index d1cead3..65b3d01 100644
--- a/lib/teslamate/vehicles/vehicle.ex
+++ b/lib/teslamate/vehicles/vehicle.ex
@@ -20,7 +20,7 @@ defmodule TeslaMate.Vehicles.Vehicle do
               last_response: nil,
               last_state_change: nil,
               elevation: nil,
-              geofence: nil,
+              geofence: :unknown,
               deps: %{},
               task: nil,
               import?: false,
```

Theory is it should solve the problem. If it works for me for "a while" will submit a pull request.

Caveat: Suspect there are other values which have the same problem. But geofence is the only one I care about. And probably OK to alter because AFAIK this value doesn't get logged to the database. Suspicious values include:

```
teslamate/cars/1/scheduled_charging_start_time (null)
teslamate/cars/1/charge_energy_added (null)
teslamate/cars/1/charger_actual_current (null)
teslamate/cars/1/geofence (null)           
teslamate/cars/1/charger_voltage (null)
teslamate/cars/1/charger_power (null)    
teslamate/cars/1/time_to_full_charge (null)   
teslamate/cars/1/state unavailable
```

All of these values where published to mqtt and then corrected a short time later. Although only geofence has the problem that a "(null)" value has dual meaning.

**Comment by brianmay** [comment]
Seems like my fix was insufficient. Will investigate.

**Comment by brianmay** [comment]
Wondering if 6c19a7b8a712a2b6bc091c7db51ad763b5bd337f may have fixed this. Will test.
