### ISSUE TITLE
FunctionClauseError: no function clause matching in TeslaApi.Stream.handle_info/2

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#2001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The error shown in the log was printed while the car was parked (I've replaced private data by `<deleted>`). Also, this was during the time when #1996 was occurring, which I think explains the Driving messages before the error.

### Relevant log output

```shell
2021-09-25 11:37:35.743 car_id=1 [info] Driving / Start
2021-09-25 11:37:37.226 car_id=1 [info] Driving / Ended / 0 km – 0 min
2021-09-25 11:37:37.226 car_id=1 [info] Start / :online
2021-09-25 11:37:37.230 car_id=1 [info] Driving / Start
2021-09-25 11:37:38.845 car_id=1 [info] Driving / Ended / 0 km – 0 min
2021-09-25 11:37:38.845 car_id=1 [info] Start / :online
2021-09-25 11:37:38.850 car_id=1 [info] Driving / Start
2021-09-25 11:37:40.503 car_id=1 [info] Driving / Ended / 0 km – 0 min
2021-09-25 11:37:40.503 car_id=1 [info] Start / :online
2021-09-25 11:39:09.323 car_id=1 [info] Received stream data: :inactive
2021-09-25 11:40:45.438 car_id=1 [info] Suspending logging
2021-09-25 11:41:38.450 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:43:30.031 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:44:39.714 [error] ** (FunctionClauseError) no function clause matching in TeslaApi.Stream.handle_info/2
    (teslamate 1.24.0) lib/tesla_api/stream.ex:63: TeslaApi.Stream.handle_info({:ssl, {:sslsocket, {:gen_tcp, #Port<0.2587>, :tls_connection, :undefined}, [#PID<0.4139.5>, #PID<0.4138.5>]}, <<136, 0>>}, %TeslaApi.Stream.State{auth: %TeslaApi.Auth{created_at: 1630495265, expires_in: 3888000, refresh_token: "<deleted>", token: "<deleted>", type: "bearer"}, disconnects: 1, last_data: %TeslaApi.Stream.Data{elevation: 27, est_heading: 231, est_lat: <deleted>, est_lng: <deleted>, est_range: 194, heading: 231, odometer: 5498.8, power: 0, range: 208, shift_state: nil, soc: 69, speed: nil, time: ~U[2021-09-25 10:43:53.763Z]}, receiver: #Function<0.82253542/1 in TeslaMate.Vehicles.Vehicle.connect_stream/1>, timeouts: 1, timer: #Reference<0.532077407.1182269441.223923>, vehicle_id: <deleted>})
    (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3
    (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4
    (stdlib 3.8.2.4) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

2021-09-25 11:44:49.234 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<deleted>/vehicle_data -> 408 (9140.497 ms)
2021-09-25 11:44:49.234 car_id=1 [error] Error / :vehicle_unavailable
2021-09-25 11:45:19.976 car_id=1 [info] Start / :online
2021-09-25 11:45:19.982 car_id=1 [info] Connecting ...
2021-09-25 11:47:53.616 car_id=1 [info] Suspending logging
2021-09-25 11:48:46.500 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:51:03.968 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:53:34.262 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:55:54.433 car_id=1 [info] Fetching vehicle state ...
2021-09-25 11:58:04.791 car_id=1 [info] Fetching vehicle state ...
2021-09-25 12:01:43.049 car_id=1 [info] Fetching vehicle state ...
2021-09-25 12:04:45.262 car_id=1 [info] Fetching vehicle state ...
2021-09-25 12:04:45.574 car_id=1 [info] Start / :asleep
2021-09-25 12:04:45.590 car_id=1 [info] Disconnecting ...
```

### Type of installation

Manual

### Version

v1.24.0

**Comment by adriankumpf** [comment]
Thanks for the report!

That error had no negative effects. The successful recovery can be seen in the lines below (`Connecting ...` etc). Nevertheless, it should still be handled properly without logging any errors of course. That's done in cbf8d89.
