### ISSUE TITLE
http://192.168.199.199:4000 Internal Server error

### ISSUE THREAD

**Issue by dkny1123a** [adriankumpf/teslamate#2037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

http://192.168.199.199:3000/ internal server error

### Relevant log output

```shell
Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1

2021-10-07 02:06:57.900 [info] SIGTERM received - shutting down


2021-10-07 02:07:21.508 [info] Migrations already up

2021-10-07 02:07:24.630 [info] System Info: Erlang/OTP 24 (emu)

2021-10-07 02:07:24.631 [info] Version: 1.24.2

2021-10-07 02:07:24.916 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (223.912 ms)

2021-10-07 02:07:25.517 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (599.892 ms)

2021-10-07 02:07:25.517 [info] Refreshed api tokens

2021-10-07 02:07:25.536 [info] Scheduling token refresh in 5 wk 5 d

2021-10-07 02:07:25.553 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)

2021-10-07 02:07:25.557 [info] Access TeslaMateWeb.Endpoint at http://localhost

2021-10-07 02:07:25.669 [info] Starting logger for 'Yumi'

2021-10-07 02:07:25.695 [info] MQTT connection has been established

2021-10-07 02:07:25.780 car_id=1 [info] Start / :asleep

2021-10-07 02:07:36.887 [info] GET /

2021-10-07 02:07:36.928 [info] Sent 500 in 41ms

2021-10-07 02:07:36.930 [error] #PID<0.2488.0> running TeslaMateWeb.Endpoint (connection #PID<0.2487.0>, stream id 1) terminated

Server: m3portal.ddnsto.com:80 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1

2021-10-07 02:08:04.523 [info] GET /

2021-10-07 02:08:04.534 [info] Sent 500 in 10ms

2021-10-07 02:08:04.536 [error] #PID<0.2490.0> running TeslaMateWeb.Endpoint (connection #PID<0.2489.0>, stream id 1) terminated

Server: m3portal.ddnsto.com:80 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1

2021-10-07 02:12:13.036 [info] GET /

2021-10-07 02:12:13.052 [info] Sent 500 in 15ms

2021-10-07 02:12:13.054 [error] #PID<0.2503.0> running TeslaMateWeb.Endpoint (connection #PID<0.2502.0>, stream id 1) terminated

Server: m3portal.ddnsto.com:80 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1

2021-10-07 02:18:27.506 [info] GET /

2021-10-07 02:18:27.521 [info] Sent 500 in 14ms

2021-10-07 02:18:27.522 [error] #PID<0.2522.0> running TeslaMateWeb.Endpoint (connection #PID<0.2521.0>, stream id 1) terminated

Server: m3portal.ddnsto.com:80 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1

2021-10-07 02:20:01.096 [info] GET /

2021-10-07 02:20:01.112 [info] Sent 500 in 15ms

2021-10-07 02:20:01.113 [error] #PID<0.2530.0> running TeslaMateWeb.Endpoint (connection #PID<0.2529.0>, stream id 1) terminated

Server: m3portal.ddnsto.com:80 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1

        (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3

        (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1

        (teslamate 1.24.2) TeslaMateWeb.Router.browser/2

        (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
```

### Type of installation

Docker

### Version

v1.24.2

**Comment by dkny1123a** [comment]
Recreate the database container.
