### ISSUE TITLE
Home: Internal Server Error

### ISSUE THREAD

**Issue by umb87** [adriankumpf/teslamate#2077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Homepage doesn't available... 
Internal Server Error when I go to homepage

### Relevant log output

```shell
Last login: Sun Oct 17 21:08:11 2021 from 192.168.2.239
Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.
pi@raspberrypi:~ $ cd /media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1/
pi@raspberrypi:/media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1 $ docker container ls
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f38e45ceb2cb postgres:13 "docker-entrypoint.s…" 38 minutes ago Up 38 minutes 5432/tcp b93a4f77-d5a4-4424-
847e-cddec00de54a1_database_1
470448209eea teslamate/grafana:latest "/run.sh" 38 minutes ago Up 38 minutes 0.0.0.0:3000->3000/tcp,
:::3000->3000/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_grafana_1
0a63bb2a3385 eclipse-mosquitto:2 "/docker-entrypoint.…" 38 minutes ago Up 38 minutes 0.0.0.0:1883-
>1883/tcp, :::1883->1883/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_mosquitto_1
6644f45dbdf2 teslamate/teslamate:latest "tini -- /bin/sh /en…" 38 minutes ago Up 38 minutes 0.0.0.0:4000-
>4000/tcp, :::4000->4000/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_teslamate_1
pi@raspberrypi:/media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1 $ docker logs 6644f45dbdf2
2021-10-17 19:06:58.769 [info] Migrations already up
2021-10-17 19:07:02.047 [info] System Info: Erlang/OTP 24 (emu)2021-10-17 19:07:02.047 [info] Version:
1.24.2
2021-10-17 19:07:02.547 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (399.032 ms)
2021-10-17 19:07:03.886 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (1338.311 ms)
2021-10-17 19:07:03.887 [info] Refreshed api tokens
2021-10-17 19:07:03.958 [info] Scheduling token refresh in 5 wk 5 d
2021-10-17 19:07:03.972 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2021-10-17 19:07:03.976 [info] Access TeslaMateWeb.Endpoint at http://localhost
2021-10-17 19:07:04.327 [info] Starting logger for 'Silver Knight'
2021-10-17 19:07:04.381 [info] MQTT connection has been established
2021-10-17 19:07:04.651 car_id=1 [info] Start / :online
2021-10-17 19:07:04.757 car_id=1 [info] Connecting ...
2021-10-17 19:07:05.111 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (333.528 ms)
2021-10-17 19:07:05.213 car_id=1 [info] Charging / SOC: 28% / BeCharge 55
2021-10-17 19:07:05.213 car_id=1 [info] Disconnecting ...
2021-10-17 19:07:05.607 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020
23:35:21 GMT. Release file on server was last modified Fri, 15 Oct 2021 21:20:55 GMT.
2021-10-17 19:07:10.422 [info] Tzdata has updated the release from 2020e to 2021d
2021-10-17 19:07:25.205 [info] GET /geo-fences/new
2021-10-17 19:07:25.216 [info] Sent 500 in 10ms
2021-10-17 19:07:25.217 [error] #PID<0.2541.0> running TeslaMateWeb.Endpoint (connection #PID<0.2539.0>,
stream id 1) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /geo-fences/new?lat=45.475484&lng=9.152018
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
2021-10-17 19:07:31.627 [info] GET /
2021-10-17 19:07:31.644 [info] Sent 500 in 15ms
2021-10-17 19:07:31.645 [error] #PID<0.2545.0> running TeslaMateWeb.Endpoint (connection #PID<0.2539.0>,
stream id 2) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
2021-10-17 19:08:05.254 [info] GET /
2021-10-17 19:08:05.269 [info] Sent 500 in 14ms
2021-10-17 19:08:05.271 [error] #PID<0.2554.0> running TeslaMateWeb.Endpoint (connection #PID<0.2539.0>,
stream id 3) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
2021-10-17 19:08:06.924 [info] GET /
2021-10-17 19:08:06.935 [info] Sent 500 in 9ms
2021-10-17 19:08:06.936 [error] #PID<0.2556.0> running TeslaMateWeb.Endpoint (connection #PID<0.2539.0>,
stream id 4) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
2021-10-17 19:16:16.693 [info] GET /
2021-10-17 19:16:16.701 [info] Sent 500 in 7ms
2021-10-17 19:16:16.702 [error] #PID<0.2673.0> running TeslaMateWeb.Endpoint (connection #PID<0.2672.0>,
stream id 1) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
2021-10-17 19:16:18.120 [info] GET /
2021-10-17 19:16:18.126 [info] Sent 500 in 6ms
2021-10-17 19:16:18.128 [error] #PID<0.2675.0> running TeslaMateWeb.Endpoint (connection #PID<0.2672.0>,
stream id 3) terminated
Server: 192.168.2.86:4000 (http)
Request: GET /
** (exit) an exception was raised:
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
(ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
(ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
(teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15: TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
(teslamate 1.24.2) TeslaMateWeb.Router.browser/2
(teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
pi@raspberrypi:/media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1 $ docker container ls
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f38e45ceb2cb postgres:13 "docker-entrypoint.s…" 39 minutes ago Up 39 minutes 5432/tcp b93a4f77-d5a4-4424-
847e-cddec00de54a1_database_1
470448209eea teslamate/grafana:latest "/run.sh" 39 minutes ago Up 39 minutes 0.0.0.0:3000->3000/tcp,
:::3000->3000/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_grafana_1
0a63bb2a3385 eclipse-mosquitto:2 "/docker-entrypoint.…" 39 minutes ago Up 39 minutes 0.0.0.0:1883-
>1883/tcp, :::1883->1883/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_mosquitto_1
6644f45dbdf2 teslamate/teslamate:latest "tini -- /bin/sh /en…" 39 minutes ago Up 39 minutes 0.0.0.0:4000-
>4000/tcp, :::4000->4000/tcp b93a4f77-d5a4-4424-847e-cddec00de54a1_teslamate_1
pi@raspberrypi:/media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1 $ docker logs f38e45ceb2cb
PostgreSQL Database directory appears to contain a database; Skipping initialization
1970-01-01 00:00:00.000 UTC [1] LOG: starting PostgreSQL 13.4 (Debian 13.4-4.pgdg110+1) on arm-unknown-
linux-gnueabihf, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 32-bit
1970-01-01 00:00:00.000 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432
1970-01-01 00:00:00.000 UTC [1] LOG: listening on IPv6 address "::", port 5432
1970-01-01 00:00:00.000 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
1970-01-01 00:00:00.000 UTC [27] LOG: database system was shut down at 1970-04-27 12:27:20 UTC
1970-01-01 00:00:00.000 UTC [1] LOG: database system is ready to accept connections
1970-01-01 00:00:00.000 UTC [33] LOG: stats_timestamp 2000-01-01 00:00:00+00 is later than collector's
time 1969-12-31 23:41:48.185232+00 for database 0
1970-01-01 00:00:00.000 UTC [32] LOG: stats collector's time 1970-05-04 05:14:18.646024+00 is later than
backend local time 1970-01-06 14:54:02+00
1970-01-01 00:00:00.000 UTC [33] LOG: stats_timestamp 1970-05-04 05:14:18.646024+00 is later than
collector's time 1969-12-31 23:41:48.185232+00 for database 0
1970-01-01 00:00:00.000 UTC [37] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [37] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
1970-01-01 00:00:00.000 UTC [46] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [46] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
1970-01-01 00:00:00.000 UTC [39] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [39] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
1970-01-01 00:00:00.000 UTC [46] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [46] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
1970-01-01 00:00:00.000 UTC [37] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [37] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
1970-01-01 00:00:00.000 UTC [39] ERROR: integer out of range
1970-01-01 00:00:00.000 UTC [39] STATEMENT: SELECT EXTRACT(EPOCH FROM age(NOW(),
s0."inserted_at"::timestamp))::integer FROM "schema_migrations" AS s0 ORDER BY s0."inserted_at" DESC LIMIT
1
pi@raspberrypi:/media/pi/b93a4f77-d5a4-4424-847e-cddec00de54a1 $ docker-compose logs teslamate
Attaching to b93a4f77-d5a4-4424-847e-cddec00de54a1_teslamate_1
teslamate_1 | 2021-10-17 19:06:58.769 [info] Migrations already up
teslamate_1 | 2021-10-17 19:07:02.047 [info] System Info: Erlang/OTP 24 (emu)
teslamate_1 | 2021-10-17 19:07:02.047 [info] Version: 1.24.2
teslamate_1 | 2021-10-17 19:07:02.547 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (399.032
ms)
teslamate_1 | 2021-10-17 19:07:03.886 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200
(1338.311 ms)
teslamate_1 | 2021-10-17 19:07:03.887 [info] Refreshed api tokens
teslamate_1 | 2021-10-17 19:07:03.958 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1 | 2021-10-17 19:07:03.972 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000
(http)
teslamate_1 | 2021-10-17 19:07:03.976 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1 | 2021-10-17 19:07:04.327 [info] Starting logger for 'Silver Knight'
teslamate_1 | 2021-10-17 19:07:04.381 [info] MQTT connection has been established
teslamate_1 | 2021-10-17 19:07:04.651 car_id=1 [info] Start / :online
teslamate_1 | 2021-10-17 19:07:04.757 car_id=1 [info] Connecting ...
teslamate_1 | 2021-10-17 19:07:05.111 [info] GET https://nominatim.openstreetmap.org/reverse -> 200
(333.528 ms)
teslamate_1 | 2021-10-17 19:07:05.213 car_id=1 [info] Charging / SOC: 28% / BeCharge 55
teslamate_1 | 2021-10-17 19:07:05.213 car_id=1 [info] Disconnecting ...
teslamate_1 | 2021-10-17 19:07:05.607 [info] tzdata release in place is from a file last modified Tue, 22
Dec 2020 23:35:21 GMT. Release file on server was last modified Fri, 15 Oct 2021 21:20:55 GMT.
teslamate_1 | 2021-10-17 19:07:10.422 [info] Tzdata has updated the release from 2020e to 2021d
teslamate_1 | 2021-10-17 19:07:25.205 [info] GET /geo-fences/new
teslamate_1 | 2021-10-17 19:07:25.216 [info] Sent 500 in 10ms
teslamate_1 | 2021-10-17 19:07:25.217 [error] #PID<0.2541.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2539.0>, stream id 1) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /geo-fences/new?lat=45.475484&lng=9.152018
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
teslamate_1 | 2021-10-17 19:07:31.627 [info] GET /
teslamate_1 | 2021-10-17 19:07:31.644 [info] Sent 500 in 15ms
teslamate_1 | 2021-10-17 19:07:31.645 [error] #PID<0.2545.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2539.0>, stream id 2) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
teslamate_1 | 2021-10-17 19:08:05.254 [info] GET /
teslamate_1 | 2021-10-17 19:08:05.269 [info] Sent 500 in 14ms
teslamate_1 | 2021-10-17 19:08:05.271 [error] #PID<0.2554.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2539.0>, stream id 3) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
teslamate_1 | 2021-10-17 19:08:06.924 [info] GET /
teslamate_1 | 2021-10-17 19:08:06.935 [info] Sent 500 in 9ms
teslamate_1 | 2021-10-17 19:08:06.936 [error] #PID<0.2556.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2539.0>, stream id 4) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
teslamate_1 | 2021-10-17 19:16:16.693 [info] GET /
teslamate_1 | 2021-10-17 19:16:16.701 [info] Sent 500 in 7ms
teslamate_1 | 2021-10-17 19:16:16.702 [error] #PID<0.2673.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2672.0>, stream id 1) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_through0__/1
teslamate_1 | 2021-10-17 19:16:18.120 [info] GET /
teslamate_1 | 2021-10-17 19:16:18.126 [info] Sent 500 in 6ms
teslamate_1 | 2021-10-17 19:16:18.128 [error] #PID<0.2675.0> running TeslaMateWeb.Endpoint (connection
#PID<0.2672.0>, stream id 3) terminated
teslamate_1 | Server: 192.168.2.86:4000 (http)
teslamate_1 | Request: GET /
teslamate_1 | ** (exit) an exception was raised:
teslamate_1 | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) integer out of range
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1 | (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1 | (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/plugs/donate.ex:15:
TeslaMateWeb.Plugs.Donate.put_donate_cookie/1
teslamate_1 | (teslamate 1.24.2) TeslaMateWeb.Router.browser/2
teslamate_1 | (teslamate 1.24.2) lib/teslamate_web/router.ex:1: TeslaMateWeb.Router.__pipe_throug
```

### Screenshots

![Screenshot_20211017-215247](https://user-images.githubusercontent.com/92692098/137642888-dcc245ed-2523-4e26-b3bd-cce3f4abb630.jpg)
![Screenshot_20211017-211223](https://user-images.githubusercontent.com/92692098/137642891-f3f52dfd-6993-40bc-997c-bb235bf016cd.jpg)
[Shell SSH.pdf](https://github.com/adriankumpf/teslamate/files/7360738/Shell.SSH.pdf)

### Type of installation

Docker

### Version

V1.24.2

**Comment by adriankumpf** [comment]
Hey @umb87, could you post the output this command:

```bash
 docker-compose exec database psql teslamate teslamate -c 'SELECT now() AS now, EXTRACT(EPOCH FROM age(NOW(), inserted_at::timestamp)) AS seconds, inserted_at from schema_migrations ORDER BY inserted_at DESC LIMIT 10;'
```

**Comment by umb87** [comment]
Hi,
Of course 😊

Thanks.

--------------
Umberto Agosto
tel:+393334669457
***@***.***

Il gio 21 ott 2021, 12:30 Adrian Kumpf ***@***.***> ha
scritto:
