### ISSUE TITLE
Internal server error when trying to view setings

### ISSUE THREAD

**Issue by SigLinJo** [adriankumpf/teslamate#2079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking settings in the web UI i get the message "Internal Server Error" It only happens on one (my own) of three instances of Teslamate running parallel on my server (I help a couple of friends with hosting Teslamate). 

I checked my settings in docker-compose and nothing differs other than what should differ like the locations for databases, urls for the different instances and ports for the different services. It has worked before with this exact setup, but maybe with an eariler version of Teslamate. I have changed subnet of my local network once, not shure if this problem was there before that.

Any hint would be very appreciated. I have tried to recreate the docker containers with no change...

### Expected Behavior

Settings menu should appear

### Steps To Reproduce

1. Go to teslamate web gui
2. Klick on Settings
3. Error happens

### Relevant log output

```shell
teslamate_1  | Server: 192.168.55.111:4000 (http)
teslamate_1  | Request: GET /settings
teslamate_1  | ** (exit) an exception was raised:
teslamate_1  |     ** (UndefinedFunctionError) function nil.id/0 is undefined
teslamate_1  |         nil.id()
teslamate_1  |         (teslamate 1.24.2) lib/teslamate_web/live/settings_live/index.ex:184: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
teslamate_1  |         (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |         (teslamate 1.24.2) lib/teslamate_web/live/settings_live/index.ex:16: TeslaMateWeb.SettingsLive.Index.mount/3
teslamate_1  |         (phoenix_live_view 0.16.4) lib/phoenix_live_view/utils.ex:301: anonymous fn/5 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4
teslamate_1  |         (telemetry 1.0.0) /opt/app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
teslamate_1  |         (phoenix_live_view 0.16.4) lib/phoenix_live_view/static.ex:260: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
teslamate_1  |         (phoenix_live_view 0.16.4) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
```

### Type of installation

Docker

### Version

v1.24.2

**Comment by SigLinJo** [comment]
I had my friends car added to my Tesla account during a month in the spring and then removed it again, maybe something went wrong during that time? I remember that I went in to my database and removed the other car to not have it show up as missing in all my grafana dashboards...
