### ISSUE TITLE
Consumption and efficiency too low and not adjusting

### ISSUE THREAD

**Issue by SylvainGa** [adriankumpf/teslamate#2111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've logged 2674 km in 245 trips in Teslamate. My consumption is 62W Wh/km which is way lower than what the car displays (147 Wh/km) for 4348 km. 

### Expected Behavior

Realistic consumption and efficiency

### Steps To Reproduce

Installed as a docker image on a RaspberryPi4 running raspbian. Logged into my account and started capturing data. Consumption en efficiency has been low from the start.
[Teslamate.log](https://github.com/adriankumpf/teslamate/files/7445538/Teslamate.log)

### Relevant log output

```shell
I had to stop the redirection of the log to a file because it was 106MB after 5 minutes (and still logging). I've uploaded the beginning of the file. Let me know if you want the whole thing in the 'Step to reproduce'
```

### Screenshots

![image](https://user-images.githubusercontent.com/49377866/139515141-4a41f43d-4d8b-409d-ade0-ead23f944eb3.png)

### Additional data

This is the data for today
[charges.csv](https://github.com/adriankumpf/teslamate/files/7445542/charges.csv)
[charging_processes.csv](https://github.com/adriankumpf/teslamate/files/7445543/charging_processes.csv)
[positions.csv](https://github.com/adriankumpf/teslamate/files/7445544/positions.csv)
[drives.csv](https://github.com/adriankumpf/teslamate/files/7445545/drives.csv)

### Type of installation

Docker

### Version

v1.24.2 (behaved the same with v1.24.1)

**Comment by SylvainGa** [comment]
This is the last 100 lines from the log (from docker-compose logs --tail=100 teslamate)

```
Attaching to pi_teslamate_1
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [charger_actual_current: 32]]
teslamate_1  | 2021-10-30 01:51:34.593 [error] Task #PID<0.2741.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/update_version", "", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [update_version: ""]]
teslamate_1  | 2021-10-30 01:51:34.595 [error] Task #PID<0.2744.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/outside_temp", "10.5", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [outside_temp: 10.5]]
teslamate_1  | 2021-10-30 01:51:34.589 [error] Task #PID<0.2738.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/display_name", "Christine", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [display_name: "Christine"]]
teslamate_1  | 2021-10-30 01:51:34.587 [error] Task #PID<0.2730.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/spoiler_type", "None", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [spoiler_type: "None"]]
teslamate_1  | 2021-10-30 01:51:34.599 [error] Task #PID<0.2742.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/power", "-7", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [power: -7]]
teslamate_1  | 2021-10-30 01:51:34.600 [error] Task #PID<0.2743.0> started from #PID<0.2712.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/ideal_battery_range_km", "222.67", [retain: true, qos: 1]}, 10000)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (WithClauseError) no with clause matching: {:error, :timeout}
teslamate_1  |             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
teslamate_1  |             (teslamate 1.24.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
teslamate_1  |             (stdlib 3.16) gen_server.erl:721: :gen_server.try_handle_call/4
teslamate_1  |             (stdlib 3.16) gen_server.erl:750: :gen_server.handle_msg/6
teslamate_1  |             (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  |     (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
teslamate_1  |     (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Function: &:erlang.apply/2
teslamate_1  |     Args: [#Function<4.48828428/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [ideal_battery_range_km: 222.67]]
```

**Comment by SylvainGa** [comment]
Oh, forgot to say, with all the MQTT errors, I disabled MQTT like such:

```
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - DISABLE_MQTT=true
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
```

**Comment by SylvainGa** [comment]
Noticed the following 👍 

select now();
          now
------------------------
 **1905-03-24 08:17:04+00**  --WTF?

From OS:

#: date
Sat 30 Oct 14:02:08 EDT 2021

**Comment by SylvainGa** [comment]
I'm starting over so I'm closing this.
