### ISSUE TITLE
Compile error with 1.25.0

### ISSUE THREAD

**Issue by airmaxx** [adriankumpf/teslamate#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
git checkout -f tags/v1.25.0
mix deps.get --only prod
npm install --prefix ./assets && npm run deploy --prefix ./assets
mix phx.digest
```
leads to 
```
Compiling 82 files (.ex)
Generating TeslaMateWeb.Cldr for 16 locales named ["da", "de", "en", "es", "fi", ...] with a default locale named "en"

== Compilation error in file lib/teslamate_web/cldr.ex ==
** (FunctionClauseError) no function clause matching in Cldr.Map.atomize_values/2    
    
    The following arguments were given to Cldr.Map.atomize_values/2:
    
        # 1
        "hanidec"
    
        # 2
        [only_existing: false]
    
    Attempted function clauses (showing 2 out of 2):
    
        def atomize_values(map, options) when is_map(map) or is_list(map)
        def atomize_values({k, value}, options) when is_map(value) or is_list(value)
    
    (cldr_utils 2.17.0) lib/cldr/utils/map.ex:349: Cldr.Map.atomize_values/2
    (ex_cldr 2.24.1) lib/cldr/locale/loader.ex:146: anonymous fn/1 in Cldr.Locale.Loader.structure_date_formats/1
    (cldr_utils 2.17.0) lib/cldr/utils/map.ex:182: anonymous fn/5 in Cldr.Map.deep_map/4
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (cldr_utils 2.17.0) lib/cldr/utils/map.ex:159: Cldr.Map.deep_map/4
    (cldr_utils 2.17.0) lib/cldr/utils/map.ex:166: anonymous fn/5 in Cldr.Map.deep_map/4
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (cldr_utils 2.17.0) lib/cldr/utils/map.ex:159: Cldr.Map.deep_map/4
```

I tried mix.phx.clean - didn't help

Any ideas what went wrong?

### Relevant log output

```shell
n/a
```

### Type of installation

Manual

### Version

v1.25.0

**Comment by adriankumpf** [comment]
Hi @airmaxx, try to delete the locale cache:

```bash
rm -rf priv/cldr/*
```

**Comment by airmaxx** [comment]
Thank you, this worked!
