### ISSUE TITLE
Software / Firmware Update Missing

### ISSUE THREAD

**Issue by hoang51** [adriankumpf/teslamate#2189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the main Teslamate home page, the software/firmware for my Tesla is correctly reported as "Version	2021.36.8.8". See included screenshot. However, going to Teslamate / Overview, Firmware block does not display anything. See included screenshot. Furthermore, going to Teslamate / Updates, a recent update to firmware 2021.36.8.8 (FSD beta 10.5), which happened on 11/23/2021, did not record correctly and also made two entries in the Updates page. See included screenshot. I have not seen anybody reported this issue for Teslamate 1.25.0. I'm not sure if the log captured the update because I don't see any entry in the log retrieved to indicate an update was performing when looking at to Teslamate / Timeline. Could this be a mismatch Timeline date/time and TM_TZ variable (wasn't set properly to America/New_York to capture correct time zone, have updated .env, but haven't restarted Teslamate)? The Timeline date/time appears to be accurate at detecting the correct time zone (compared with Google Maps Timeline) when I used my car today.

Edit update 11/27/2021: So I finally found the associated update to firmware 2021.36.8.8 in the log and I see there's an error associated with Teslamate:

```
teslamate_1  |  ** (FunctionClauseError) no function clause matching in TeslaMate.Vehicles.Vehicle.handle_event/4
```

BTW, TM_TZ variable played a role in logging incorrect time, which caused me to look at the wrong timestampe in the log. I took down Teslamate and brought it back up so that it has the correct TM_TZ after fixing it in the .env file. This definitely caused an offset in time for the logs of +6 hours. I have extracted the relevant log associated with the firmware update and provided below. I have also marked the previous log irrelevant in its own section that was nothing related to the firmware update.

### Expected Behavior

After a recent software update to 2021.36.8.8 on 11/23/2021, Teslamate should've recorded the software update and displayed it correctly on the Teslamate / Overview page and only have one entry line on the Teslamate / Updates page.

### Steps To Reproduce

Navigate to Teslamate / Overview and/or Teslamate / Updates after recent FSD beta update 2021.36.8.8.

### Relevant log output

```shell
teslamate_1  |  2021-11-23 10:52:57.071 car_id=1 [info] Update / Start
teslamate_1  |  2021-11-23 10:52:57.111 car_id=1 [info] Disconnecting ...
teslamate_1  |  2021-11-23 10:58:34.900 [error] GenStateMachine :"1" terminating
teslamate_1  |  ** (FunctionClauseError) no function clause matching in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |      (teslamate 1.25.0) lib/teslamate/vehicles/vehicle.ex:170: TeslaMate.Vehicles.Vehicle.handle_event(:internal, {:update, {:asleep, %TeslaApi.Vehicle{api_version: 28, backseat_token: nil, backseat_token_updated_at: nil, calendar_enabled: true, charge_state: %TeslaApi.Vehicle.State.Charge{max_range_charge_counter: 0, charge_limit_soc_std: 90, scheduled_charging_start_time: nil, time_to_full_charge: 0.0, conn_charge_cable: "<invalid>", charger_power: nil, charge_limit_soc: 90, fast_charger_present: nil, managed_charging_active: false, charge_limit_soc_max: 100, charger_pilot_current: nil, charge_to_max_range: false, trip_charging: false, charge_enable_request: true, charge_miles_added_rated: 21.5, charge_port_door_open: nil, not_enough_power_to_heat: nil, est_battery_range: 198.45, charge_current_request_max: 12, charge_limit_soc_min: 50, fast_charger_brand: "<invalid>", charge_port_cold_weather_mode: nil, ideal_battery_range: 237.96, charge_port_latch: "<invalid>", managed_charging_user_canceled: false, timestamp: 1637661514511, battery_heater_on: false, managed_charging_start_time: nil, charge_rate: 0.0, charge_energy_added: 5.45, charge_current_request: 12, battery_range: 237.96, charger_phases: nil, usable_battery_level: 89, user_charge_enable_request: nil, charging_state: nil, battery_level: 90, charge_miles_added_ideal: 21.5, scheduled_charging_pending: false, charger_voltage: nil, fast_charger_type: "<invalid>", ...}, climate_state: %TeslaApi.Vehicle.State.Climate{battery_heater: nil, battery_heater_no_power: nil, climate_keeper_mode: "off", defrost_mode: 0, driver_temp_setting: 19.4, fan_status: 0, inside_temp: nil, is_auto_conditioning_on: nil, is_climate_on: false, is_front_defroster_on: false, is_preconditioning: false, is_rear_defroster_on: false, left_temp_direction: nil, max_avail_temp: 28.0, min_avail_temp: 15.0, outside_temp: nil, passenger_temp_setting: 19.4, remote_heater_control_enabled: false, right_temp_direction: nil, seat_heater_left: 0, seat_heater_rear_center: 0, seat_heater_rear_left: 0, seat_heater_rear_left_back: nil, seat_heater_rear_right: 0, seat_heater_rear_right_back: nil, seat_heater_right: 0, side_mirror_heaters: false, smart_preconditioning: nil, steering_wheel_heater: nil, timestamp: 1637661514511, wiper_blade_heater: false}, color: nil, display_name: "Sonic", drive_state: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1637661513, heading: #, latitude: #, longitude: #, native_latitude: #, native_location_supported: 1, native_longitude: #, native_type: "wgs", power: nil, shift_state: nil, speed: nil, timestamp: 1637661514511}, gui_settings: nil, id: #, in_service: false, option_codes: ["AD15", "MDL3", "PBSB", "RENA", "BT37", "ID3W", "RF3G", "S3PB", "DRLH", "DV2W", "W39B", "APF0", "COUS", "BC3B", "CH07", "PC30", "FC3P", "FG31", "GLFR", "HL31", "HM31", "IL31", "LTPB", "MR31", "FM3B", "RS3H", "SA3P", "STCP", "SC04", "SU3C", "T3CA", "TW00", "TM00", ...], state: "asleep", tokens: ["#", "#"], vehicle_config: %TeslaApi.Vehicle.State.VehicleConfig{can_accept_navigation_requests: true, can_actuate_trunks: true, car_special_type: "base", car_type: "model3", charge_port_type: "US", eu_vehicle: false, exterior_color: "DeepBlue", has_air_suspension: false, has_ludicrous_mode: false, key_version: 2, motorized_charge_port: true, perf_config: nil, plg: false, rear_seat_heaters: 1, rear_seat_type: 0, rhd: false, roof_color: "RoofColorGlass", seat_type: nil, spoiler_type: "Passive", sun_roof_installed: nil, third_row_seats: "None", timestamp: 1637661514511, trim_badging: "p74d", use_range_badging: true, wheel_type: "Stiletto19"}, vehicle_id: #, vehicle_state: %TeslaApi.Vehicle.State.VehicleState{summon_standby_mode_enabled: true, odometer: 10216.508578, homelink_nearby: true, notifications_supported: true, dr: 0, fp_window: 0, autopark_state_v3: "ready", homelink_device_count: 2, software_update: %TeslaApi.Vehicle.State.VehicleState.SoftwareUpdate{download_perc: 100, expected_duration_sec: 1500, install_perc: 60, scheduled_time_ms: nil, status: "installing", version: "2021.36.8.8"}, sun_roof_state: nil, vehicle_name: "Sonic", smart_summon_available: true, fd_window: 0, pr: 0, rp_window: 0, remote_start_supported: true, sentry_mode_available: true, valet_mode: false, calendar_supported: true, sentry_mode: false, locked: true, rt: 0, remote_start: false, rd_window: 0, center_display_state: 0, timestamp: 1637661514511, is_user_present: false, df: 0, ...}, vin: "#"}}}, {:updating, %TeslaMate.Log.Update{__meta__: #Ecto.Schema.Metadata<:loaded, "updates">, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, end_date: nil, id: 2, start_date: ~U[2021-11-23 09:52:56.671000Z], version: nil}}, %TeslaMate.Vehicles.Vehicle.Data{car: %TeslaMate.Log.Car{__meta__: #Ecto.Schema.Metadata<:loaded, "cars">, charging_processes: #Ecto.Association.NotLoaded<association :charging_processes is not loaded>, drives: #Ecto.Association.NotLoaded<association :drives is not loaded>, efficiency: nil, eid: #, exterior_color: "DeepBlue", friendly_name: nil, id: 1, inserted_at: ~N[2021-11-18 09:37:14], model: "3", name: "Sonic", positions: #Ecto.Association.NotLoaded<association :positions is not loaded>, settings: %TeslaMate.Settings.CarSettings{__meta__: #Ecto.Schema.Metadata<:loaded, "car_settings">, car: #Ecto.Association.NotLoaded<association :car is not loaded>, free_supercharging: false, id: 1, req_not_unlocked: false, suspend_after_idle_min: 15, suspend_min: 21, use_streaming_api: true}, settings_id: 1, spoiler_type: "Passive", trim_badging: "P74D", updated_at: ~N[2021-11-18 17:30:39], vid: 1986078119, vin: "#", wheel_type: "Stiletto19"}, deps: %{api: TeslaMate.Api, locations: TeslaMate.Locations, log: TeslaMate.Log, pubsub: Phoenix.PubSub, settings: TeslaMate.Settings, vehicles: TeslaMate.Vehicles}, elevation: 104, geofence: nil, import?: false, last_response: %TeslaApi.Vehicle{api_version: 28, backseat_token: nil, backseat_token_updated_at: nil, calendar_enabled: true, charge_state: %TeslaApi.Vehicle.State.Charge{max_range_charge_counter: 0, charge_limit_soc_std: 90, scheduled_charging_start_time: nil, time_to_full_charge: 0.0, conn_charge_cable: "<invalid>", charger_power: nil, charge_limit_soc: 90, fast_charger_present: nil, managed_charging_active: false, charge_limit_soc_max: 100, charger_pilot_current: nil, charge_to_max_range: false, trip_charging: false, charge_enable_request: true, charge_miles_added_rated: 21.5, charge_port_door_open: nil, not_enough_power_to_heat: nil, est_battery_range: 198.45, charge_current_request_max: 12, charge_limit_soc_min: 50, fast_charger_brand: "<invalid>", charge_port_cold_weather_mode: nil, ideal_battery_range: 237.96, charge_port_latch: "<invalid>", managed_charging_user_canceled: false, timestamp: 1637661499123, battery_heater_on: false, managed_charging_start_time: nil, charge_rate: 0.0, charge_energy_added: 5.45, charge_current_request: 12, battery_range: 237.96, charger_phases: nil, usable_battery_level: 89, user_charge_enable_request: nil, charging_state: nil, battery_level: 90, charge_miles_added_ideal: 21.5, scheduled_charging_pending: false, ...}, climate_state: %TeslaApi.Vehicle.State.Climate{battery_heater: nil, battery_heater_no_power: nil, climate_keeper_mode: "off", defrost_mode: 0, driver_temp_setting: 19.4, fan_status: 0, inside_temp: nil, is_auto_conditioning_on: nil, is_climate_on: false, is_front_defroster_on: false, is_preconditioning: false, is_rear_defroster_on: false, left_temp_direction: nil, max_avail_temp: 28.0, min_avail_temp: 15.0, outside_temp: nil, passenger_temp_setting: 19.4, remote_heater_control_enabled: false, right_temp_direction: nil, seat_heater_left: 0, seat_heater_rear_center: 0, seat_heater_rear_left: 0, seat_heater_rear_left_back: nil, seat_heater_rear_right: 0, seat_heater_rear_right_back: nil, s (truncated)
teslamate_1  |  2021-11-23 10:58:35.059 car_id=1 [info] Start / :asleep
teslamate_1  |  2021-11-23 10:59:15.768 car_id=1 [info] Start / :online
teslamate_1  |  2021-11-23 10:59:15.776 car_id=1 [info] Connecting ...
teslamate_1  |  2021-11-23 10:59:15.777 car_id=1 [info] Update / Start
teslamate_1  |  2021-11-23 10:59:15.781 car_id=1 [info] Disconnecting ...
teslamate_1  |  2021-11-23 11:00:01.948 [error] GenStateMachine :"1" terminating
teslamate_1  |  ** (FunctionClauseError) no function clause matching in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |      (teslamate 1.25.0) lib/teslamate/vehicles/vehicle.ex:170: TeslaMate.Vehicles.Vehicle.handle_event(:internal, {:update, {:asleep, %TeslaApi.Vehicle{api_version: 28, backseat_token: nil, backseat_token_updated_at: nil, calendar_enabled: true, charge_state: %TeslaApi.Vehicle.State.Charge{max_range_charge_counter: 0, charge_limit_soc_std: 90, scheduled_charging_start_time: nil, time_to_full_charge: 0.0, conn_charge_cable: "SAE", charger_power: 0, charge_limit_soc: 90, fast_charger_present: false, managed_charging_active: false, charge_limit_soc_max: 100, charger_pilot_current: 12, charge_to_max_range: false, trip_charging: false, charge_enable_request: true, charge_miles_added_rated: 21.0, charge_port_door_open: true, not_enough_power_to_heat: nil, est_battery_range: 198.11, charge_current_request_max: 12, charge_limit_soc_min: 50, fast_charger_brand: "<invalid>", charge_port_cold_weather_mode: false, ideal_battery_range: 237.55, charge_port_latch: "Engaged", managed_charging_user_canceled: false, timestamp: 1637661601522, battery_heater_on: false, managed_charging_start_time: nil, charge_rate: 0.0, charge_energy_added: 5.34, charge_current_request: 12, battery_range: 237.55, charger_phases: 1, usable_battery_level: 89, user_charge_enable_request: nil, charging_state: "Complete", battery_level: 90, charge_miles_added_ideal: 21.0, scheduled_charging_pending: false, charger_voltage: 2, fast_charger_type: "MCSingleWireCAN", ...}, climate_state: %TeslaApi.Vehicle.State.Climate{battery_heater: false, battery_heater_no_power: nil, climate_keeper_mode: "off", defrost_mode: 0, driver_temp_setting: 19.4, fan_status: 0, inside_temp: 8.5, is_auto_conditioning_on: false, is_climate_on: false, is_front_defroster_on: false, is_preconditioning: false, is_rear_defroster_on: false, left_temp_direction: 0, max_avail_temp: 28.0, min_avail_temp: 15.0, outside_temp: 7.5, passenger_temp_setting: 19.4, remote_heater_control_enabled: false, right_temp_direction: 0, seat_heater_left: 0, seat_heater_rear_center: 0, seat_heater_rear_left: 0, seat_heater_rear_left_back: nil, seat_heater_rear_right: 0, seat_heater_rear_right_back: nil, seat_heater_right: 0, side_mirror_heaters: false, smart_preconditioning: nil, steering_wheel_heater: nil, timestamp: 1637661601522, wiper_blade_heater: false}, color: nil, display_name: "Sonic", drive_state: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1637661571, heading: #, latitude: #, longitude: #, native_latitude: #, native_location_supported: 1, native_longitude: #, native_type: "wgs", power: 0, shift_state: nil, speed: nil, timestamp: 1637661601522}, gui_settings: nil, id: #, in_service: false, option_codes: ["AD15", "MDL3", "PBSB", "RENA", "BT37", "ID3W", "RF3G", "S3PB", "DRLH", "DV2W", "W39B", "APF0", "COUS", "BC3B", "CH07", "PC30", "FC3P", "FG31", "GLFR", "HL31", "HM31", "IL31", "LTPB", "MR31", "FM3B", "RS3H", "SA3P", "STCP", "SC04", "SU3C", "T3CA", "TW00", "TM00", ...], state: "asleep", tokens: ["#", "#"], vehicle_config: %TeslaApi.Vehicle.State.VehicleConfig{can_accept_navigation_requests: true, can_actuate_trunks: true, car_special_type: "base", car_type: "model3", charge_port_type: "US", eu_vehicle: false, exterior_color: "DeepBlue", has_air_suspension: false, has_ludicrous_mode: false, key_version: 2, motorized_charge_port: true, perf_config: nil, plg: false, rear_seat_heaters: 1, rear_seat_type: 0, rhd: false, roof_color: "RoofColorGlass", seat_type: nil, spoiler_type: "Passive", sun_roof_installed: nil, third_row_seats: "None", timestamp: 1637661601522, trim_badging: "p74d", use_range_badging: true, wheel_type: "Stiletto19"}, vehicle_id: #, vehicle_state: %TeslaApi.Vehicle.State.VehicleState{summon_standby_mode_enabled: true, odometer: 10216.508578, homelink_nearby: true, notifications_supported: true, dr: 0, fp_window: 0, autopark_state_v3: "standby", homelink_device_count: 2, software_update: %TeslaApi.Vehicle.State.VehicleState.SoftwareUpdate{download_perc: 100, expected_duration_sec: 1500, install_perc: 80, scheduled_time_ms: nil, status: "installing", version: "2021.36.8.8"}, sun_roof_state: nil, vehicle_name: "Sonic", smart_summon_available: true, fd_window: 0, pr: 0, rp_window: 0, remote_start_supported: true, sentry_mode_available: true, valet_mode: false, calendar_supported: true, sentry_mode: false, locked: true, rt: 0, remote_start: false, rd_window: 0, center_display_state: 0, timestamp: 1637661601521, is_user_present: false, df: 0, ...}, vin: "#"}}}, {:updating, %TeslaMate.Log.Update{__meta__: #Ecto.Schema.Metadata<:loaded, "updates">, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, end_date: nil, id: 3, start_date: ~U[2021-11-23 09:59:15.365000Z], version: nil}}, %TeslaMate.Vehicles.Vehicle.Data{car: %TeslaMate.Log.Car{__meta__: #Ecto.Schema.Metadata<:loaded, "cars">, charging_processes: #Ecto.Association.NotLoaded<association :charging_processes is not loaded>, drives: #Ecto.Association.NotLoaded<association :drives is not loaded>, efficiency: nil, eid: #, exterior_color: "DeepBlue", friendly_name: nil, id: 1, inserted_at: ~N[2021-11-18 09:37:14], model: "3", name: "Sonic", positions: #Ecto.Association.NotLoaded<association :positions is not loaded>, settings: %TeslaMate.Settings.CarSettings{__meta__: #Ecto.Schema.Metadata<:loaded, "car_settings">, car: #Ecto.Association.NotLoaded<association :car is not loaded>, free_supercharging: false, id: 1, req_not_unlocked: false, suspend_after_idle_min: 15, suspend_min: 21, use_streaming_api: true}, settings_id: 1, spoiler_type: "Passive", trim_badging: "P74D", updated_at: ~N[2021-11-18 17:30:39], vid: 1986078119, vin: "#", wheel_type: "Stiletto19"}, deps: %{api: TeslaMate.Api, locations: TeslaMate.Locations, log: TeslaMate.Log, pubsub: Phoenix.PubSub, settings: TeslaMate.Settings, vehicles: TeslaMate.Vehicles}, elevation: nil, geofence: nil, import?: false, last_response: %TeslaApi.Vehicle{api_version: 28, backseat_token: nil, backseat_token_updated_at: nil, calendar_enabled: true, charge_state: %TeslaApi.Vehicle.State.Charge{max_range_charge_counter: 0, charge_limit_soc_std: 90, scheduled_charging_start_time: nil, time_to_full_charge: 0.0, conn_charge_cable: "SAE", charger_power: 0, charge_limit_soc: 90, fast_charger_present: false, managed_charging_active: false, charge_limit_soc_max: 100, charger_pilot_current: 12, charge_to_max_range: false, trip_charging: false, charge_enable_request: true, charge_miles_added_rated: 21.0, charge_port_door_open: true, not_enough_power_to_heat: nil, est_battery_range: 198.11, charge_current_request_max: 12, charge_limit_soc_min: 50, fast_charger_brand: "<invalid>", charge_port_cold_weather_mode: false, ideal_battery_range: 237.55, charge_port_latch: "Engaged", managed_charging_user_canceled: false, timestamp: 1637661586159, battery_heater_on: false, managed_charging_start_time: nil, charge_rate: 0.0, charge_energy_added: 5.34, charge_current_request: 12, battery_range: 237.55, charger_phases: 1, usable_battery_level: 89, user_charge_enable_request: nil, charging_state: "Complete", battery_level: 90, charge_miles_added_ideal: 21.0, scheduled_charging_pending: false, ...}, climate_state: %TeslaApi.Vehicle.State.Climate{battery_heater: false, battery_heater_no_power: nil, climate_keeper_mode: "off", defrost_mode: 0, driver_temp_setting: 19.4, fan_status: 0, inside_temp: 8.5, is_auto_conditioning_on: false, is_climate_on: false, is_front_defroster_on: false, is_preconditioning: false, is_rear_defroster_on: false, left_temp_direction: 0, max_avail_temp: 28.0, min_avail_temp: 15.0, outside_temp: 7.5, passenger_temp_setting: 19.4, remote_heater_control_enabled: false, right_temp_direction: 0, seat_heater_left: 0, seat_heater_rear_center: 0, seat_heater_rear_left: 0, seat_heater_rear_left_back: nil, seat_heater_rear_right: 0, seat_heater_rear_right_back: nil, (truncated)
teslamate_1  |  2021-11-23 11:00:02.105 car_id=1 [info] Start / :asleep
teslamate_1  |  2021-11-23 11:01:22.806 car_id=1 [info] Start / :offline
teslamate_1  |  2021-11-23 11:02:13.241 car_id=1 [info] Start / :asleep
teslamate_1  |  2021-11-23 11:02:56.128 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/1492930949889702/vehicle_data -> 540 (2599.585 ms)
teslamate_1  |  2021-11-23 11:02:56.128 [warn] TeslaApi.Error / vehicle error: it is online but not responsive
teslamate_1  |  2021-11-23 11:02:56.128 car_id=1 [error] Error / :unknown
teslamate_1  |  2021-11-23 11:04:26.954 car_id=1 [info] Start / :online
teslamate_1  |  2021-11-23 11:04:26.961 car_id=1 [info] Connecting ...
teslamate_1  |  2021-11-23 11:07:29.020 car_id=1 [info] Suspending logging
teslamate_1  |  2021-11-23 11:07:29.089 car_id=1 [warn] Received stale stream data: %TeslaApi.Stream.Data{elevation: 104, est_heading: #, est_lat: #, est_lng: #, est_range: 198, heading: 74, odometer: 10216.5, power: 0, range: 238, shift_state: nil, soc: 90, speed: nil, time: ~U[2021-11-23 10:07:28.422Z]}
teslamate_1  |  2021-11-23 11:17:29.658 car_id=1 [info] Charging detected: -1 kW
teslamate_1  |  2021-11-23 11:17:30.536 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (309.592 ms)
teslamate_1  |  2021-11-23 11:17:30.543 car_id=1 [info] Charging / SOC: 90%
teslamate_1  |  2021-11-23 11:17:30.543 car_id=1 [info] Disconnecting ...
teslamate_1  |  2021-11-23 11:18:57.423 car_id=1 [warn] Vehicle went offline while charging
teslamate_1  |  2021-11-23 11:19:07.963 car_id=1 [warn] Vehicle went offline while charging
teslamate_1  |  2021-11-23 11:20:19.466 car_id=1 [warn] Vehicle went offline while charging
teslamate_1  |  2021-11-23 11:28:18.814 car_id=1 [info] Derived efficiency factor: 159.0 Wh/km (4x confirmed)
teslamate_1  |  2021-11-23 11:28:18.815 car_id=1 [info] Charging / Complete / 0.11 kWh – 11 min
teslamate_1  |  2021-11-23 11:28:18.817 car_id=1 [info] Start / :online
teslamate_1  |  2021-11-23 11:28:18.822 car_id=1 [info] Connecting ...
teslamate_1  |  2021-11-23 11:29:05.181 [info] GET /
teslamate_1  |  2021-11-23 11:29:05.185 [info] Sent 200 in 4ms
teslamate_1  |  2021-11-23 11:29:12.149 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  |  2021-11-23 11:59:12.869 car_id=1 [info] Vehicle is still online. Falling asleep for: 30 min
teslamate_1  |  2021-11-23 12:04:01.183 car_id=1 [info] Fetching vehicle state ...
teslamate_1  |  2021-11-23 12:04:01.349 car_id=1 [info] Start / :asleep
teslamate_1  |  2021-11-23 12:04:01.354 car_id=1 [info] Disconnecting ...
teslamate_1  |  2021-11-23 14:10:26.492 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492930949889702 -> error: "timeout" (35000.971 ms)
teslamate_1  |  2021-11-23 14:10:26.492 [warn] TeslaApi.Error / timeout
teslamate_1  |  2021-11-23 14:10:26.492 car_id=1 [error] Error / :unknown
teslamate_1  |  2021-11-23 14:12:03.917 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492930949889702 -> error: "timeout" (35000.871 ms)
teslamate_1  |  2021-11-23 14:12:03.917 [warn] TeslaApi.Error / timeout
teslamate_1  |  2021-11-23 14:12:03.917 car_id=1 [error] Error / :unknown
teslamate_1  |  2021-11-23 14:30:27.427 [info] GET /
teslamate_1  |  2021-11-23 14:30:27.430 [info] Sent 200 in 3ms
teslamate_1  |  2021-11-23 14:50:55.114 [info] Refreshing access token ...
teslamate_1  |  2021-11-23 14:50:55.376 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (261.389 ms)
teslamate_1  |  2021-11-23 14:50:55.379 [info] Scheduling token refresh in 6 h
```

```
IRRELEVANT LOG - see update 11/27/2021 above

teslamate_1  | 2021-11-23 04:51:59.797 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-11-23 04:51:59.801 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-23 04:52:40.414 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-23 04:52:40.421 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-23 04:53:36.942 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-11-23 04:53:36.946 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-23 04:54:17.655 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-23 04:54:17.662 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-23 04:55:13.909 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-11-23 04:55:13.913 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-23 04:55:54.601 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-23 04:55:54.607 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-23 04:56:51.185 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-11-23 04:56:51.190 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-23 04:57:31.844 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-23 04:57:31.851 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-23 04:58:33.454 car_id=1 [info] Received stream data: %TeslaApi.Stream.Data{elevation: 104, est_heading: 79, est_lat: #, est_lng: #, est_range: 181, heading: 79, odometer: 10216.5, power: 1, range: 217, shift_state: nil, soc: 82, speed: nil, time: ~U[2021-11-23 03:58:33.309Z]}
teslamate_1  | 2021-11-23 04:58:43.457 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-11-23 04:58:43.461 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-23 04:59:24.221 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-23 04:59:24.229 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-23 05:00:17.309 car_id=1 [info] Received stream data: %TeslaApi.Stream.Data{elevation: 104, est_heading: 79, est_lat: ##, est_lng: -##, est_range: 181, heading: 79, odometer: 10216.5, power: 1, range: 217, shift_state: nil, soc: 82, speed: nil, time: ~U[2021-11-23 04:00:16.700Z]}
```

### Screenshots

![tm1](https://user-images.githubusercontent.com/38891125/143326612-0e505cf7-b00d-4d4c-8f6a-4cb36b4a6bc6.jpg)

![tm2](https://user-images.githubusercontent.com/38891125/143326613-79086137-0c97-4b26-b493-3c0278a7de65.jpg)

![tm3](https://user-images.githubusercontent.com/38891125/143326611-bdda0ae6-9383-465e-b0ad-046232d1c468.jpg)

![tm4](https://user-images.githubusercontent.com/38891125/143328585-4b7ebfe1-cfb8-471e-b036-2dadad76c08b.jpg)

### Type of installation

Docker

### Version

1.25.0

**Comment by DrMichael** [comment]
What gives

```
select split_part(version, ' ', 1) as version 
from updates 
where car_id = '1' 
order by start_date desc 
limit 1
```
?

**Comment by hoang51** [comment]
Hi @DrMichael,

So a Google search shows that this appears to be SQL related. I'm not entirely versed in SQL nor Docker-Compose. Can you please elaborate what steps need to be taken so that I can get the requested result? It looks like I need to issue some docker-compose commands via SSH, but that's where I haven't found the exact answer. Thanks. :)

**Comment by manuelkamp** [comment]
> It looks like I need to issue some docker-compose commands via SSH

indeed: docker-compose exec database psql teslamate teslamate

then you are able to do this sql query

**Comment by DrMichael** [comment]
Oh, don't forget the ";" at the end...

**Comment by manuelkamp** [comment]
> Oh, don't forget the ";" at the end...

...of the sql query: LIMIT 1**;**

**Comment by hoang51** [comment]
@DrMichael & @manuelkamp , thank you both for your help. I didn't have enough time to figure out how to finish the execution. As for the output of the requested commands, this is what it outputted:

```
 version 
---------
 
(1 row)
```

**Comment by DrMichael** [comment]
Mach mal einfacher:

`select version from updates order by start_date desc;
`

**Comment by hoang51** [comment]
Here is the output for that @DrMichael :

```
         version          
--------------------------
 
 
 2021.36.8.5 0126c45b1ab7
(3 rows)
```

**Comment by DrMichael** [comment]
Hmmm, why are there empty versions? Then let's have a complete one:

`select * from updates order by start_date desc;
`ANd you got only one firmware update so far?

**Comment by hoang51** [comment]
I have no idea why the update 2021.36.8.8 was never recorded properly and making two blank entries. I only had one firmware update (to 2021.36.8.8) from 2021.36.8.5 since I've recently installed Teslamate. This is the output:

```
 id |       start_date        |        end_date         |         version          | car_id 
----+-------------------------+-------------------------+--------------------------+--------
  3 | 2021-11-23 09:59:15.365 |                         |                          |      1
  2 | 2021-11-23 09:52:56.671 |                         |                          |      1
  1 | 2021-11-18 17:30:38.843 | 2021-11-18 17:30:38.843 | 2021.36.8.5 0126c45b1ab7 |      1
(3 rows)
```

**Comment by hoang51** [comment]
@DrMichael and others, I have recently updated the original issue with the relevant log output. I was able to find the update process in the log and there appears to be an error for each logged update (at 9:52 and 9:59):

```
teslamate_1  |  ** (FunctionClauseError) no function clause matching in TeslaMate.Vehicles.Vehicle.handle_event/4
```
Further inspection of the log does show that 2021.36.8.8 is acknowledged, but not sure why it was never recorded.

**Comment by manuelkamp** [comment]
Ok, first make a backup of your DB in case anything went wrong and you need to revert. Then execute the follwoing commands one per one (each line is one command):

DELETE FROM updates WHERE id=3;
UPDATE updates SET end_date='2021-11-23 09:59:15.365', version='2021.36.8.8 43e7bf2619' WHERE id=2;

As far as I am aware, for Postgres we do not need to modify the autoincrement value of the id-column - please correct me if I am wrong.

If now the Update shows up correct, you should be fine.

**Comment by hoang51** [comment]
@manuelkamp , I get the following error with the last command line you provided:

> teslamate=# ALTER SEQUENCE updates _id_seq RESTART WITH 3;
> ERROR:  syntax error at or near "_id_seq"
> LINE 1: ALTER SEQUENCE updates _id_seq RESTART WITH 3;
>                                ^

**Comment by hoang51** [comment]
Given my nature of trying to resolve computer problems, the solution was simple, but took time to figure it out since I'm not versed in SQL related tasks:

> ALTER SEQUENCE updates _id_seq RESTART WITH 3;

should be...

> ALTER SEQUENCE updates_id_seq RESTART WITH 3;

I had to rely on Google to find [how to pull a list of sequences](https://stackoverflow.com/questions/1493262/list-all-sequences-in-a-postgres-db-8-1-with-sql) (second answer down with a single line command) and noticed that it was updates_id_seq that is being targeted. Problem solved.

As for what it did to the database to fix the problem, I now see what appears to be correct. Now to see if the database will take the next update correctly. Thanks for your help @manuelkamp and @DrMichael .

As for the error:

> teslamate_1  |  ** (FunctionClauseError) no function clause matching in TeslaMate.Vehicles.Vehicle.handle_event/4

What to make of it? Something to alert Adrian on?

**Comment by hoang51** [comment]
An update finally came. I did not experience any glitch that happened to the previous update when my Model 3 updated to 2021.44.25.6 (FSD Beta 10.8). So I will close this issue out. Thanks for all the help.
