### ISSUE TITLE
Cannot login to TeslaMate (running on Synology NAS)

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#220]
So, this is not new, and have been having issues on Synology since they broke this a while back and haven't had a chance to go back to it until now. I cleaned up everything - removed all images, containers, volumes, etc - deleted Synology, rebooted and added everything back as a fresh docker compose and I see the same issue. Essentially the first time I get to Teslamate page (on port 4000), and enter the tesla credentials, those don't get saved and it keeps showing the same page again and again. 

Here is what I see in the log and I am not sure what is the issue. This is running fine on a pi on the same network so clearly it has something to do with synology or that host, but I don't know what.

Curious is anyone else saw and solved this?

```
2019-10-25 21:55:36,stdout,"Last message: %Phoenix.Socket.Message{event: \"event\", join_ref: \"292\", payload: %{\"event\" => \"save\", \"type\" => \"form\", \"value\" => \"_csrf_token=RETRACTED&_utf8=%E2%9C%93&credentials%5Bemail%5D=RETRACTED&credentials%5Bpassword%5D=RETRACTED\"}, ref: \"311\", topic: \"lv:phx-3h4K4MBh\"}"
2019-10-25 21:55:36,stdout,    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2019-10-25 21:55:36,stdout,    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
2019-10-25 21:55:36,stdout,    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
2019-10-25 21:55:36,stdout,    (phoenix_live_view) lib/phoenix_live_view/channel.ex:81: Phoenix.LiveView.Channel.handle_info/2
2019-10-25 21:55:36,stdout,    (teslamate) lib/teslamate_web/live/signin_live/index.ex:40: TeslaMateWeb.SignInLive.Index.handle_event/3
2019-10-25 21:55:36,stdout,    (elixir) lib/gen_server.ex:1009: GenServer.call/3
2019-10-25 21:55:36,stdout,    ** (EXIT) time out
2019-10-25 21:55:36,stdout,"** (stop) exited in: GenServer.call(TeslaMate.Api, {:sign_in, %TeslaMate.Auth.Credentials{__meta__: #Ecto.Schema.Metadata<:built, \"\">, email: \"RETRACTED\", id: nil, password: \"RETRACTED\"}}, 5000)"
2019-10-25 21:55:36,stdout,14:55:36.224 [error] GenServer #PID<0.3682.0> terminating
```

Line 40 that is outlined in index.ex is the actual call to the API to sign-in
https://github.com/adriankumpf/teslamate/blob/6bb171f5e224e349f8deb3f55230c9210e6be315/lib/teslamate_web/live/signin_live/index.ex#L40

And I can validate the credentials are correct. Appreciate any insight.

Thanks.

**Comment by adriankumpf** [comment]
The reported timeout indicates that the TeslaMate API process was busy. Possible causes could be a connection or DNS problem. The log should provide more information.

**Comment by snjoetw** [comment]
fwiw I just installed Teslamate on my Synology NAS using docker compose and it runs fine
