### ISSUE TITLE
Restore fails when backup is older than 11/12/2021

### ISSUE THREAD

**Issue by henroFall** [adriankumpf/teslamate#2290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have an automatic backup routine that failed, and it made its last backup on 11/11. I'm not sure if the upgrade on 11/12 broke me, or if I broke myself, but that is my last backup.
When attempting to restore it into the latest build, I get 
`ERROR:  missing data for column "est_battery_range_km"`
When teslamate starts, I get the further errors about the CARS table as seen below. 

I cannot restore my data.

If I could pull the image down from 11/11 then I would be able to restore my data into it, and then upgrade, right? Or else fix teslamate to tolerate older data restorations?

### Expected Behavior

I had hoped that Teslamate would be able to restore my data

### Steps To Reproduce

Use your backup script (what drops schemas and creates functions) on a backup from 11/11 or earlier. 

### Relevant log output

```shell
teslamate_1  | 2022-01-09 16:33:22.221 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate_1  | 2022-01-09 16:33:22.224 [info] create table cars
database_1   | 2022-01-09 16:33:22.226 UTC [35] ERROR:  relation "cars" already exists
database_1   | 2022-01-09 16:33:22.226 UTC [35] STATEMENT:  CREATE TABLE "cars" ("id" bigserial, "eid" bigint NOT NULL, "vid" bigint NOT NULL, "model" varchar(255) NOT NULL, "efficiency" float NOT NULL, "inserted_at" timestamp(0) NOT NULL, "updated_at" timestamp(0) NOT NULL, PRIMARY KEY ("id"))
teslamate_1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
teslamate_1  | 2022-01-09 16:33:26.187 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate_1  | 2022-01-09 16:33:26.190 [info] create table cars
database_1   | 2022-01-09 16:33:26.192 UTC [38] ERROR:  relation "cars" already exists
database_1   | 2022-01-09 16:33:26.192 UTC [38] STATEMENT:  CREATE TABLE "cars" ("id" bigserial, "eid" bigint NOT NULL, "vid" bigint NOT NULL, "model" varchar(255) NOT NULL, "efficiency" float NOT NULL, "inserted_at" timestamp(0) NOT NULL, "updated_at" timestamp(0) NOT NULL, PRIMARY KEY ("id"))
teslamate_1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
teslamate_teslamate_1 exited with code 1
teslamate_1  | 2022-01-09 16:33:30.334 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate_1  | 2022-01-09 16:33:30.337 [info] create table cars
database_1   | 2022-01-09 16:33:30.338 UTC [41] ERROR:  relation "cars" already exists
database_1   | 2022-01-09 16:33:30.338 UTC [41] STATEMENT:  CREATE TABLE "cars" ("id" bigserial, "eid" bigint NOT NULL, "vid" bigint NOT NULL, "model" varchar(255) NOT NULL, "efficiency" float NOT NULL, "inserted_at" timestamp(0) NOT NULL, "updated_at" timestamp(0) NOT NULL, PRIMARY KEY ("id"))
teslamate_1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
teslamate_teslamate_1 exited with code 1
```

### Type of installation

Docker

### Version

1.25

**Comment by henroFall** [comment]
I'm not sure that the subject line is my actual issue now. I found how to pull old images and still  get the error. I will move this to discussions.
