### ISSUE TITLE
Token validation error result in incomplete and split drives

### ISSUE THREAD

**Issue by cybe** [adriankumpf/teslamate#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

An ongoing drive was terminated uncleanly and a new drive was started after a token validation error occurred. That split the drive into two with the first one being incomplete. IDs 977 and 976 from top to bottom.

![image](https://user-images.githubusercontent.com/713548/154123320-e79910ca-cccf-4b40-9460-60a8408e8cab.png)

The database shows this as follows:
```
teslamate=# select id,start_date,end_date,start_position_id,end_position_id,start_geofence_id,end_geofence_id from drives where id >= 975 and id < 978;

 id  |         start_date         |        end_date         | start_position_id | end_position_id | start_geofence_id | end_geofence_id
-----+----------------------------+-------------------------+-------------------+-----------------+-------------------+-----------------
 976 | 2022-02-14 11:32:23.538796 |                         |                   |                 |                   |
 977 | 2022-02-14 14:28:33.23     | 2022-02-14 15:20:56.728 |           2175449 |         2183661 |                   |
```
ID 975 is missing, if that is relevant.

The attached log output shows the validation error and the start of a new drive. While leaving the previous drive incomplete. The whole trip (i.e the positions) however seems complete. If needed I could provide the exact positions.

Would this be manually fixable, by the way?

### Expected Behavior

Even a one time token validation error should keep an ongoing drive intact. 

### Relevant log output

```shell
2022-02-14 12:32:23.537 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 5, est_heading: 72, est_lat: 53.5xxxxx, est_lng: 10.0xxxxx, est_range: 274, heading: 70, odometer: 1101
7.6, power: 1, range: 358, shift_state: "D", soc: 100, speed: 0, time: ~U[2022-02-14 11:32:23.461Z]}
2022-02-14 12:32:23.537 car_id=1 [info] Driving / Start

2022-02-14 15:28:32.114 [error] ** (RuntimeError) Client Error: %{"error_type" => "client_error", "msg_type" => "data:error", "tag" => "214275939478", "value" => "Can't validate token. "}
    (teslamate 1.26.1) lib/tesla_api/stream.ex:165: TeslaApi.Stream.handle_frame/2
    (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3
    (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

2022-02-14 15:28:33.369 car_id=1 [info] Start / :online
2022-02-14 15:28:33.378 car_id=1 [info] Connecting ...
2022-02-14 15:28:33.379 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1644848911, heading: 149, latitude: 51.704026, longitude: 10.280268, native_latitude: 51.704026
, native_location_supported: 1, native_longitude: 10.280268, native_type: "wgs", power: 24, shift_state: "D", speed: 62, timestamp: 1644848913230}

2022-02-14 16:20:59.081 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1644852055, heading: 117, latitude: 51.450594, longitude: 11.304512, native_latitude: 51.450594,
native_location_supported: 1, native_longitude: 11.304512, native_type: "wgs", power: 3, shift_state: "P", speed: 0, timestamp: 1644852056728}
2022-02-14 16:20:59.081 car_id=1 [info] Driving / Ended / 86 km – 52 min

```
```


### Screenshots

_No response_

### Additional data

_No response_

### Type of installation

Docker

### Version

v1.26.1

**Comment by init6-git** [comment]
That's very similar to #2450. 
I get the same error.

**Comment by cybe** [comment]
> That's very similar to #2450.
> I get the same error.

This seems indeed to be the same issue. My bad for not finding it.
