### ISSUE TITLE
Cannot enter total cost that over 10000 

### ISSUE THREAD

**Issue by dongbum** [adriankumpf/teslamate#2523]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I set total cost over 10000.
And can't enter total cost.

Page is refreshed and input box is blank.

### Steps To Reproduce

1. Go to a charge session
2. Click on "cost" to set the cost
3. Enter total cost that over 10000
4. Page is refreshed and cost box is blank.

### Relevant log output

```shell
teslamate_1            | A field with precision 6, scale 2 must round to an absolute value less than 10^4.
teslamate_1            |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1            |     (teslamate 1.26.1) lib/teslamate_web/live/charge_live/cost.ex:85: TeslaMateWeb.ChargeLive.Cost.handle_event/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
teslamate_1            |     (telemetry 1.0.0) /opt/app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
teslamate_1            |     (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
teslamate_1            | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"event" => "save", "type" => "form", "value" => "_method=put&_csrf_token=KUUxAQsqNQw9QlBJPQsFEBIMNFIYVhdwm0iXobP8K859uHquFvFbW1S9&charging_process%5Bmode%5D=total&charging_process%5Bcost%5D=10000"}, ref: "5", topic: "lv:phx-FtnRTKSO2amSz1Hh"}
teslamate_1            | 2022-03-06 14:36:37.661 [info] GET /charge-cost/286
teslamate_1            | 2022-03-06 14:36:37.670 [info] Sent 200 in 8ms
teslamate_1            | 2022-03-06 14:41:05.846 [error] GenServer #PID<0.25872.5> terminating
teslamate_1            | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) numeric field overflow
teslamate_1            |
teslamate_1            | A field with precision 6, scale 2 must round to an absolute value less than 10^4.
teslamate_1            |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1            |     (teslamate 1.26.1) lib/teslamate_web/live/charge_live/cost.ex:85: TeslaMateWeb.ChargeLive.Cost.handle_event/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
teslamate_1            |     (telemetry 1.0.0) /opt/app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
teslamate_1            |     (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
teslamate_1            | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"event" => "save", "type" => "form", "value" => "_method=put&_csrf_token=JTk8FAwxK1A6EjMEGwwdCyRJBgR2DXYFaLdMhyNdLhVtSOinp3t49j2L&charging_process%5Bmode%5D=total&charging_process%5Bcost%5D=10000"}, ref: "13", topic: "lv:phx-FtnRa1MDGTTv2VKh"}
teslamate_1            | 2022-03-06 14:41:22.370 [error] GenServer #PID<0.25954.5> terminating
teslamate_1            | ** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) numeric field overflow
teslamate_1            |
teslamate_1            | A field with precision 6, scale 2 must round to an absolute value less than 10^4.
teslamate_1            |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
teslamate_1            |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1            |     (teslamate 1.26.1) lib/teslamate_web/live/charge_live/cost.ex:85: TeslaMateWeb.ChargeLive.Cost.handle_event/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
teslamate_1            |     (telemetry 1.0.0) /opt/app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
teslamate_1            |     (phoenix_live_view 0.17.5) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
teslamate_1            |     (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
teslamate_1            | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "14", payload: %{"event" => "save", "type" => "form", "value" => "_method=put&_csrf_token=JkQfaFQ9ElAONz0qGAs1NxslJAcnBiB9b1G10uwdxMXZPHARO_V7had4&charging_process%5Bmode%5D=total&charging_process%5Bcost%5D=10000"}, ref: "16", topic: "lv:phx-FtnRa1MDGTTv2VKh"}
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by adriankumpf** [comment]
Related to #1064. Let's track it there.

**Comment by dongbum** [comment]
@adriankumpf  Solved!

I found solution in #1064 reply at @olivercho

And it works perfectly.
