### ISSUE TITLE
1.26.1 compile fails

### ISSUE THREAD

**Issue by markusdd** [adriankumpf/teslamate#2624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I tried to upgrade my 1.25 install to 1.26.1 I ran into the following at the end:

```
Generating TeslaMateWeb.Cldr for 16 locales named ["da", "de", "en", "es", "fi", ...] with a default locale named "en"
Generated teslamate app

20:01:06.568 [notice] Application mime exited: exited in: MIME.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function MIME.Application.start/2 is undefined (module MIME.Application is not available)
            (mime 1.6.0) MIME.Application.start(:normal, [])
            (kernel 8.1.3) application_master.erl:293: :application_master.start_it_old/4

20:01:06.579 [notice] Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:mime, {:bad_return, {{MIME.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{MIME.Application, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 293]}]}}}}}}
    (phoenix 1.6.5) lib/mix/tasks/phx.digest.ex:56: Mix.Tasks.Phx.Digest.run/1
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2

```

### Expected Behavior

compilation and release succeeds

### Steps To Reproduce

Run ` MIX_ENV=prod mix do phx.digest, release --overwrite` on a 1.25 install.

### Relevant log output

```shell
see above
```

### Type of installation

Manual

### Version

v1.26.1

**Comment by markusdd** [comment]
please disregard,

it turned out to be an issue with the telemetry module which I needed to completely remove and recompile. This made it pass.
