### ISSUE TITLE
Grafana on RPI dies horribly...

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#2654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Grafana:edge is restarting because it is constantly crashing on my RPI3+. It runs well under normal Ubuntu on another machine.
It also runs fine with grafana:latest.

### Expected Behavior

Start and run smoothly.

### Relevant log output

```shell
...
grafana_1    | runtime.(*mcache).refill(0x0, 0x0)
grafana_1    |  /usr/local/go/src/runtime/mcache.go:185 +0x154 fp=0x589bca4 sp=0x589bc74 pc=0x26f28
grafana_1    |
grafana_1    | goroutine 115 [select]:
grafana_1    | go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0x50dccc0)
grafana_1    |  /opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:243 +0xf4
grafana_1    | go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1(0x50dccc0)
grafana_1    |  /opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:111 +0x4c
grafana_1    | created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
grafana_1    |  /opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:109 +0x1e8
grafana_1    |
grafana_1    | goroutine 94 [select]:
grafana_1    | go.opencensus.io/stats/view.(*worker).start(0x5220ba0)
grafana_1    |  /opt/drone/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xa0
grafana_1    | created by go.opencensus.io/stats/view.init.0
grafana_1    |  /opt/drone/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x64
grafana_1    |
grafana_1    | goroutine 137 [chan receive]:
grafana_1    | github.com/golang/glog.(*loggingT).flushDaemon(0x4599698)
grafana_1    |  /opt/drone/gomodcache/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x70
grafana_1    | created by github.com/golang/glog.init.0
grafana_1    |  /opt/drone/gomodcache/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x214
```

### Type of installation

Docker

### Version

1.27.0-dev

**Comment by leewillis77** [comment]
Related? https://github.com/grafana/grafana/issues/48130

**Comment by DrMichael** [comment]
Could be. @adriankumpf Could we upgrade from 8.5.0 to 8.5.1 in edge?

**Comment by DrMichael** [comment]
Right, runs fine with 8.5.3...
