### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by bigjools** [adriankumpf/teslamate#294]
Hi, new user here. I set up with the basic and advanced docker-compose files and get the same result, the sign in page spins and returns back to the same page. The log contains this

```
teslamate_1  | 11:51:35.074 [error] GenServer #PID<0.3858.0> terminating
teslamate_1  | ** (stop) exited in: GenServer.call(TeslaMate.Api, {:sign_in, %TeslaMate.Auth.Credentials{__meta__: #Ecto.Schema.Metadata<:built, "">, email: "REDACTED@gmail.com", id: nil, password: "REDACTED"}}, 5000)
teslamate_1  |     ** (EXIT) time out
teslamate_1  |     (elixir) lib/gen_server.ex:1009: GenServer.call/3
teslamate_1  |     (teslamate) lib/teslamate_web/live/signin_live/index.ex:40: TeslaMateWeb.SignInLive.Index.handle_event/3
teslamate_1  |     (phoenix_live_view) lib/phoenix_live_view/channel.ex:89: Phoenix.LiveView.Channel.handle_info/2
teslamate_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "37", payload: %{"event" => "save", "type" => "form", "value" => "_csrf_token=K10OGAwfEkFZIg4oOhIcdAIqeFgEQzslslJS8hXs7TBGRzuAriJawwcv&_utf8=%E2%9C%93&credentials%5Bemail%5D=REDACTED%40gmail.com&credentials%5Bpassword%5D=REDACTED"}, ref: "51", topic: "lv:phx-IjhDNdPf"}
```

The proxy service is also failing to contact letsencrypt
```
proxy_1      | time="2019-12-05T11:43:06Z" level=error msg="Unable to obtain ACME certificate for domains \"REDACTED\": cannot get ACME client get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get https://acme-v02.api.letsencrypt.org/directory: net/http: TLS handshake timeout" providerName=tmhttpchallenge.acme routerName=teslamate rule="Host(`REDACTED`)"
```

It seems like it can't talk to these couple of places but I can exec a wget in the container and reach other places so I am at a loss. Any help is appreciated.

**Comment by bigjools** [comment]
I did some digging and found an MTU mismatch on the host vs the docker bridge. Fixing that now enables me to get wget working in the proxy container, however the teslamate processes still time out. The response to wget is quite slow from the letsencrypt site.Can the teslamate timeout be raised?
