### ISSUE TITLE
ArithmeticError when suspending logging

### ISSUE THREAD

**Issue by bigjools** [adriankumpf/teslamate#296]
**Describe the bug**
It's impossible to put the car to sleep as the logging will not stop. Whether it's automatic, or manually triggered, it fails with ArithmeticError in the log. (See below)

**To Reproduce**
This is a brand new installation. Manually hitting "try to sleep" in the web UI will trigger this.

**Expected behavior**
A sleeping car!

**Relevant entries from the logs**
```
teslamate_1  | 00:18:27.339 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 00:18:27.343 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (ArithmeticError) bad argument in arithmetic expression
teslamate_1  |     :erlang.*(nil, 60000)
teslamate_1  |     (stdlib) timer.erl:225: :timer.minutes/1
teslamate_1  |     (teslamate) lib/teslamate/vehicles/vehicle.ex:928: TeslaMate.Vehicles.Vehicle.schedule_fetch/2
teslamate_1  |     (teslamate) lib/teslamate/vehicles/vehicle.ex:212: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | 00:18:27.347 [error] GenServer #PID<0.9969.0> terminating
teslamate_1  | ** (stop) exited in: :gen_statem.call(:"1", :suspend_logging, :infinity)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (ArithmeticError) bad argument in arithmetic expression
teslamate_1  |             :erlang.*(nil, 60000)
teslamate_1  |             (stdlib) timer.erl:225: :timer.minutes/1
teslamate_1  |             (teslamate) lib/teslamate/vehicles/vehicle.ex:928: TeslaMate.Vehicles.Vehicle.schedule_fetch/2
teslamate_1  |             (teslamate) lib/teslamate/vehicles/vehicle.ex:212: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |             (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
teslamate_1  |             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  |     (stdlib) gen.erl:177: :gen.do_call/4
teslamate_1  |     (stdlib) gen_statem.erl:619: :gen_statem.call_dirty/4
teslamate_1  |     (teslamate) lib/teslamate_web/live/car_live/summary.ex:61: TeslaMateWeb.CarLive.Summary.handle_info/2
teslamate_1  |     (phoenix_live_view) lib/phoenix_live_view/channel.ex:106: Phoenix.LiveView.Channel.handle_info/2
teslamate_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: :suspend_logging

```

**Screenshots**

**Operating environment (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.04 server

**Comment by adriankumpf** [comment]
Thank you for the detailed report. The fix will ship with the next release. In the meantime, restarting Teslamate also works.

**Comment by bigjools** [comment]
Confirmed that works, thank you.
