### ISSUE TITLE
Browsing to /settings  in WebUI gives 500 error

### ISSUE THREAD

**Issue by SDekkers** [adriankumpf/teslamate#3032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Browsing to the settings page gives an HTTP-500 error.

### Expected Behavior

Settings page shows

### Relevant log output

```shell
Request: GET /settings
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined
        nil.id()
        (teslamate 1.27.1) lib/teslamate_web/live/settings_live/index.ex:183: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (teslamate 1.27.1) lib/teslamate_web/live/settings_live/index.ex:15: TeslaMateWeb.SettingsLive.Index.mount/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.1.0) /opt/app/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:270: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by dyxyl** [comment]
Maybe the database contains some spurious data?  What is the output of the following SQL commands?
```
select * from car_settings;
select id, settings_id, inserted_at, updated_at from cars;
```

**Comment by natrlhy** [comment]
When going to the settings page I also get an `Internal Server Error` message and can't view the settings, I tried doing some things mentioned in https://github.com/adriankumpf/teslamate/discussions/2110 and the `apt update;apt upgrade` commands didn't fix things. I get a similar message as @SDekkers mentioned above:

Here's some output:
```
teslamate_1  | Request: GET /settings
teslamate_1  | ** (exit) an exception was raised:
teslamate_1  |     ** (UndefinedFunctionError) function nil.id/0 is undefined
teslamate_1  |         nil.id()
teslamate_1  |         (teslamate 1.27.2) lib/teslamate_web/live/settings_live/index.ex:183: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
teslamate_1  |         (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |         (teslamate 1.27.2) lib/teslamate_web/live/settings_live/index.ex:15: TeslaMateWeb.SettingsLive.Index.mount/3
teslamate_1  |         (phoenix_live_view 0.17.12) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
teslamate_1  |         (telemetry 1.2.1) /opt/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
teslamate_1  |         (phoenix_live_view 0.17.12) lib/phoenix_live_view/static.ex:270: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
teslamate_1  |         (phoenix_live_view 0.17.12) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
^CERROR: Aborting.
root@teslamate:~/docker/teslamate# docker-compose exec database psql teslamate teslamate
psql (14.6 (Debian 14.6-1.pgdg110+1))
Type "help" for help.

teslamate=# select * from car_settings;
 id | suspend_min | suspend_after_idle_min | req_not_unlocked | free_supercharging | use_streaming_api
----+-------------+------------------------+------------------+--------------------+-------------------
  1 |          12 |                     10 | f                | f                  | t
  2 |          21 |                     15 | f                | f                  | t
  3 |          21 |                     15 | f                | f                  | t
  4 |          21 |                     15 | f                | f                  | t
(4 rows)

teslamate=# select id, settings_id, inserted_at, updated_at from cars;
 id | settings_id |     inserted_at     |     updated_at
----+-------------+---------------------+---------------------
  5 |           2 | 2022-02-06 20:58:30 | 2022-12-25 23:51:38
  1 |           1 | 2019-08-06 00:01:00 | 2022-12-29 03:32:05
```

I'm not sure if this stems from `id_settings` 3 and 4 not being tied to another car as I have 2 on my account. I've had a few loaner cars but have removed the data from the database`. Is more cleanup needed?

**Comment by natrlhy** [comment]
Ok figured it out. Since it wasn't a 1:1 mapping of the `car_settings` ID I just had to run:
`DELETE FROM car_settings WHERE id = 3;`
`DELETE FROM car_settings WHERE id = 4;`

I can now see my settings page again!

**Comment by SDekkers** [comment]
@natrlhy this also worked for me! Thanks!
