### ISSUE TITLE
Key error when migrating to v1.14.0

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#317]
Hi,
I was on  1.13.2 and upgrading to v1.14.0 I get the following error. Saw this at the end of the day when I noticed the charging wasn't showing up. Any ideas on what I need to update? Looks liek it can't find a end date in the migration script. For now thinking should I downgrade?

Thanks.

```
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:26:49.594 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:26:49.669 [info] Phase correction: 2 -> 1,
22:26:49.736 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:26:59.393 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:26:59.469 [info] Phase correction: 2 -> 1,
22:26:59.538 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:27:10.599 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:27:10.677 [info] Phase correction: 2 -> 1,
22:27:10.746 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:27:24.819 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:27:24.892 [info] Phase correction: 2 -> 1,
22:27:24.962 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:27:45.465 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:27:45.541 [info] Phase correction: 2 -> 1,
22:27:45.607 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:28:18.921 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:28:18.995 [info] Phase correction: 2 -> 1,
22:28:19.063 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:29:18.073 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:29:18.148 [info] Phase correction: 2 -> 1,
22:29:18.220 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
22:30:26.114 [info] == Running 20191212230527 TeslaMate.Repo.Migrations.RecalcEnergyUsed.up/0 forward,
22:30:26.189 [info] Phase correction: 2 -> 1,
22:30:26.258 [info] Phase correction: 2 -> 1,
** (KeyError) key :detected_end_date not found in: %{},
    lib/teslamate-1.14.0/priv/repo/migrations/20191212230527_recalc_energy_used.exs:159: TeslaMate.Repo.Migrations.RecalcEnergyUsed.complete_charging_process/1,
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2,
    (elixir) lib/enum.ex:783: Enum.each/2,
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3,
    (stdlib) timer.erl:166: :timer.tc/1,
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7,
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7,
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4,
```

**Comment by bahree** [comment]
In addition, I deprecated this down to 1.1.3.2 and when I get back to Grafana and on the charges, I see the following. I don't understand why these would be missing. Is the resolution deleting these entries from the database? And then pull the latest? Curious on why this happened in the first place.

Thanks.

![Capture-charges](https://user-images.githubusercontent.com/3529468/71399079-5f94b900-25d7-11ea-9351-646895a72792.PNG)

**Comment by bahree** [comment]
Perhaps in the migration, where this is null - in the scripts it can either delete these, or add a one second or some other time duration to meet the db constraint? Thoughts?

**Comment by adriankumpf** [comment]
Sorry for the inconvenience. The new version (v1.14.1) includes a fix. The charges are recomputed with this update. So nothing was deleted. After running the migrations everything should be back to normal.

**Comment by bahree** [comment]
Perfect this does solves it. Will close the ticket out. And please nothing to apologize @adriankumpf!

I had also deprecated the version and was curious on what and why this was happening. Turns out I over 600 records where the end date was null; and clearly something is causing this but I didn't know what - debugged it and turns out the issue was that my adapter from the charger wasn't fully connected. I use a JuicePro and need to use a adapter to charge the Model 3 - and that wasn't completely flush.

So the car would try charging (sensing it was plugged), but it couldn't and then would try again, and again, and again in a loop. Each time it started a new entry was written but it was never 'closed out'. I wanted to share here in case someone else also see's this. 

I wonder if we can find a collection of such issues that show up in the data, but the root cause is something else and it can help warn the owners.

Thanks.

**Comment by adriankumpf** [comment]
> Perfect this does solves it. Will close the ticket out. And please nothing to apologize @adriankumpf!

Glad it worked! :)

> So the car would try charging (sensing it was plugged), but it couldn't and then would try again, and again, and again in a loop. Each time it started a new entry was written but it was never 'closed out'. I wanted to share here in case someone else also see's this.

I thought that something must have gone wrong when logging those charges at some point in the past. It is possible that this is already fixed. If not, i.e. if that loop causes TeslaMate to produce any errors please open an issue with the log output.
