### ISSUE TITLE
(KeyError) key :id not found in: nil

### ISSUE THREAD

**Issue by focher** [adriankumpf/teslamate#3258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When attempting to go to the Settings on the TeslaMate dashboard, I get an Internal Server Error. The dashboard worked fine and showed all cars. The Grafana dashboards appear fine too.

### Expected Behavior

Displays Settings page.

### Steps To Reproduce

1. Open TeslaMate dashboard page.
2. Click Settings.

### Relevant log output

```shell
Request: GET /settings
** (exit) an exception was raised:
 ** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map

(teslamate 1.27.3) lib/teslamate_web/live/settings_live/index.ex:183: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
(elixir 1.15.0-rc.1) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
(teslamate 1.27.3) lib/teslamate_web/live/settings_live/index.ex:15: TeslaMateWeb.SettingsLive.Index.mount/3
(phoenix_live_view 0.17.14) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
(telemetry 1.2.1) /opt/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
(phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:270: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
(phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
(phoenix_live_view 0.17.14) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by cwanja** [comment]
@focher please see the mentioned issue or #3414 for a fix.
