### ISSUE TITLE
Charge is not shown correctly

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#343]
**Describe the bug**

Charging not logged correctly. This was one charge:
![2020-01-04 11_41_41-Window](https://user-images.githubusercontent.com/8087682/71764373-5c5ad080-2ee7-11ea-9bdd-6cbebab4571e.png)

**Expected behavior**

Well, that it is shown as one charge.

**Relevant entries from the logs**
Would database extract help?

```
16:07:42.829 car_id=1 [info] Charging / SOC: 70%
16:38:01.844 [error] TeslaApi.Error / 502 â€“ "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 4em auto 0 auto;\n      border: 1px solid #ccc;\n      border-right-color: #999;\n      border-bottom-color: #999;\n    }\n    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }\n  </style>\n</head>\n\n<body>\n  <!-- This file lives in public/500.html -->\n  <div class=\"dialog\">\n    <h1>We're sorry, but something went wrong.</h1>\n  </div>\n</body>\n</html>\n"
16:38:01.844 car_id=1 [error] Error / :unknown
16:46:22.592 [error] GenStateMachine :"1" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{battery_heater: false, battery_heater_on: false, charge_energy_added: 9.64, charger_actual_current: 0, charger_phases: nil, charger_power: 0.0, charger_voltage: 1, conn_charge_cable: "<invalid>", date: ~U[2020-01-03 15:46:22.367000Z], fast_charger_brand: "<invalid>", fast_charger_type: "<invalid>"}, errors: [ideal_battery_range_km: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Charge<>, valid?: false>}
    (teslamate) lib/teslamate/vehicles/vehicle.ex:460: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
16:46:23.975 car_id=1 [info] Start / :online
16:46:24.287 [error] GenStateMachine :"1" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{battery_heater: false, battery_heater_on: false, charge_energy_added: 9.64, charger_actual_current: 0, charger_phases: nil, charger_power: 0.0, charger_voltage: 1, conn_charge_cable: "<invalid>", date: ~U[2020-01-03 15:46:23.761000Z], fast_charger_brand: "<invalid>", fast_charger_type: "<invalid>"}, errors: [ideal_battery_range_km: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Charge<>, valid?: false>}
    (teslamate) lib/teslamate/vehicles/vehicle.ex:433: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
16:46:25.032 car_id=1 [info] Start / :online
16:46:25.281 car_id=1 [info] Charging / SOC: 89%
16:46:31.000 car_id=1 [info] Derived efficiency factor: 136.1 Wh/km (7x confirmed)
16:46:31.000 car_id=1 [info] Charging / Stopped / 0.09999999999999964 kWh â€“ 0 min
16:46:31.000 car_id=1 [info] Start / :online
```

**Screenshots**

If applicable, add screenshots to help explain the problem.

**Operating environment**

 - OS: Ubuntu 18.04.3
 - TeslaMate Version: v1.14.1
 - Type of installation: Docker

**Comment by DrMichael** [comment]
Hmmm, we have
```
Charging / SOC: 70%
Charging / SOC: 89%
Charging / Stopped / 0.09999999999999964 kWh â€“ 0 min
```
Could that be the issue?
