### ISSUE TITLE
Migration issue in v1.16.0 (migration 20200203120311)

### ISSUE THREAD

**Issue by Niek** [adriankumpf/teslamate#446]
I upgraded from v1.15.1 to v1.16.0 and encounter this migration issue:
```bash
$ _build/prod/rel/teslamate/bin/teslamate eval "TeslaMate.Release.migrate"
10:14:28.380 [info] == Running 20200203120311 TeslaMate.Repo.Migrations.CascadeDelete.up/0 forward
10:14:28.384 [info] drop constraint cars_settings_id_fkey from table cars
10:14:28.386 [info] alter table cars
10:14:28.390 [info] drop constraint charges_charging_process_id_fkey from table charges
10:14:28.392 [info] alter table charges
10:14:28.398 [info] drop constraint charging_processes_car_id_fkey from table charging_processes
10:14:28.399 [info] drop constraint charging_processes_address_id_fkey from table charging_processes
10:14:28.400 [info] drop constraint charging_processes_geofence_id_fkey from table charging_processes
10:14:28.401 [info] alter table charging_processes
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "charging_processes_car_id_index" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:166: :timer.tc/1
```

Some extra info:
```sql
select max(version) from schema_migrations
20200120142602
```

**Comment by Niek** [comment]
I fixed it by adding the following lines to ``priv/repo/migrations/20200203120311_cascade_delete.exs``:

```elixir
    drop(index(:charging_processes, [:car_id]))
    drop(index(:drives, [:car_id], name: :trips_car_id_index))
    drop(index(:drives, [:start_address_id], name: :trips_start_address_id_index))
    drop(index(:drives, [:end_address_id], name: :trips_end_address_id_index))
    drop(index(:drives, [:start_position_id]))
    drop(index(:drives, [:end_position_id]))
    drop(index(:drives, [:start_geofence_id]))
    drop(index(:positions, [:car_id]))
```

Not sure if it's just my install or if more people encountered it? In that case it might be good to add this the migration file.

**Comment by adriankumpf** [comment]
I'm unable to reproduce that issue. If anyone else has the problem: let us know!

I would be careful about deleting indexes, though.

**Comment by Niek** [comment]
I re-created the indexes afterwards, so queries won't be slow. Not sure why I encountered this issue, might be because I'm running PostgreSQL 11 instead of 12 (on a standalone install)?

**Comment by Niek** [comment]
Apparently it's a bug with specific PostgreSQL versions, like 11.4:
Discussion: https://www.postgresql.org/message-id/15865-17940eacc8f8b081@postgresql.org
Fix: https://git.postgresql.org/gitweb/?p=postgresql.git&a=commitdiff&h=afaf48afb

I'm closing this, since it's not a Teslamate issue. Short story: use the most recent PostgreSQL version and you'll be fine :)
