### ISSUE TITLE
Grafana crashes after update of teslamate to 1.18.2

### ISSUE THREAD

**Issue by markusdd** [adriankumpf/teslamate#540]
**Describe the bug**

After upgrading teslamate, itself is runnign fine and database migration was successful.
But Grafana keeps crashing with below stacktrace

```
Mar 29 15:05:56 tesla grafana-server[2712]: panic: non-positive interval for NewTicker
Mar 29 15:05:56 tesla grafana-server[2712]: goroutine 131 [running]:
Mar 29 15:05:56 tesla grafana-server[2712]: time.NewTicker(0xffffffffc4653600, 0x0)
Mar 29 15:05:56 tesla grafana-server[2712]:         /usr/local/go/src/time/tick.go:23 +0x147
Mar 29 15:05:56 tesla grafana-server[2712]: github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*fileReader).pollChanges(0xc000189a40, 0x1e99240, 0xc0009dbb80)
Mar 29 15:05:56 tesla grafana-server[2712]:         /go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/file_reader.go:57 +0x4e
Mar 29 15:05:56 tesla grafana-server[2712]: created by github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*DashboardProvisionerImpl).PollChanges
Mar 29 15:05:56 tesla grafana-server[2712]:         /go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/dashboard.go:62 +0x76
Mar 29 15:05:56 tesla systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 29 15:05:56 tesla systemd[1]: grafana-server.service: Unit entered failed state.
```

**To Reproduce**

Upgrade to 1.18.2
Use Grafana on Debian , version 6.6.2 or 6.7.1 (latest) crash with dame behavior

**Expected behavior**

Grafana shall start und use the new dashboards

**Relevant entries from the logs**

Teslamate is fine
```
Mar 29 15:02:46 tesla systemd[1]: Started Teslamate.
Mar 29 15:02:52 tesla teslamate[520]: 17:02:52.348 [info] Version: 1.18.2
Mar 29 15:02:53 tesla teslamate[520]: 17:02:53.369 [info] Refreshed api tokens
Mar 29 15:02:53 tesla teslamate[520]: 17:02:53.369 [info] Scheduling token refresh in 40d
Mar 29 15:02:53 tesla teslamate[520]: 17:02:53.380 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
Mar 29 15:02:53 tesla teslamate[520]: 17:02:53.380 [info] Access TeslaMateWeb.Endpoint at http://localhost
Mar 29 15:02:54 tesla teslamate[520]: 17:02:54.167 [info] Starting logger for 'Hyperion'
Mar 29 15:02:54 tesla teslamate[520]: 17:02:54.971 car_id=1 [info] Start / :offline
Mar 29 15:03:38 tesla teslamate[520]: 17:03:38.539 [info] GET /
Mar 29 15:03:38 tesla teslamate[520]: 17:03:38.548 [info] Sent 200 in 9ms

```

**Operating environment**

- TeslaMate Version: 1.18.2 (upgraded from 1.14.3)
- Type of installation: manual
- OS: debian 9 (fully up to date)

**Comment by markusdd** [comment]
ok, it definetly crashes on dashboard import.
I removed my  /etc/grafana/provisioning/dashboards/dashboards.yml

and then grafana starts, but I have no dashboards obviously.

```
apiVersion: 1

providers:
- name: 'teslamate'
  orgId: 1
  folder: dashboards
  type: file
  disableDeletion: false
  editable: true
  updateIntervalSeconds: -1
  options:
    path: /usr/src/teslamate/grafana/dashboards
```

**Comment by adriankumpf** [comment]
Provisioning Grafana is not covered in [the documentation](https://teslamate.readthedocs.io/en/latest/installation/debian.html) but you've probably used this file as a basis:

https://github.com/adriankumpf/teslamate/blob/677891833623df115c5d4fc8278c298697c45a61/grafana/dashboards.yml#L1-L23 

Notice `updateIntervalSeconds` which needs to be a positive integer. Alternatively, reimport the dashboards once after each update:

```bash
$ ./grafana/dashboards.sh restore

URL:                  http://localhost:3000
LOGIN:                admin:admin             
DASHBOARDS_DIRECTORY: ./grafana/dashboards

RESTORED locations.json
RESTORED drive-stats.json
RESTORED updates.json
RESTORED drive-details.json
RESTORED charge-details.json
RESTORED states.json
RESTORED overview.json
RESTORED vampire-drain.json
RESTORED visited.json
RESTORED drives.json
RESTORED projected-range.json
RESTORED charge-level.json
RESTORED charging-stats.json
RESTORED mileage.json
RESTORED charges.json
RESTORED efficiency.json

```

**Comment by markusdd** [comment]
Thanks for pointing that out.
Still I'm confused why that is, because I did take the provisioning file from kind of official tutoial and it worked fine ever since, it just stopped working now. 

Anyway...it works now.

**Comment by adriankumpf** [comment]
I ran into the same error when upgrading Grafana. They seem to have made some changes in this respect in recent versions.

**Comment by markusdd** [comment]
Ok, that gives me peace of mind that I'm not stupid and can't read xD
