### ISSUE TITLE
After container restart connection to Tesla seems unauthorized 

### ISSUE THREAD

**Issue by robbertverheij** [adriankumpf/teslamate#597]
**Describe the bug**

After restart of teslamate container it seems that the connection to the Tesla api is unauthorized. After re-login or manually adding tokens to DB the connection seems to be working as long as the container isn't restarted. (I schedule a stop / offline backup / start every day, so I get the issue daily)

**To Reproduce**

1. restart container
2. check logging

**Expected behavior**

The connection not to be unauthorized.

**Relevant entries from the logs**

2020-04-17T11:33:46.154503166Z 11:33:46.154 [info] [alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}],
2020-04-17T11:36:17.610114120Z 11:36:17.608 [info] SIGTERM received - shutting down,
2020-04-17T11:36:17.610517400Z ,
2020-04-17T11:36:38.505344686Z 11:36:38.498 [info] Already up,
2020-04-17T11:37:14.196381004Z 11:37:14.195 [info] Version: 1.19.0-dev,
2020-04-17T11:37:24.216190277Z 11:37:24.212 [warn] Token refresh failed: %TeslaApi.Error{,
2020-04-17T11:37:24.216326162Z   env: %Mojito.Response{,
2020-04-17T11:37:24.216362673Z     body: %{,
2020-04-17T11:37:24.216395225Z       "error" => "invalid_grant",,
2020-04-17T11:37:24.216430954Z       "error_description" => "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
2020-04-17T11:37:24.216471006Z     },,
2020-04-17T11:37:24.216502673Z     complete: true,,
2020-04-17T11:37:24.216537412Z     headers: [,
2020-04-17T11:37:24.216568454Z       {"server", "nginx"},,
2020-04-17T11:37:24.216600433Z       {"date", "Fri, 17 Apr 2020 11:37:24 GMT"},,
2020-04-17T11:37:24.216633089Z       {"content-type", "application/json; charset=utf-8"},,
2020-04-17T11:37:24.216666474Z       {"transfer-encoding", "chunked"},,
2020-04-17T11:37:24.216808922Z       {"connection", "keep-alive"},,
2020-04-17T11:37:24.216842516Z       {"x-frame-options", "SAMEORIGIN"},,
2020-04-17T11:37:24.216897932Z       {"x-xss-protection", "1; mode=block"},,
2020-04-17T11:37:24.217007463Z       {"x-content-type-options", "nosniff"},,
2020-04-17T11:37:24.217044286Z       {"cache-control", "no-store"},,
2020-04-17T11:37:24.217078036Z       {"pragma", "no-cache"},,
2020-04-17T11:37:24.217109547Z       {"www-authenticate",,
2020-04-17T11:37:24.217140432Z        "Bearer realm=\"Doorkeeper\", error=\"invalid_grant\", error_description=\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\""},,
2020-04-17T11:37:24.217177151Z       {"x-request-id", "a52294c59bc52ac022051ecbed7bbfa1"},,
2020-04-17T11:37:24.217207671Z       {"x-runtime", "0.005480"},
2020-04-17T11:37:24.217237776Z     ],,
2020-04-17T11:37:24.217267098Z     status_code: 401,
2020-04-17T11:37:24.217296734Z   },,
2020-04-17T11:37:24.217325953Z   message: "Failed to authenticate.",,
2020-04-17T11:37:24.217355692Z   reason: :authentication_failure,
2020-04-17T11:37:24.217384963Z },
2020-04-17T11:37:24.217431004Z 11:37:24.212 [info] Elixir.TeslaMate.Api / unhandled message: {#Reference<0.2210834356.3752067076.95532>, :ok},
2020-04-17T11:37:24.218066837Z 11:37:24.216 [info] Elixir.TeslaMate.Api / unhandled message: {:mojito_response, #Reference<0.2210834356.3752067076.95528>,,
2020-04-17T11:37:24.218150691Z  {:ok,,
2020-04-17T11:37:24.218207878Z   %Mojito.Response{,,
17T11:37:24.218240430Z     body: "{\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}",,
2020-04-17T11:37:24.218276003Z     complete: true,,
2020-04-17T11:37:24.218323191Z     headers: [,
2020-04-17T11:37:24.218352982Z       {"server", "nginx"},,
2020-04-17T11:37:24.218383503Z       {"date", "Fri, 17 Apr 2020 11:37:19 GMT"},,
2020-04-17T11:37:24.218416003Z       {"content-type", "application/json; charset=utf-8"},,
2020-04-17T11:37:24.218446992Z       {"transfer-encoding", "chunked"},,
2020-04-17T11:37:24.218477461Z       {"connection", "keep-alive"},,
2020-04-17T11:37:24.218507722Z       {"x-frame-options", "SAMEORIGIN"},,
2020-04-17T11:37:24.218539961Z       {"x-xss-protection", "1; mode=block"},,
2020-04-17T11:37:24.218570794Z       {"x-content-type-options", "nosniff"},,
2020-04-17T11:37:24.218601211Z       {"cache-control", "no-store"},,
2020-04-17T11:37:24.218631680Z       {"pragma", "no-cache"},,
2020-04-17T11:37:24.218663034Z       {"www-authenticate",,
2020-04-17T11:37:24.218694440Z        "Bearer realm=\"Doorkeeper\", error=\"invalid_grant\", error_description=\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\""},,
2020-04-17T11:37:24.218785065Z       {"x-request-id", "24ac4aa4e442bb08fc8dfb33c23a922e"},,
2020-04-17T11:37:24.218818034Z       {"x-runtime", "0.006425"},
2020-04-17T11:37:24.218848190Z     ],,
2020-04-17T11:37:24.218877461Z     status_code: 401,
2020-04-17T11:37:24.218906523Z   }}},
2020-04-17T11:37:24.231941295Z 11:37:24.231 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http),
2020-04-17T11:37:24.236043945Z 11:37:24.235 [info] Access TeslaMateWeb.Endpoint at http://localhost,
2020-04-17T11:37:24.272008161Z 11:37:24.266 [warn] Using fallback vehicles:,
2020-04-17T11:37:24.272108681Z ,
2020-04-17T11:37:24.272139775Z [,
2020-04-17T11:37:24.272171025Z   %TeslaApi.Vehicle{,
2020-04-17T11:37:24.272200869Z     api_version: nil,,
2020-04-17T11:37:24.272230608Z     backseat_token: nil,,
2020-04-17T11:37:24.272259931Z     backseat_token_updated_at: nil,,
2020-04-17T11:37:24.272290191Z     calendar_enabled: nil,,
2020-04-17T11:37:24.272322275Z     charge_state: nil,,
2020-04-17T11:37:24.272352170Z     climate_state: nil,,
2020-04-17T11:37:24.272381441Z     color: nil,,
2020-04-17T11:37:24.272413733Z     display_name: "JR's M3",,
2020-04-17T11:37:24.272445295Z     drive_state: nil,,
2020-04-17T11:37:24.272474618Z     gui_settings: nil,,
2020-04-17T11:37:24.272504097Z     id: <redacted>,,
2020-04-17T11:37:24.272533733Z     in_service: false,,
2020-04-17T11:37:24.272563160Z     option_codes: [],,
2020-04-17T11:37:24.272594774Z     state: "unknown",,
2020-04-17T11:37:24.272634305Z     tokens: [],,
2020-04-17T11:37:24.272664774Z     vehicle_config: nil,,
2020-04-17T11:37:24.272694566Z     vehicle_id: <redacted>,,
2020-04-17T11:37:24.272723889Z     vehicle_state: nil,,
2020-04-17T11:37:24.272753003Z     vin: "0",
2020-04-17T11:37:24.272782066Z   },
2020-04-17T11:37:24.272811649Z ],
2020-04-17T11:37:24.272840711Z 11:37:24.267 [info] Starting logger for 'JR's M3',
2020-04-17T11:37:24.302647801Z 11:37:24.299 [error] Error / unauthorized,
2020-04-17T11:37:24.326379744Z 11:37:24.307 [info] MQTT connection has been established,
2020-04-17T11:38:13.386919294Z 11:38:13.386 [info] [alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}],
2020-04-17T11:40:28.174339988Z 11:40:28.172 [info] GET /settings,
2020-04-17T11:40:28.262705474Z 11:40:28.252 [info] Sent 200 in 80ms,
2020-04-17T11:40:34.563710571Z 11:40:34.563 [info] GET /,
2020-04-17T11:40:34.575155189Z 11:40:34.573 [info] Sent 302 in 10ms,
2020-04-17T11:40:34.864382911Z 11:40:34.861 [info] GET /sign_in,
2020-04-17T11:40:34.889500320Z 11:40:34.874 [info] Sent 200 in 12ms,
2020-04-17T11:41:28.630299682Z 11:41:28.628 [info] Scheduling token refresh in 40d,
2020-04-17T11:41:29.174843665Z 11:41:29.174 [info] GET /,
2020-04-17T11:41:33.600337600Z 11:41:33.599 [info] Starting logger for 'JR's M3',
2020-04-17T11:41:33.642122794Z 11:41:33.641 [info] Sent 200 in 4467ms,
2020-04-17T11:41:33.909140757Z 11:41:33.908 car_id=1 [info] Start / :offline,
2020-04-17T11:44:13.393008960Z 11:44:13.392 [info] [alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}],

(I redacted the ID's)
I also checked that the ID//vehicle_ID are present and the same as in the request in the car table in the database.
**Screenshots**

**Operating environment**

- TeslaMate Version: teslamate:1.19.0-dev latest pull from docker. (tried updating to this version because of the same issue I also had with using the stable 1.18 verion)
- Type of installation: Docker
- OS: Raspberry Pi

**Comment by adriankumpf** [comment]
At startup the tokens are refreshed ([POST /oauth/token?grant_type=refresh_token](https://tesla-api.timdorr.com/api-basics/authentication#post-oauth-token-grant_type-refresh_token)). The error `"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."` indicates a problem with the tokens themselves. You could try a manual refresh (e.g. using curl) to see if that works. Otherwise I wouldn't know what TeslaMate could do that would cause a refresh to fail with that error message.

**Comment by robbertverheij** [comment]
That’s what I figured as well... unfortunately manually refreshing tokens using curl gives the same issue. I suppose calling Tesla isn’t really an option.. For now I just don’t shutdown the container anymore before making a backup and I’m hoping it’ll pass eventually. I’ll keep you posted.

**Comment by adriankumpf** [comment]
Have you already tried to reset your Tesla password? This might help.

**Comment by robbertverheij** [comment]
Tried that already before posting the possible issue. Unfortunately no luck with that either.... Smartphone apps are still ok and logged in. (Of course when resetting the password inwas required to change it)

**Comment by robbertverheij** [comment]
Apparently since last weekend the issue is solved without a hint of the exact source. Anyway; thanks for reading my story. :-)

**Comment by jun3280net** [comment]
> Have you already tried to reset your Tesla password? This might help.
Hi @adriankumpf , @robbertverheij  I've been roughly two months removed from from using Teslamate, as Tesla's recent software updates have caused some issues with various functions.  My last logged data point appears to be Mar 5, 2020.

Things have now stabilized with 2020.12.10 - so I decided to check back in with Teslamate.  I see there have been a number of revisions and I was excited to update my docker container.

That said, I ran into the same error : 
teslamate_1  |       {"www-authenticate",
teslamate_1  |        **"Bearer realm=\"Doorkeeper\", error=\"invalid_grant\", error_description=\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\""},**
teslamate_1  |       {"x-request-id", "f41468aa4b43d862ab76d963725eeb9c"},
teslamate_1  |       {"x-runtime", "0.010631"}
teslamate_1  |     ],
teslamate_1  |     status_code: 401
teslamate_1  |   },
teslamate_1  |   message: "Failed to authenticate.",
teslamate_1  |   reason: :authentication_failure
teslamate_1  | }
teslamate_1  | 18:59:00.755 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
teslamate_1  | 18:59:00.756 [info] Access TeslaMateWeb.Endpoint at http://teslamate.root.dxxx.com
teslamate_1  | 18:59:00.758 [warn] Using fallback vehicles:

I can access Grafana.  However, when I try and access https://teslamate.root.dxxx.com I get prompted for my tesla login/pass.  I enter the proper credentials, but it keeps prompting.  
I've tried resetting my Tesla password, but same issue.

![image](https://user-images.githubusercontent.com/30555695/80839565-c1ce7d80-8bb8-11ea-9873-b9e4dd03f554.png)

I then decided to run the suggested run CURL to update the token into the server directly to bypass the login/pass prompt.

![image](https://user-images.githubusercontent.com/30555695/80839756-17a32580-8bb9-11ea-8a83-04c8ff67c61d.png)

This however did not work for me either, as I'm still being prompted on the Teslamate screen.
![image](https://user-images.githubusercontent.com/30555695/80846220-c733c400-8bc8-11ea-968b-583f42c25810.png)

I believe the relevant log details are as follows : 
proxy_1      | time="2020-05-01T19:28:14Z" level=error msg="unable to find the IP address for the container \"/teslamate_teslamate_1\": the server is ignored" providerName=docker container=teslamate-teslamate-**bd76a85552c6753a9c2e2ad88b13d536cd649dd4f474e94b26103a924aac9a60**
database_1   | 2020-05-01 19:28:15.692 UTC [150] LOG:  incomplete startup packet
teslamate_teslamate_1 exited with code 1
teslamate_1  | 19:26:33.770 [info] Already up
teslamate_1  | 19:26:39.906 [info] Version: 1.19.2
teslamate_1  | 19:26:39.927 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Api
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (CaseClauseError) no case clause matching: [%TeslaMate.Auth.Tokens{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, access: "**old_token**", id: 1, inserted_at: ~N[2019-08-15 09:30:58], refresh: "**old_refresh_token**", updated_at: ~N[2020-02-23 05:47:46]}, %TeslaMate.Auth.Tokens{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, access: "**new_token**", id: 2, inserted_at: ~N[2020-05-01 19:23:29], refresh: "**new_refresh_token**", updated_at: ~N[2020-05-01 19:23:29]}]
teslamate_1  |             (teslamate 1.19.2) lib/teslamate/auth.ex:22: TeslaMate.Auth.get_tokens/0
teslamate_1  |             (teslamate 1.19.2) lib/teslamate/api.ex:85: TeslaMate.Api.init/1
teslamate_1  |             (stdlib 3.12.1) gen_server.erl:374: :gen_server.init_it/2
teslamate_1  |             (stdlib 3.12.1) gen_server.erl:342: :gen_server.init_it/6
teslamate_1  |             (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | {"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{case_clause,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.TeslaMate.Auth.Tokens',source => <<\"tokens\">>,state => loaded},'__struct__' => 'Elixir.TeslaMate.Auth.Tokens',access => <<\"**old_token**\">>,id => 1,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 15,hour => 9,microsecond => {0,0},minute => 30,month => 8,second => 58,year => 2019},refresh => <<\"**old_refresh_token**\">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 5,microsecond => {0,0},minute => 47,month => 2,second => 46,year => 2020}},#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.TeslaMate.Auth.Tokens',source => <<\"tokens\">>,state => loaded},'__struct__' => 'Elixir.TeslaMate.Auth.Tokens',access => <<\"**new_token**\">>,id => 2,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 1,hour => 19,microsecond => {0,0},minute => 23,month => 5,second => 29,year => 2020},refresh => <<\"**new_refresh_token**\">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 1,hour => 19,microsecond => {0,0},minute => 23,month => 5,second => 29,year => 2020}}]},[{'Elixir.TeslaMate.Auth',get_tokens,0,[{file,\"lib/teslamate/auth.ex\"},{line,22}]},{'Elixir.TeslaMate.Api',init,1,[{file,\"lib/teslamate/api.ex\"},{line,85}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
teslamate_1  | Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{case_clause,[#{'__meta__' => #{'__struct__' => 'Elixir.E
teslamate_1  | 
teslamate_1  | Crash dump is being written to: erl_crash.dump...done
teslamate_1  | 19:26:45.288 [info] Already up
teslamate_1  | 19:26:51.311 [info] Version: 1.19.2

**Comment by jun3280net** [comment]
With regards to logging in at the Teslamate screen ... I must have forgotten my login/pass.  I ended up just replacing the .htpasswd file with new info populated from [htpasswd generator](https://hostingcanada.org/htpasswd-generator/) using Mode : Apache specific salted MD5.
