### ISSUE TITLE
Crashes on startup after manual update from v1.19.1 to v1.19.2

### ISSUE THREAD

**Issue by rtega** [adriankumpf/teslamate#652]
Teslamate crashes on startup after I manually upgraded from v1.19.1 to v1.19.2.

I got this in my logs:
```
22:58:12.389 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMateWeb.En\
dpoint
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Phoenix.Socket.__child_spec__/2 is undefined or private
            (phoenix 1.5.1) Phoenix.Socket.__child_spec__(Phoenix.LiveView.Socket, [endpoint: TeslaMateWeb.Endpoint, websocket: [connect_info: [session: [stor\
e: :cookie, key: "_teslamate_key", signing_salt: "yt5O3CAQ"]], transport_log: :debug]])
            (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
            (phoenix 1.5.1) lib/phoenix/endpoint/supervisor.ex:105: Phoenix.Endpoint.Supervisor.init/1
            (stdlib 3.10) supervisor.erl:295: :supervisor.init/1
            (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMateWeb.Endpoint',{undef,\
[{'Elixir.Phoenix.Socket','__child_spec__',['Elixir.Phoenix.LiveView.Socket',[{endpoint,'Elixir.TeslaMateWeb.Endpoint'},{websocket,[{connect_info,[{session,[{\
store,cookie},{key,<<\"_teslamate_key\">>},{signing_salt,<<\"yt5O3CAQ\">>}]}]},{transport_log,debug}]}]],[]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\\
"lib/enum.ex\"},{line,1396}]},{'Elixir.Phoenix.Endpoint.Supervisor',init,1,[{file,\"lib/phoenix/endpoint/supervisor.ex\"},{line,105}]},{supervisor,init,1,[{fi\
le,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]\
},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMateWeb.Endpoint',{undef,[\
{'Elixir.Phoenix.Socket','__child_spec__',

Crash dump is being written to: erl_crash.dump...done

```

The crash dump has been attached.

**Operating environment**

- TeslaMate Version: v1.19.2
- Type of installation: Manual
- OS: raspbian
[erl_crash.zip](https://github.com/adriankumpf/teslamate/files/4536469/erl_crash.zip)

**Comment by adriankumpf** [comment]
This could be a caching problem. Try to clean the `_build` directory and then repeat the upgrade process.

**Comment by rtega** [comment]
That solved it! Thanks! Maybe this should be mentioned in the docs?

**Comment by adriankumpf** [comment]
Great! Yeah, we should mention that in the upgrade guide.

**Comment by pyjamasam** [comment]
Confirmed the same issue, and the same resolution worked.

**Comment by SigLinJo** [comment]
Confirming same issue on FreeBSD 11.3 and clearing _build worked for me to. Thanks for providing a solution!
