### ISSUE TITLE
BAD Gateway error since I tried to use API token instead of Tesla login/password

### ISSUE THREAD

**Issue by convertl** [adriankumpf/teslamate#657]
**Describe the bug**

Hi,
I followed the FAQ to use my API token instead of my Tesla username/password.
Since then, when I restarted Teslamate docker, I get an "Bad gateway" error message when trying to access Teslamate on my web browser.

I got the logs (see below), it seems error is linked to the update of the database (I replaced real tokens with myoldtoken and mynewtoken)

How can I fix that ?

Thanks for the help !

**To Reproduce**

I followed the FAQ on https://docs.teslamate.org/docs/faq "How do I use my API token instead of my Tesla username/password?"

**Expected behavior**

Teslamate working. It is not anymore the case.

**Relevant entries from the logs**

```
teslamate_1  | 20:13:12.630 [info] Already up
teslamate_1  | 20:13:34.068 [info] Version: 1.19.1
teslamate_1  | 20:13:34.136 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Api
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (CaseClauseError) no case clause matching: [%TeslaMate.Auth.Tokens{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, access: "myoldaccesstoken", id: 1, inserted_at: ~N[2020-02-20 17:55:11], refresh: "myoldrefreshtoken", updated_at: ~N[2020-04-21 16:26:25]}, %TeslaMate.Auth.Tokens{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, access: "mynewaccesstoken", id: 2, inserted_at: ~N[2020-04-24 10:02:12], refresh: "mynewrefreshtoken", updated_at: ~N[2020-04-24 10:02:12]}]
teslamate_1  |             (teslamate 1.19.1) lib/teslamate/auth.ex:22: TeslaMate.Auth.get_tokens/0
teslamate_1  |             (teslamate 1.19.1) lib/teslamate/api.ex:85: TeslaMate.Api.init/1
teslamate_1  |             (stdlib 3.12.1) gen_server.erl:374: :gen_server.init_it/2
teslamate_1  |             (stdlib 3.12.1) gen_server.erl:342: :gen_server.init_it/6
teslamate_1  |             (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | {"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{case_clause,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.TeslaMate.Auth.Tokens',source => <<\"tokens\">>,state => loaded},'__struct__' => 'Elixir.TeslaMate.Auth.Tokens',access => <<\"myoldaccesstoken\">>,id => 1,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 20,hour => 17,microsecond => {0,0},minute => 55,month => 2,second => 11,year => 2020},refresh => <<\"myoldrefreshtoken\">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 21,hour => 16,microsecond => {0,0},minute => 26,month => 4,second => 25,year => 2020}},#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.TeslaMate.Auth.Tokens',source => <<\"tokens\">>,state => loaded},'__struct__' => 'Elixir.TeslaMate.Auth.Tokens',access => <<\"mynewaccesstoken\">>,id => 2,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 24,hour => 10,microsecond => {0,0},minute => 2,month => 4,second => 12,year => 2020},refresh => <<\"mynewrefreshtoken\">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 24,hour => 10,microsecond => {0,0},minute => 2,month => 4,second => 12,year => 2020}}]},[{'Elixir.TeslaMate.Auth',get_tokens,0,[{file,\"lib/teslamate/auth.ex\"},{line,22}]},{'Elixir.TeslaMate.Api',init,1,[{file,\"lib/teslamate/api.ex\"},{line,85}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
teslamate_1  | Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{case_clause,[#{'__meta__' => #{'__struct__' => 'Elixir.E
teslamate_1  |
teslamate_1  | Crash dump is being written to: erl_crash.dump...done
```

**Operating environment**

- TeslaMate Version: v1.19.1
- Type of installation: Docker
- OS: Debian

**Comment by adriankumpf** [comment]
Somehow there are two tokens pairs in the "tokens" table … however, only one is allowed. Try to delete on row from that table and restart.

**Comment by convertl** [comment]
Hi Adrian.
Thanks for the answer. I deleted row id 1 and now Teslamate works again.

Thanks a lot !

**Comment by detritu5** [comment]
How you delete the token?? I´ve tried with TRUNCATE tokens and DELETE FROM tokens
but still have the same issue.
