### ISSUE TITLE
Locale file compile error (cldr.ex)

### ISSUE THREAD

**Issue by Niek** [adriankumpf/teslamate#761]
When compiling the latest master I get this error:
```elixir
Generating TeslaMateWeb.Cldr for 14 locales named ["da", "de", "en", "en-001", "es", ...] with a default locale named "en"

== Compilation error in file lib/teslamate_web/cldr.ex ==
** (RuntimeError) Locale file "da" is invalid - map key "lenient_parse" was not found.
    lib/cldr/config/config.ex:1964: anonymous fn/4 in Cldr.Config.assert_valid_keys!/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/cldr/config/config.ex:1962: Cldr.Config.assert_valid_keys!/2
    lib/cldr/config/config.ex:1278: Cldr.Config.do_get_locale/3
    lib/cldr/compiler_locale_cache.ex:71: Cldr.Locale.Cache.do_get_locale/2
    lib/cldr/config/config.ex:529: anonymous fn/2 in Cldr.Config.known_rbnf_locale_names/1
    (elixir 1.10.3) lib/enum.ex:3291: Enum.filter_list/2
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by adriankumpf** [comment]
The CI builds succeed so deleeting the cached locale files should work: `rm -rf priv/cldr/locales/*`

**Comment by Niek** [comment]
Thanks, that did the job :) Might be a good one to add to the manual upgrade process. Closing this issue now!
