### ISSUE TITLE
Crash during initialization due to timeout in TeslaMate.Vehicles.list_vehicles

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#835]
I started TeslaMate (manual FreeBSD VirtualBox install behind an Apache reverse proxy) and the brower reported 500 Server Error.  The TeslaMate log contains the following:

```
=====
===== LOGGING STARTED Sun Jul 12 12:01:04 BST 2020
=====
12:01:17.938 [info] Version: 1.19.3
12:01:18.957 [info] Refreshed api tokens
12:01:18.957 [info] Scheduling token refresh in 40d
12:01:18.970 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at 127.0.0.1:4000 (http)
12:01:19.030 [info] Access TeslaMateWeb.Endpoint at http://localhost
12:01:31.854 [info] GET /
12:01:49.034 [error] #PID<0.4126.0> running TeslaMateWeb.Endpoint (connection #PID<0.4125.0>, stream id 1) terminated
Server: localhost:8000 (http)
Request: GET /
** (exit) exited in: GenServer.call(TeslaMate.Vehicles, :which_children, :infinity)
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, :timeout}
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:78: TeslaMate.Vehicles.list_vehicles!/0
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:52: TeslaMate.Vehicles.init/1
            (stdlib 3.8.2.3) supervisor.erl:295: :supervisor.init/1
            (stdlib 3.8.2.3) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.8.2.3) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.8.2.3) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
12:01:55.044 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Vehicles
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, :timeout}
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:78: TeslaMate.Vehicles.list_vehicles!/0
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:52: TeslaMate.Vehicles.init/1
            (stdlib 3.8.2.3) supervisor.erl:295: :supervisor.init/1
            (stdlib 3.8.2.3) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.8.2.3) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.8.2.3) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{{case_clause,{error,timeout}},[{'Elixir.TeslaMate.Vehicles','list_vehicles!',0,[{file,\"lib/teslamate/vehicles.ex\"},{line,78}]},{'Elixir.TeslaMate.Vehicles',init,1,[{file,\"lib/teslamate/vehicles.ex\"},{line,52}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{{case_clause,{error,timeout}},[{'Elixir.TeslaMate.Ve

Crash dump is being written to: erl_crash.dump...done
```

This normally works and it worked after restarting TeslaMate.

**Comment by dyxyl** [comment]
It just happened again:

```
=====
===== LOGGING STARTED Mon Jul 13 19:16:37 BST 2020
=====
19:16:50.482 [info] Version: 1.19.3
19:16:51.500 [info] Refreshed api tokens
19:16:51.500 [info] Scheduling token refresh in 40d
19:16:51.512 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at 127.0.0.1:4000 (http)
19:16:51.538 [info] Access TeslaMateWeb.Endpoint at http://localhost
19:17:21.565 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Vehicles
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, :timeout}
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:78: TeslaMate.Vehicles.list_vehicles!/0
            (teslamate 1.19.3) lib/teslamate/vehicles.ex:52: TeslaMate.Vehicles.init/1
            (stdlib 3.8.2.3) supervisor.erl:295: :supervisor.init/1
            (stdlib 3.8.2.3) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.8.2.3) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.8.2.3) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{{case_clause,{error,timeout}},[{'Elixir.TeslaMate.Vehicles','list_vehicles!',0,[{file,\"lib/teslamate/vehicles.ex\"},{line,78}]},{'Elixir.TeslaMate.Vehicles',init,1,[{file,\"lib/teslamate/vehicles.ex\"},{line,52}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{{case_clause,{error,timeout}},[{'Elixir.TeslaMate.Ve

Crash dump is being written to: erl_crash.dump...done
```

FWIW, Postgres printed that it was listening at 19:16:30 and TeslaMate's migrations ran at 19:16:37 without any errors.

As before, it worked after restarting TeslaMate.

**Comment by dyxyl** [comment]
It also worked first time after I rebooted the FreeBSD VM.

**Comment by adriankumpf** [comment]
API errors were previously not handled during initialization. This should be fixed on the master branch.
