### ISSUE TITLE
Import: GPS Glitch caused Teslamate to crash

### ISSUE THREAD

**Issue by flexosvr** [adriankumpf/teslamate#898]
A glitch in the GPS data from a teslafi import caused teslamate to crash when it tried to find addresses. I remember the glitch happening as I was driving. the GPS thought i was in the ocean for a little bit until it re-locked. 

If an address can't be determined, the software should not crash, it should state the address as "Unknown"

Import the csv provided

[GPS-glitch-TeslaFi72020.zip](https://github.com/adriankumpf/teslamate/files/5168382/GPS-glitch-TeslaFi72020.zip)

**Relevant entries from the logs**

```
19:00:22.737 [info] Repairing drive #68 ...
19:00:24.330 [error] GenServer TeslaMate.Repair terminating

** (BadMapError) expected a map, got: nil
(elixir 1.10.3) lib/map.ex:450: Map.get(nil, "house_number", nil)
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:139: TeslaMate.Locations.Geocoder.get_first/2
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:123: TeslaMate.Locations.Geocoder.into_address/1
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:16: TeslaMate.Locations.Geocoder.reverse_lookup/3
(teslamate 1.19.4) lib/teslamate/locations.ex:37: TeslaMate.Locations.find_address/1
(teslamate 1.19.4) lib/teslamate/repair.ex:124: TeslaMate.Repair.get_address_id/1
(teslamate 1.19.4) lib/teslamate/repair.ex:97: TeslaMate.Repair.repair/1
(teslamate 1.19.4) lib/teslamate/repair.ex:59: TeslaMate.Repair.handle_cast/2
Last message: {:"$gen_cast", :repair}
19:00:24.336 [info] Repairing drive #68 ...
19:00:24.330 [error] GenServer TeslaMate.Repair terminating

** (BadMapError) expected a map, got: nil
(elixir 1.10.3) lib/map.ex:450: Map.get(nil, "house_number", nil)
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:139: TeslaMate.Locations.Geocoder.get_first/2
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:123: TeslaMate.Locations.Geocoder.into_address/1
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:16: TeslaMate.Locations.Geocoder.reverse_lookup/3
(teslamate 1.19.4) lib/teslamate/locations.ex:37: TeslaMate.Locations.find_address/1
(teslamate 1.19.4) lib/teslamate/repair.ex:124: TeslaMate.Repair.get_address_id/1
(teslamate 1.19.4) lib/teslamate/repair.ex:97: TeslaMate.Repair.repair/1
(teslamate 1.19.4) lib/teslamate/repair.ex:59: TeslaMate.Repair.handle_cast/2
Last message: {:"$gen_cast", :repair}
19:00:24.336 [info] Repairing drive #68 ...
19:00:25.936 [error] GenServer TeslaMate.Repair terminating

** (BadMapError) expected a map, got: nil
(elixir 1.10.3) lib/map.ex:450: Map.get(nil, "house_number", nil)
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:139: TeslaMate.Locations.Geocoder.get_first/2
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:123: TeslaMate.Locations.Geocoder.into_address/1
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:16: TeslaMate.Locations.Geocoder.reverse_lookup/3
(teslamate 1.19.4) lib/teslamate/locations.ex:37: TeslaMate.Locations.find_address/1
(teslamate 1.19.4) lib/teslamate/repair.ex:124: TeslaMate.Repair.get_address_id/1
(teslamate 1.19.4) lib/teslamate/repair.ex:97: TeslaMate.Repair.repair/1
(teslamate 1.19.4) lib/teslamate/repair.ex:59: TeslaMate.Repair.handle_cast/2
Last message: {:"$gen_cast", :repair}
19:00:25.942 [info] Repairing drive #68 ...
19:00:27.533 [error] GenServer TeslaMate.Repair terminating

** (BadMapError) expected a map, got: nil
(elixir 1.10.3) lib/map.ex:450: Map.get(nil, "house_number", nil)
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:139: TeslaMate.Locations.Geocoder.get_first/2
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:123: TeslaMate.Locations.Geocoder.into_address/1
(teslamate 1.19.4) lib/teslamate/locations/geocoder.ex:16: TeslaMate.Locations.Geocoder.reverse_lookup/3
(teslamate 1.19.4) lib/teslamate/locations.ex:37: TeslaMate.Locations.find_address/1
(teslamate 1.19.4) lib/teslamate/repair.ex:124: TeslaMate.Repair.get_address_id/1
(teslamate 1.19.4) lib/teslamate/repair.ex:97: TeslaMate.Repair.repair/1
(teslamate 1.19.4) lib/teslamate/repair.ex:59: TeslaMate.Repair.handle_cast/2
Last message: {:"$gen_cast", :repair}
19:00:32.536 [info] Application teslamate exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})

Crash dump is being written to: erl_crash.dump...done
```

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Unraid v6.8.3
- User OS & Browser: Windows 10, Chrome

**Comment by flexosvr** [comment]
Few details i left out:
Upon restart of Teslamate - the system would try again and crash. I fixed it by wiping the database completely, removing those data points manually in the CSV and re-importing. 
the points in question are on 7/20/2020 from 07:00 to 07:15.

**Comment by adriankumpf** [comment]
Using the CSV file and your exact times, this could be reproduced very well. Thanks. Fixed on master.
